DROP TABLE AAA6863.PR_MERGE_PC_COMPARE;

CREATE TABLE AAA6863.PR_MERGE_PC_COMPARE
AS
   SELECT TO_CHAR (PR_PC_GRP.PC, '000') SRC_PC,
          TO_CHAR (PR_PC_GRP_1.PC, '000') DEST_PC,
          PR_PC_GRP.PC_GRP,
          PR_PC_GRP.PC_SUBGRP SRC_PC_SUBGRP,
          PR_PC_GRP_1.PC_SUBGRP DEST_PC_SUBGRP
     FROM AAD9606.PR_PC_GRP PR_PC_GRP
          INNER JOIN AAD9606.PR_PC_GRP PR_PC_GRP_1
             ON (PR_PC_GRP.PC_GRP = PR_PC_GRP_1.PC_GRP)
   ORDER BY PR_PC_GRP.PC ASC, PR_PC_GRP_1.PC ASC;
					
GRANT SELECT ON AAA6863.PR_MERGE_PC_COMPARE TO PUBLIC;