CREATE OR REPLACE FORCE VIEW AAA6863.PBO_SLS

AS

SELECT SLS.ACCOUNT_NAME,
       SLS.PRICE_COLUMN,
       SLS.MAIN_CUSTOMER_GK,
       SLS.DISCOUNT_GROUP_NK,
       SLS.DISCOUNT_GROUP_NK_NAME,
       SLS.PRICE_CATEGORY,
       SLS.INVOICE_LINES,
       SLS.AVG_COGS,
-- Sales with no adjustments
       SLS.EXT_SALES TOTAL_SALES,
       PBO.PBO_SLS,
-- Sales less PBO sales from the outer joined view
-- If no PBO sales use 0 so the calculation will work
       SLS.EXT_SALES - NVL(PBO.PBO_SLS,0) EXT_SALES
			 
  FROM AAA6863.PR_MERGE_DATA_2 SLS, 
			AAK9658.PBO_DTL PBO
	
WHERE     SLS.ACCOUNT_NAME = PBO.ACCT(+)
       AND SLS.DISCOUNT_GROUP_NK = PBO.DISC_GRP(+)
       AND SLS.PRICE_COLUMN = PBO.PC(+)
       AND SLS.MAIN_CUSTOMER_GK = PBO.MAIN_CUSTOMER_GK(+)
       AND SLS.PRICE_CATEGORY = PBO.PRICE_CATEGORY(+)
GROUP BY SLS.ACCOUNT_NAME,
         SLS.PRICE_COLUMN,
         SLS.MAIN_CUSTOMER_GK,
         SLS.DISCOUNT_GROUP_NK,
         SLS.DISCOUNT_GROUP_NK_NAME,
         SLS.PRICE_CATEGORY,
         SLS.INVOICE_LINES,
         SLS.AVG_COGS,
         SLS.EXT_SALES,
         PBO.PBO_SLS;
