CREATE OR REPLACE FORCE VIEW AAA6863.PR_MERGE_RECOMMENDATION

AS

SELECT X.ACCOUNT_NAME,
          X.COLUMN_CATEGORY,
          X.MAIN_CUSTOMER_GK,
          DW_CUST.MAIN_CUSTOMER_NK,
          DW_CUST.CUSTOMER_NAME,
          DW_CUST.CUSTOMER_STATUS,
          DW_CUST.SALESMAN_CODE,
          DW_CUST.CUSTOMER_TYPE,
          CUST.SRC_PRICE_COLUMN,
          CUST.DEST_PC,
          CUST.IMPACT_KEY,
          CUST.NET_IMPACT,
          X.MIN_IMPACT_AMT
     FROM (SELECT ACCOUNT_NAME,
                  COLUMN_CATEGORY,
                  SRC_PRICE_COLUMN,
                  MAIN_CUSTOMER_GK,
                  MIN (ABS (IMPACT_AMT)) MIN_IMPACT_AMT
             FROM AAA6863.PR_MERGE_IMPACT_SUMS_JACKSON
           GROUP BY ACCOUNT_NAME, COLUMN_CATEGORY, SRC_PRICE_COLUMN, MAIN_CUSTOMER_GK) X,
          (SELECT ACCOUNT_NAME,
                  COLUMN_CATEGORY,
                  MAIN_CUSTOMER_GK,
                  SRC_PRICE_COLUMN,
                  DEST_PC,
                  IMPACT_KEY,
                  IMPACT_AMT NET_IMPACT,
                  ABS (IMPACT_AMT) IMPACT_AMT
             FROM AAA6863.PR_MERGE_IMPACT_SUMS_JACKSON) CUST,
          DW_FEI.CUSTOMER_DIMENSION DW_CUST
    WHERE     X.MIN_IMPACT_AMT = CUST.IMPACT_AMT
         AND X.MAIN_CUSTOMER_GK = CUST.MAIN_CUSTOMER_GK
          AND X.SRC_PRICE_COLUMN = CUST.SRC_PRICE_COLUMN
          AND X.MAIN_CUSTOMER_GK = DW_CUST.CUSTOMER_GK;

