SELECT WF.ACCOUNT_NAME,
       WF.CATEGORY AS VERTICAL,
       WF.FISCAL_YY,
       SUM(WF.MATRIX_SALES) MATRIX_SALES,
       SUM(WF.MATRIX_COST) MATRIX_COST,
       SUM(WF.CONTRACT_SALES) CONTRACT_SALES,
       SUM(WF.CONTRACT_COST) CONTRACT_COST,
       SUM(WF.MANUAL_SALES) MANUAL_SALES,
       SUM(WF.MANUAL_COST) MANUAL_COST,
       SUM(WF.SP_SALES) SP_SALES,
       SUM(WF.SP_COST) SP_COST,
       SUM(WF.CREDIT_SALES) CREDIT_SALES,
       SUM(WF.CREDIT_COST) CREDIT_COST
  FROM AAD9606.PR_WF_BLND_VERTS_GP_DWV_FTG WF
	GROUP BY
		WF.ACCOUNT_NAME,
    WF.CATEGORY,
    WF.FISCAL_YY
	ORDER BY
		WF.ACCOUNT_NAME,
		WF.CATEGORY;
