DROP TABLE AAA6863.PR_SALESMART_TEST_201802;

CREATE TABLE AAA6863.PR_SALESMART_TEST_201802
AS 

SELECT
	/*
		for JJ
	*/
  
	X.ACCOUNT_NUMBER_NK BR_NO,
	NVL ( X.SELL_ALIAS_NAME, NULL ) BR_NAME, 
	X.SELL_WAREHOUSE_NUMBER_NK WHSE,
	X.SELL_WAREHOUSE_NAME WH_NAME,
	X.PRICE_COLUMN PC,
	X.PRIMARY_VENDOR_NK VENDOR,
	X.PRIMARY_VENDOR_NAME VENDOR_NAME,
	X.CHANNEL_TYPE CHANNEL,
	X.PRICE_CATEGORY,
	X.YEARMONTH,
	SUM ( X.EXT_SALES_AMOUNT ) SALES,
	SUM ( X.EXT_AVG_COGS_AMOUNT ) AVG_COST
	-- MATRIX SALES
	
		
FROM SALES_MART.PRICE_MGMT_DATA_DET X

WHERE X.YEARMONTH = '201802' --BETWEEN  '201602' AND '201801'
	AND X.ACCOUNT_NUMBER_NK IN ( '61', '1550', '2000', '1480' )
	AND X.IC_FLAG = 'REGULAR'
	-- AND X.PRICE_CATEGORY
	-- AND X.PRICE_SUB_CATEGORY
	-- AND X.CHANNEL_TYPE
	-- AND X.SALES_TYPE

GROUP BY
	X.ACCOUNT_NUMBER_NK,
	NVL ( X.SELL_ALIAS_NAME, NULL ), 
	X.SELL_WAREHOUSE_NUMBER_NK,
	X.SELL_WAREHOUSE_NAME,
	X.PRICE_COLUMN,
	X.PRIMARY_VENDOR_NK,
	X.PRIMARY_VENDOR_NAME,
	X.CHANNEL_TYPE,
	X.PRICE_CATEGORY,
	X.YEARMONTH

ORDER BY X.ACCOUNT_NUMBER_NK ASC,
	X.SELL_WAREHOUSE_NUMBER_NK ASC,
	X.CHANNEL_TYPE ASC
;