SELECT DISTINCT

	PRICE.BRANCH_NUMBER_NK,
	PRICE.PRICE_COLUMN AS PC,
	PRICE.PRICE_TYPE AS PTYPE,

	NVL (PRICE.DISC_GROUP,NULL) AS DG,
	NVL (PRICE.MASTER_PRODUCT_NK, NULL) AS PN,
	NVL (PROD.ALT1_CODE, NULL) AS ALT_1,
	
	PRICE.BASIS B,
	PRICE.OPERATOR_USED OP,
	PRICE.MULTIPLIER,
	
	PRICE.UPDATE_TIMESTAMP UPDATE_DATE,
	CONTACTS.RPC
	
FROM DW_FEI.PRICE_DIMENSION PRICE,
	BRANCH_CONTACTS CONTACTS,
	DW_FEI.PRODUCT_DIMENSION PROD
	
WHERE PRICE.BRANCH_NUMBER_NK = CONTACTS.ACCOUNT_NK
	AND PRICE.MASTER_PRODUCT_NK  = PROD.PRODUCT_NK
	AND (PRICE.PRICE_COLUMN      < (170)
	AND CONTACTS.RPC             = 'Midwest'
	AND PRICE.DELETE_DATE       IS NULL
	AND CONTACTS.ACCOUNT_NK      = '1116'
	AND PRICE.PRICE_COLUMN NOT  IN (23))
	
ORDER BY PRICE.BRANCH_NUMBER_NK,
  NVL (PRICE.MASTER_PRODUCT_NK, NULL),
  PRICE.PRICE_COLUMN;
  