
/* substitution variables */
accept p_disc prompt "Please enter mult change"

SELECT DISTINCT BDG.ACCOUNT_NAME,
    PRICE.BRANCH_NUMBER_NK BU_NUM_TEMPLATE_START,
    PRICE.PRICE_COLUMN PC,
    PRICE.DISC_GROUP DG_ALT,
    PRICE.PRICE_TYPE PTYPE,
    PRICE.BASIS B,
    PRICE.OPERATOR_USED O,
    ROUND(PRICE.MULTIPLIER, 4) EXISTING_FACTOR,
    PRICE.UPDATE_TIMESTAMP UPDATE_DATE,
    BDG.RAW_DISC_TO_COST SDTC,
    CONTACTS.RPC,
	NULL,
	'G#'
		|| PRICE.DISC_GROUP
		|| '*'
		|| PRICE.PRICE_COLUMN TRICOMBO,
	PRICE.BASIS BAS,
	CASE
		WHEN PRICE.OPERATOR_USED = '-'
			AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) < 0
		THEN '+'
		WHEN PRICE.OPERATOR_USED = '-'
			AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) > 0
		THEN  '-' 
		WHEN PRICE.OPERATOR_USED = '+'
			AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) > 0
		THEN '+' 
		WHEN PRICE.OPERATOR_USED = '+'
			AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) < 0
		THEN '-'
		WHEN PRICE.OPERATOR_USED = 'X'
		THEN 'X'
		ELSE 
			NULL
	END
		AS OP,
	CASE
		WHEN PRICE.OPERATOR_USED = '-' 
			AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) < 0
		THEN 
			ROUND(1 - (1 - PRICE.MULTIPLIER) / (1 - &p_disc), 3)
		WHEN PRICE.OPERATOR_USED = '-' 
			AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) > 0
		THEN 
			ROUND(1 - (1 - PRICE.MULTIPLIER) / (1 - &p_disc), 3)		
		
		WHEN PRICE.OPERATOR_USED = '+'
			AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) > 0
		THEN 
			ROUND(((1 + PRICE.MULTIPLIER) / (1 - &p_disc))-1, 3)
		
		WHEN PRICE.OPERATOR_USED = '+'
			AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) < 0
		THEN 
			ROUND(((1 + PRICE.MULTIPLIER) / (1 - &p_disc)), 3)
		WHEN PRICE.OPERATOR_USED = 'X'
		THEN 
			ROUND(PRICE.MULTIPLIER / (1 - &p_disc), 3)
		ELSE 
			NULL
	END                        
		AS new_form,
	(SysDate + 1) EFFECTIVE_DATE

FROM DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG,
    DW_FEI.PRICE_DIMENSION PRICE,
    AAF1046.BRANCH_CONTACTS CONTACTS

WHERE BDG.ACCOUNT_NUMBER_NK  = PRICE.BRANCH_NUMBER_NK
	AND BDG.BRANCH_DISC_GROUP_NK = PRICE.DISC_GROUP
	AND CONTACTS.ACCOUNT_NK  = BDG.ACCOUNT_NUMBER_NK		
	AND BDG.ACCOUNT_NAME = 'DETROIT'
	AND (PRICE.PRICE_COLUMN NOT IN (23, 170, 171, 172, 173, 
									175, 180, 181, 182, 183, 
									190, 191, 192, 193, 205)
	AND PRICE.DISC_GROUP IN (0504, 0505, 0511, 0513, 0517, 0525, 0529)
	AND PRICE.PRICE_TYPE = 'G'
	AND CONTACTS.RPC = 'Midwest'
	AND PRICE.DELETE_DATE IS NULL)
ORDER BY PRICE.BRANCH_NUMBER_NK,
    PRICE.DISC_GROUP,
    PRICE.PRICE_COLUMN;