--Pull Group Matrix Formulas
SELECT DISTINCT BDG.ACCOUNT_NAME,
    'G#' || PRICE.DISC_GROUP || '*' || PRICE.PRICE_COLUMN AS TRICOMBO,
    PRICE.BRANCH_NUMBER_NK AS BU_NUM_TEMPLATE_START, 
    PRICE.PRICE_COLUMN AS PC,
    PRICE.DISC_GROUP AS DG_ALT,
    PRICE.PRICE_TYPE AS PTYPE,
    (SYSDATE+1) AS EFFECTIVE_DATE,
    PRICE.BASIS AS B,
    PRICE.OPERATOR_USED AS O,    
    
    -- Logic to adjust mult if needed
      CASE 
        WHEN PRICE.OPERATOR_USED = '-'
        THEN 
          ROUND((1-(1 - PRICE.MULTIPLIER)/.835),4)
        ELSE
          ROUND((PRICE.MULTIPLIER/.835),4)
      END
        AS NEW_FACTOR_TEMPLATE_END,
    
    ROUND(PRICE.MULTIPLIER,4) AS EXISTING_FACTOR,    
    PRICE.UPDATE_TIMESTAMP AS UPDATE_DATE,
    BDG.RAW_DISC_TO_COST AS SDTC,    
    CONTACTS.RPC    
    
FROM DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG,
     DW_FEI.PRICE_DIMENSION PRICE,
     AAF1046.BRANCH_CONTACTS CONTACTS

WHERE (BDG.ACCOUNT_NUMBER_NK = PRICE.BRANCH_NUMBER_NK AND BDG.BRANCH_DISC_GROUP_NK = PRICE.DISC_GROUP)
    AND CONTACTS.ACCOUNT_NK = BDG.ACCOUNT_NUMBER_NK
    AND PRICE.PRICE_TYPE = 'G'
    AND PRICE.DELETE_DATE IS NULL    
    
    --Choose DG Numbers
    AND PRICE.DISC_GROUP IN (0504,0505,0511,0513,0517,0525,0529)
        --Choose Regional Pricing Centers
    AND CONTACTS.RPC = 'Atlantic'
    
    --Exclude BUs?
    --AND BDG.ACCOUNT_NAME NOT IN('LENZ','DW)
    
    --Select Certain BUs?
    
    --AND BDG.ACCOUNT_NAME IN('LAKEWOOD')
    
    --Exclude Price Columns?
    AND PRICE.PRICE_COLUMN NOT IN(170,171,172,173,175,180,181,182,183,190,191,192,193,205)    

         