SELECT PRICE.BRANCH_NUMBER_NK AS BU,
	CONTACTS.ALIAS AS BU_NAME,
	'G#' || PRICE.DISC_GROUP || '*' || PRICE.PRICE_COLUMN AS TRICOMBO,
	PRICE.PRICE_TYPE AS PTYPE,
	NVL(PRICE.DISC_GROUP,PROD.DISCOUNT_GROUP_NK) AS DG,
	DGKOB.H_FM_G,
	PRICE.PRICE_COLUMN AS PC,
	NVL(PROD.ALT1_CODE,'N/A') AS ALT,
	PRICE.BASIS B,
	PRICE.OPERATOR_USED AS O,
	ROUND(PRICE.MULTIPLIER, 4) AS FACTOR,
	'###' AS NEW_FACTOR,
	PRICE.UPDATE_TIMESTAMP UPDATE_DATE,
	CONTACTS.RPC

FROM AAA6863.DG_BY_KOB DGKOB,
	DW_FEI.PRICE_DIMENSION PRICE
	LEFT JOIN DW_FEI.PRODUCT_DIMENSION PROD
	ON PRICE.MASTER_PRODUCT_NK = PROD.PRODUCT_NK,
	AAF1046.BRANCH_CONTACTS CONTACTS

WHERE DGKOB.DG_NK = PRICE.DISC_GROUP
	AND PRICE.BRANCH_NUMBER_NK = CONTACTS.ACCOUNT_NK
	AND PRICE.DELETE_DATE IS NULL
	AND PRICE.PRICE_TYPE = 'G'
	AND CONTACTS.RPC = 'Midwest'
	--AND PRICE.BRANCH_NUMBER_NK = '1300'
	AND PRICE.PRICE_COLUMN IN (170,171,172,173,180,181,182,183,190,191,192,193,205)
	AND DGKOB.H_FM_G = 'NDP'
	
ORDER BY CONTACTS.ALIAS,
	PRICE.DISC_GROUP,
	PRICE.PRICE_COLUMN;
