accept p_disc NUMBER prompt "Please enter mult change"

SELECT DISTINCT PRICE.BRANCH_NUMBER_NK,
    PRICE.PRICE_COLUMN AS PC,
    PROD.ALT1_CODE AS DG_ALT,
    PRICE.PRICE_TYPE AS PTYPE,
    (SYSDATE+1) AS EFFECTIVE_DATE,
    PRICE.BASIS B,
    CASE
        WHEN PRICE.OPERATOR_USED = '-'
          AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) < 0
	THEN '+'
	WHEN PRICE.OPERATOR_USED = '-'
          AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) > 0
	THEN  '-' 
	WHEN PRICE.OPERATOR_USED = '+'
          AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) > 0
	THEN '+' 
	WHEN PRICE.OPERATOR_USED = '+'
          AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) < 0
	THEN '-'
          WHEN PRICE.OPERATOR_USED = 'X'
	THEN 'X'
          ELSE 
		NULL
	END
          AS OP,
	
        CASE
        WHEN PRICE.OPERATOR_USED = '-' 
          AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) < 0
	THEN 
          ROUND(1 - (1 - PRICE.MULTIPLIER) / (1 - &p_disc), 3)
	WHEN PRICE.OPERATOR_USED = '-' 
          AND (1 - PRICE.MULTIPLIER) / (1 - &p_disc) > 0
	THEN 
          ROUND(1 - (1 - PRICE.MULTIPLIER) / (1 - &p_disc), 3)		
	
	WHEN PRICE.OPERATOR_USED = '+'
          AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) > 0
	THEN 
          ROUND(((1 + PRICE.MULTIPLIER) / (1 - &p_disc))-1, 3)
		
	WHEN PRICE.OPERATOR_USED = '+'
          AND (1 + PRICE.MULTIPLIER) / (1 - &p_disc) < 0
	THEN 
          ROUND(((1 + PRICE.MULTIPLIER) / (1 - &p_disc)), 3)
	WHEN PRICE.OPERATOR_USED = 'X'
        THEN 
          ROUND(PRICE.MULTIPLIER / (1 - &p_disc), 3)
	ELSE 
		NULL
	END                        
	AS NEW_FACTOR,    
    
    --Extra Info
    ROUND(PRICE.MULTIPLIER, 4) EXISTING_FACTOR,
    'P#' || PROD.PRODUCT_NK || '*' || PRICE.PRICE_COLUMN AS TRICOMBO,
    PRICE.UPDATE_TIMESTAMP UPDATE_DATE,
    CONTACTS.RPC
    
FROM DW_FEI.PRICE_DIMENSION PRICE,
     DW_FEI.PRODUCT_DIMENSION PROD,
     AAF1046.BRANCH_CONTACTS CONTACTS

WHERE PROD.PRODUCT_NK = PRICE.MASTER_PRODUCT_NK
    AND PRICE.BRANCH_NUMBER_NK = CONTACTS.ACCOUNT_NK
    AND PRICE.PRICE_TYPE = 'P'
    AND PRICE.DELETE_DATE IS NULL
    
    --CHOOSE RPC
    AND CONTACTS.RPC = 'Atlantic'
    
    --CHOOSE BRANCH
    AND CONTACTS.ACCOUNT_NK IN(501,31)
    
    --CHOOSE PRICE COLUMNS
    AND PRICE.PRICE_COLUMN NOT IN (23, 170, 171, 172, 173, 175, 180, 181, 182, 183, 190, 191, 192, 193, 205)

    
    --CHOOSE DGS
    AND PROD.DISCOUNT_GROUP_NK IN(0504,0505,0511,0513,0517,0525,0529)
    
ORDER BY PRICE.BRANCH_NUMBER_NK,
    PROD.ALT1_CODE,
    PRICE.PRICE_COLUMN
    
    