SELECT TPD.FISCAL_YEAR,
       SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       SWD.ACCOUNT_NAME,
       SWD.ACCOUNT_NUMBER_NK,
       IHF.WRITER,
       IHF.YEARMONTH,
       ILF.DISCOUNT_GROUP_NK,
       DG_DIM.DISCOUNT_GROUP_NAME,
       ILF.PRODUCT_NUMBER_NK,
       ILF.ALT_CODE,
       PR_DIM.PRODUCT_NAME,
       SUM (ILF.SHIPPED_QTY),
       SUM (ILF.EXT_SALES_AMOUNT),
       SUM (ILF.EXT_AVG_COGS_AMOUNT),
       SUM (ILF.EXT_ACTUAL_COGS_AMOUNT),
       SUM (ILF.REPLACEMENT_COST)
  FROM    (   (   (   (   DW_FEI.INVOICE_LINE_FACT ILF
                       INNER JOIN
                          DW_FEI.DISCOUNT_GROUP_DIMENSION DG_DIM
                       ON (ILF.DISCOUNT_GROUP_NK = DG_DIM.DISCOUNT_GROUP_NK))
                   INNER JOIN
                      DW_FEI.INVOICE_HEADER_FACT IHF
                   ON (IHF.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK))
               INNER JOIN
                  SALES_MART.SALES_WAREHOUSE_DIM SWD
               ON (IHF.WAREHOUSE_NUMBER = SWD.WAREHOUSE_NUMBER_NK))
           INNER JOIN
              SALES_MART.TIME_PERIOD_DIMENSION TPD
           ON (IHF.YEARMONTH = TPD.YEARMONTH))
       INNER JOIN
          DW_FEI.PRODUCT_DIMENSION PR_DIM
       ON (ILF.PRODUCT_GK = PR_DIM.PRODUCT_GK)
 WHERE     (TPD.FISCAL_YEAR = 'YEAR TO DATE')
       AND (SWD.ACCOUNT_NUMBER_NK = '2000')
       AND (ILF.DISCOUNT_GROUP_NK = '9181')
GROUP BY TPD.FISCAL_YEAR,

         SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ACCOUNT_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         IHF.WRITER,
         IHF.YEARMONTH,
         ILF.DISCOUNT_GROUP_NK,
         DG_DIM.DISCOUNT_GROUP_NAME,
         ILF.PRODUCT_NUMBER_NK,
         ILF.ALT_CODE,
         PR_DIM.PRODUCT_NAME;