Manual CORE ACCA TY = 
    CALCULATE(SUM('DWFEI_STG PR_PBI_PRICE_CAT_SUMS'[CORE_COGS_AMT]),
        'DWFEI_STG TIME_PERIOD_DIMENSION'[ROLL12MONTHS] = "LAST TWELVE MONTHS",
        'DWFEI_STG PR_PBI_PRICE_CAT_SUMS'[PRICE_CATEGORY] = "MANUAL")

Manual Sales TY = 
    CALCULATE(SUM('DWFEI_STG PR_PBI_PRICE_CAT_SUMS'[EXT_SALES_AMT]),
        'DWFEI_STG TIME_PERIOD_DIMENSION'[ROLL12MONTHS] = "LAST TWELVE MONTHS",
        'DWFEI_STG PR_PBI_PRICE_CAT_SUMS'[PRICE_CATEGORY] = "MANUAL")

Manual CORE GP$ = [MANUAL Sales TY]-[MANUAL CORE ACCA TY]

Manual GP% = DIVIDE([MANUAL CORE GP$],[MANUAL Sales TY],0)
