/*
    pulls few results
*/
SELECT DISTINCT WHSE.ACCOUNT_NUMBER_NK,
       WHSE.ACCOUNT_NAME,
       PO_HDR.WAREHOUSE_NUMBER_NK,
       PO_HDR.BRANCH_VENDOR_NK,
       PO_HDR.PO_NUMBER_NK,
       PO_HDR.PO_DATE,
       PO_HDR.PO_DATE_YEARMONTH,
       PO_LINE.RECEIPT_NUMBER,
       PO_LINE.RECEIPT_DATE,
       PO_LINE.RECEIPT_YEARMONTH,
       PO_LINE.PRODUCT_NK,
       PO_LINE.ORDERED_QTY,
       PO_LINE.RECEIVED_QTY,
       PO_LINE.UNIT_COST,
       PO_LINE.EXT_LINE_COST,
       -- ORIGINAL INVOICE
       ILF.PROCESS_DATE,
       ILF.PRODUCT_NUMBER_NK,
       PROD.ALT1_CODE,
       PROD.DISCOUNT_GROUP_NK,
       ILF.ORDERED_QTY,
       ILF.SHIPPED_QTY,
       ILF.EXT_SALES_AMOUNT,
       ILF.EXT_AVG_COGS_AMOUNT,
       ILF.UNIT_NET_PRICE_AMOUNT,
       ILF.ORDER_ENTRY_DATE,
       IHF.CUSTOMER_NUMBER_NK,
       IHF.INVOICE_NUMBER_NK,
       ILF.INVOICE_LINE_NUMBER,
       -- CREDIT MEMO
       ILF2.CREDIT_MEMO_TYPE,
       ILF2.PROCESS_DATE,
       ILF2.PRODUCT_NUMBER_NK,
       ILF2.ORDERED_QTY,
       ILF2.SHIPPED_QTY,
       ILF2.EXT_SALES_AMOUNT,
       ILF2.EXT_AVG_COGS_AMOUNT,
       ILF2.UNIT_NET_PRICE_AMOUNT,
       ILF2.ORDER_ENTRY_DATE,
       ILF2.INVOICE_LINE_NUMBER,
       -- YOU CAN ATTEMPT TO JOIN ANY OF THESE PO TO THE HDR FACT,
       -- IF THEY ARE FEI POS YOU WILL GET SOME MATCHES:
       IHF.TAG_PO,
       IHF.PO_NUMBER,
       IHF.DIRECT_PO_NUMBER,
       CUST.CUSTOMER_NAME,
       IHF.SALE_TYPE,
       BR_VDR.VENDOR_NK,
       BR_VDR.VENDOR_NAME,
       BR_VDR.IC_EDI_WHSE
  FROM DW_FEI.PO_LINE_FACT PO_LINE
       INNER JOIN DW_FEI.INVOICE_LINE_FACT ILF
          ON (PO_LINE.PRODUCT_GK = ILF.PRODUCT_GK)
       INNER JOIN DW_FEI.INVOICE_HEADER_FACT IHF
          ON (IHF.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK)
       --JOIN FROM THE ORIGINAL INVOICE TO THE PO

       INNER JOIN
       DW_FEI.PO_HEADER_FACT PO_HDR
          -- USE ANY OF THE INVOICE PO FIELDS HERE TO JOIN DEPENDING ON SCENARIO
          -- IHF.TAG_PO,
          -- IHF.PO_NUMBER,
          -- IHF.DIRECT_PO_NUMBER,

          ON (    PO_HDR.PO_NUMBER_NK = IHF.DIRECT_PO_NUMBER
              AND PO_HDR.PO_GK = PO_LINE.PO_GK)
       INNER JOIN
       DW_FEI.WAREHOUSE_DIMENSION WHSE
          ON (    WHSE.WAREHOUSE_GK = IHF.SHIP_FROM_WAREHOUSE_GK
              AND PO_HDR.WAREHOUSE_NUMBER_GK = WHSE.WAREHOUSE_GK)
       INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUST
          ON (IHF.CUSTOMER_ACCOUNT_GK = CUST.CUSTOMER_GK)
       INNER JOIN DW_FEI.BRANCH_VENDOR_DIMENSION BR_VDR
          ON (PO_HDR.BRANCH_VENDOR_GK = BR_VDR.VENDOR_GK)
       --JOIN FROM THE CREDIT INVOICE TO THE ORIGINAL INVOICE

       INNER JOIN
       (SELECT *
          FROM DW_FEI.INVOICE_LINE_FACT INV, DW_FEI.WAREHOUSE_DIMENSION WHSE
         WHERE     INV.SELL_WAREHOUSE_NUMBER_NK = WHSE.WAREHOUSE_NUMBER_NK
               AND WHSE.ACCOUNT_NAME = 'DALLAS'
               AND INV.CM_ORIG_INV IS NOT NULL
               AND INV.YEARMONTH BETWEEN 201502 AND 201601) ILF2
          ON (    IHF.INVOICE_NUMBER_NK = ILF2.CM_ORIG_INV
              --AND IHF.ORDER_ENTRY_DATE = ILF2.CM_ORIG_INV_DATE
              AND IHF.WAREHOUSE_NUMBER = ILF2.SELL_WAREHOUSE_NUMBER_NK
              AND ILF.PRODUCT_GK = ILF2.PRODUCT_GK)
      INNER JOIN
        DW_FEI.PRODUCT_DIMENSION PROD
          ON ILF.PRODUCT_NUMBER_NK = PROD.PRODUCT_NK
              
      
WHERE     WHSE.ACCOUNT_NUMBER_NK = '61'
       AND PO_HDR.PO_DATE_YEARMONTH BETWEEN 201502 AND 201601
       AND IHF.CUSTOMER_NUMBER_NK IN
              ('24351',
               '28646',
               '32607',
               '81713',
               '90799',
               '146156',
               '197407',
               '2219',
               '26347',
               '28623',
               '30186',
               '32606',
               '62054',
               '62059')
      AND PROD.DISCOUNT_GROUP_NK IN ( '4162', '4422', '4423' )
;