SELECT DISTINCT
       SWD.DIVISION_NAME AS REGION,
       SUBSTR ( SWD.REGION_NAME, 1 ,3 ) AS DISTRICT,
       SWD.ACCOUNT_NUMBER_NK AS ACCT_NK,
       SWD.ACCOUNT_NAME,
       POHF.WAREHOUSE_NUMBER_NK AS WHSE_NK,
			 POHF.PO_TYPE,
       EMP.USER_LOGON,
			 EMP.INITIALS INI,
       POHF.WRITTEN_BY,
       POLF.PO_NUMBER_NK,
       SUM ( POLF.ORDERED_QTY ) ORD,
       SUM ( POLF.RECEIVED_QTY ) REC,
       POHF.SPC_YN,
       POHF.LPU_YN,
       POHF.EDI_FLAG,
       POHF.SHIP_VIA,
       POHF.PO_NUMBER_NK,
			 BVD.ALPHA,
       BVD.VENDOR_NK,
       BVD.VENDOR_NAME
  FROM   (  (  (  (  (  DW_FEI.EMPLOYEE_DIMENSION EMP
                   RIGHT OUTER JOIN
                     DW_FEI.PO_HEADER_FACT POHF
                   ON ( EMP.EMPLOYEE_TRILOGIE_NK = POHF.EMPLOYEE_TRILOGIE_NK ))
                LEFT OUTER JOIN
                  SALES_MART.SALES_WAREHOUSE_DIM SWD
                ON ( SWD.WAREHOUSE_NUMBER_NK = POHF.WAREHOUSE_NUMBER_NK ))
             INNER JOIN
               SALES_MART.TIME_PERIOD_DIMENSION TPD
             ON ( TPD.YEARMONTH = POHF.PO_DATE_YEARMONTH ))
          INNER JOIN
            DW_FEI.PO_LINE_FACT POLF
          ON ( POHF.PO_GK = POLF.PO_GK ))
       INNER JOIN
         DW_FEI.BRANCH_VENDOR_DIMENSION BVD
       ON ( BVD.VENDOR_GK = POHF.BRANCH_VENDOR_GK ))
			 
 WHERE   ( POHF.INTERBRANCH_WHSE_NK IS NULL )
       AND ( POHF.DELETE_DATE IS NULL )
			 AND ( TPD.ROLLING_MONTH = 'LAST MONTH' )
			 AND ( SWD.ACCOUNT_NUMBER_NK  = '1480' )
       -- AND ( POHF.WAREHOUSE_NUMBER_NK = '290' )
       AND ( POHF.SPC_YN = 'NO' )
GROUP BY
         SWD.DIVISION_NAME,
				 SUBSTR ( SWD.REGION_NAME, 1 ,3 ),
         SWD.ACCOUNT_NUMBER_NK,
         SWD.ACCOUNT_NAME,
         POHF.WAREHOUSE_NUMBER_NK,
         EMP.USER_LOGON,
				 EMP.INITIALS,
         POHF.WRITTEN_BY,
         POLF.PO_NUMBER_NK,
				 POHF.PO_TYPE,
         POHF.SPC_YN,
         POHF.LPU_YN,
         POHF.EDI_FLAG,
         POHF.SHIP_VIA,
         POHF.PO_NUMBER_NK,
			   BVD.ALPHA,
         BVD.VENDOR_NK,
         BVD.VENDOR_NAME
				 
;