SELECT P.PRODUCT_ACCT,
       MP.DISC_GROUP_ID,
       DG.DISCOUNT_GROUP_NAME,
       -- P.PRODUCT_KEY,
       -- P.PRODUCT_ID,
       LEFT (P.PRODUCT_ID, (CHARINDEX ('*', P.PRODUCT_ID)) - 1)
          MPID,
       RIGHT (P.PRODUCT_ID,
              LEN (P.PRODUCT_ID) - CHARINDEX ('*', P.PRODUCT_ID))
          WHSE,
       MP.V_ALT_CODE1,
       MP.VENDOR_PROD_CODE,
       MP.PRODUCT_DESC,
       (ROUND (P.RPLC_COST_AMT, 2))
          RPLC_COST_AMT,
       (V_RPLC_CHG_DATE)
          V_RPLC_CHG_DATE,
       (ROUND (P.AVG_COST_AMT, 2))
          AVG_COST_AMT,
       (ROUND (P.ON_HAND_BAL, 0))
          ON_HAND_BAL,
       (ROUND (P.AVG_DEMAND_AMT, 2))
          DEMAND,
       (ROUND (P.V_BASIS_L, 2))
          BR_LIST,
       (P.V_LAST_PRICE_CHG_DATE)
          V_LAST_PRICE_CHG_DATE,
       DWMP.LIST_PRICE,
       (ROUND (P.V_BASIS_2, 2))
          BASIS_2,
       (ROUND (P.V_BASIS_4, 2))
          BASIS_4,
       (ROUND (P.V_LAST_RPLC_COST_AMT, 2))
          LAST_RPLC_COST_AMT,
       (V_LAST_RPLC_CHG_DATE)
          V_LAST_RPLC_CHG_DATE
FROM [ODS_STG].[PRODUCT] P
     INNER JOIN [ODS_STG].[MASTER_PRODUCT] MP
        ON LEFT (P.PRODUCT_ID, CHARINDEX ('*', P.PRODUCT_ID) - 1) =
           MP.MASTER_PRODUCT_ID
     INNER JOIN [DWFEI_STG].[DISCOUNT_GROUP_DIMENSION] DG
        ON MP.DISC_GROUP_ID = DG.DISCOUNT_GROUP_NK
     INNER JOIN [DWFEI_STG].[PRODUCT_DIMENSION] DWMP
        ON LEFT (P.PRODUCT_ID, CHARINDEX ('*', P.PRODUCT_ID) - 1) =
           DWMP.PRODUCT_NK
     INNER JOIN [DWFEI_STG].[SALES_WAREHOUSE_DIM] SWD
        ON RIGHT (P.PRODUCT_ID,
                  LEN (P.PRODUCT_ID) - CHARINDEX ('*', P.PRODUCT_ID)) =
           SWD.[WAREHOUSE_NUMBER_NK]
AND P.PRODUCT_ACCT = SWD.ACCOUNT_NAME
WHERE     CHARINDEX ('*', P.PRODUCT_ID) > 2
      AND P.PRODUCT_ID NOT LIKE '%NS%'
      -- AND PRODUCT_ACCT IN ('ORL','LAKEWOOD','ATLANTA')
      AND DWMP.LIST_PRICE > 0
      AND DWMP.LIST_PRICE <> P.V_BASIS_L


