SELECT CONCAT (w.BranchName,
               '*',
               P.PriceColumn,
               '*',
               CASE WHEN P.ItemNumber IS NOT NULL THEN 'P#' ELSE 'G#' END,
               ISNULL (P.ItemNumber, P.DiscountGroup)),
       P.Branch,
       w.BranchName,
       P.DiscountGroup,
       P.ItemNumber,
       P.PriceColumn,
       P.LastUpdatedDate,
       P.PMBasis,
       P.PMOper,
       P.PMMult
FROM CaptainSCR_Staging.dbo.PriceMatrix P
     INNER JOIN CaptainSCR_Staging.dbo.Warehouse w ON P.Branch = w.Branch
WHERE     P.DeletedOnDate IS NULL
      AND P.Branch <> '39'
      AND P.DiscountGroup IN ('0144',
                              '0182',
                              '0206',
                              '0207',
                              '0210',
                              '0211',
                              '0238',
                              '0240',
                              '0241',
                              '0251',
                              '0252',
                              '0316',
                              '7661',
                              '7662',
                              '7663',
                              '7667',
                              '7668',
                              '7670',
                              '7671',
                              '7672',
                              '7674',
                              '7675',
                              '7676',
                              '7677',
                              '7678',
                              '7682',
                              '7684',
                              '7687',
                              '7688',
                              '7693',
                              '7700',
                              '7701',
                              '7703',
                              '7711',
                              '9026',
                              '9027',
                              '9137',
                              '9138')
GROUP BY P.Branch,
         w.BranchName,
         P.DiscountGroup,
         P.ItemNumber,
         P.PriceColumn,
         P.LastUpdatedDate,
         P.PMBasis,
         P.PMOper,
         P.PMMult,
         CONCAT (w.BranchName,
                 '*',
                 P.PriceColumn,
                 '*',
                 CASE WHEN P.ItemNumber IS NOT NULL THEN 'P#' ELSE 'G#' END,
                 ISNULL (P.ItemNumber, P.DiscountGroup))