SELECT SWD.DIVISION_NAME AS REGION,
       SWD.REGION_NAME AS DISTRICT,
       SWD.ALIAS_NAME AS ALIAS,
       PM_DET.PRICE_COLUMN,
			 PM_DET.SELL_WAREHOUSE_NUMBER_NK,
       SUM (PM_DET.EXT_SALES_AMOUNT),
       SUM (PM_DET.EXT_AVG_COGS_AMOUNT),
       SUM (PM_DET.EXT_ACTUAL_COGS_AMOUNT)
  FROM    (   SALES_MART.PRICE_MGMT_DATA_DET PM_DET
           INNER JOIN
              SALES_MART.SALES_WAREHOUSE_DIM SWD
           ON (PM_DET.SELL_WAREHOUSE_NUMBER_NK = SWD.WAREHOUSE_NUMBER_NK))
       INNER JOIN
          SALES_MART.TIME_PERIOD_DIMENSION TPD
       ON (PM_DET.YEARMONTH = TPD.YEARMONTH)
 WHERE     (TPD.ROLL12MONTHS = 'LAST TWELVE MONTHS')
       AND (PM_DET.IC_FLAG = 'REGULAR')
       AND (PM_DET.PRICE_COLUMN IN ('180', '680'))
GROUP BY SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ALIAS_NAME,
         TPD.ROLL12MONTHS,
         PM_DET.IC_FLAG,
         PM_DET.PRICE_COLUMN,
				 PM_DET.SELL_WAREHOUSE_NUMBER_NK
		;