SELECT DISTINCT
       --PROD_DIM.PRODUCT_NK PROD,
       PROD_DIM.PRODUCT_NK || '*' || WHSE_DIM.WAREHOUSE_NUMBER_NK PRODUCT,
       WHSE_DIM.ACCOUNT_NAME ACCOUNT,
       WHSE_DIM.WAREHOUSE_NUMBER_NK WHSE,
       WPF.ALT_CODE ALT_1,
       PROD_DIM.PRODUCT_NAME DESCRIPTION,
       --NULL AS VENDOR_CODE,
       WPF.NEW_LIST,
       WPF.LIST_PR,
       WPF.BASIS_2,
       WPF.BASIS_3,
       WPF.REP_COST REP,
       WPF.WHSE_AVG_COST_AMOUNT AC,
       NULL AS PO_COST,
       NULL AS PO_DATE,
       PROD_DIM.LIST_PRICE AS M_LIST,
       WPF.DISCOUNT_GROUP_NK DISC_GRP,
       WPF.LINEBUY LINE,
       WPF.STATUS_TYPE ST,
       WPF.UNIT_OF_MEASUREMENT UM,
       WPF.ON_HAND_QTY OHB,
       WPF.DEMAND_12_MONTHS DMD,
       NULL AS AVAIL,
       NULL AS LOC_OPT,
       VEND.MASTER_VENDOR_NAME VENDOR
       --SWD.DIVISION_NAME
			 
  FROM    (   (   DW_FEI.WAREHOUSE_PRODUCT_FACT WPF
               INNER JOIN
                  DW_FEI.WAREHOUSE_DIMENSION WHSE_DIM
               ON (WPF.WAREHOUSE_GK = WHSE_DIM.WAREHOUSE_GK))
           INNER JOIN
              DW_FEI.PRODUCT_DIMENSION PROD_DIM
           ON (WPF.PRODUCT_GK = PROD_DIM.PRODUCT_GK))
       INNER JOIN
          SALES_MART.SALES_WAREHOUSE_DIM SWD
       ON (SWD.WAREHOUSE_NUMBER_NK = WHSE_DIM.WAREHOUSE_NUMBER_NK)
       INNER JOIN 
          AAM1365.MASTER_DG_TCL TCL
        ON (WPF.DISCOUNT_GROUP_NK = TCL.DG_NK)
       INNER JOIN
          DW_FEI.MASTER_VENDOR_DIMENSION VEND
       ON (PROD_DIM.MANUFACTURER = VEND.MASTER_VENDOR_NK)
        
 WHERE     
       --(WHSE_DIM.ACCOUNT_NAME IN ('DETROIT', 'KC', 'PLYMOUTH', 'DALLAS', 'CHICAGO', 'NASH', 'OHVAL'))
       (WHSE_DIM.ACCOUNT_NAME IN ('NASH', 'DALLAS', 'OHVAL', 'PHOENIX', 'SACRAMENTO', 'HONOLULU', 'CALSTEAM'))
       --(WHSE_DIM.ACCOUNT_NAME IN ('KC', 'CHICAGO', 'PLYMOUTH', 'DETROIT', 'GARDEN', 'COL', 'SEATTLE', 'ANCHORAGE'))
       --AND (WPF.STATUS_TYPE IN ('T', 'S'))
       --AND (SWD.DIVISION_NAME = 'temp')
       --AND (SWD.REGION_NAME = 'temp')
       AND TCL.COMBO = 'COMM WAVE #1'
       AND WPF.DISCOUNT_GROUP_NK IN ( TCL.DG_NK ) 
       --AND WPF.DISCOUNT_GROUP_NK IN ( '1465', '1468' )
       AND (WPF.YEARMONTH = TO_NUMBER (TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')))
;