SELECT SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       SWD.ACCOUNT_NUMBER_NK,
       SWD.ACCOUNT_NAME,
       SWD.WAREHOUSE_NUMBER_NK,
       DISC_HF.DISCREP_AMOUNT,
       DISC_HF.DISCREP_CODE,
       DISC_LF.PO_NUMBER_NK,
       DISC_LF.PO_DATE,
       DISC_LF.RECEIPT,
       DISC_LF.XREF_DATE,
       DISC_LF.MISMATCHES,
       DISC_LF.FRT_DISCREPS,
       DISC_LF.DIR_DISCREPS,
       DISC_LF.DIR_INVOICES,
       DISC_LF.DELETE_DATE,
       DISC_HF.DEBIT_MEMO
  FROM    (   DW_FEI.AP_DISCREP_LINE_FACT DISC_LF
           INNER JOIN
              DW_FEI.AP_DISCREP_HEADER_FACT DISC_HF
           ON (DISC_LF.WAREHOUSE_NUMBER_GK = DISC_HF.WAREHOUSE_NUMBER_GK)
              AND (DISC_LF.AP_DISCREP_GK = DISC_HF.AP_DISCREP_GK))
       INNER JOIN
          SALES_MART.SALES_WAREHOUSE_DIM SWD
       ON (SWD.WAREHOUSE_NUMBER_NK = DISC_HF.WAREHOUSE_NUMBER_NK)
          AND (SWD.WAREHOUSE_NUMBER_NK = DISC_LF.WAREHOUSE_NUMBER_NK)
 WHERE (SWD.WAREHOUSE_NUMBER_NK = '78')
       --AND (DISC_LF.PO_DATE BETWEEN  add_months(trunc(sysdate,'mm'),-1) and last_day(add_months(trunc(sysdate,'mm'),-1)))
	 ;