SELECT SWD.DIVISION_NAME REG,
       SWD.REGION_NAME DIST,
       PM_DET.ACCOUNT_NUMBER_NK BR_NK,
       PM_DET.PRICE_CATEGORY,
       PM_DET.CUSTOMER_TYPE,
       SUM ( PM_DET.EXT_SALES_AMOUNT ) SALES,
       SUM ( PM_DET.EXT_AVG_COGS_AMOUNT ) AC,
			 SUM ( PM_DET.TOTAL_LINES ) LINES,
			 SUM ( PM_DET.LINES_FILLED ) LINES_FILLED
  FROM   (  SALES_MART.TIME_PERIOD_DIMENSION TPD
          INNER JOIN
            SALES_MART.PRICE_MGMT_DATA_DET PM_DET
          ON ( TPD.YEARMONTH = PM_DET.YEARMONTH )
       INNER JOIN
         SALES_MART.SALES_WAREHOUSE_DIM SWD
       ON ( SWD.ACCOUNT_NUMBER_NK = PM_DET.ACCOUNT_NUMBER_NK ))
 WHERE ( PM_DET.YEARMONTH BETWEEN '201508' AND '201602' )
 			 -- AND ( TPD.FISCAL_YEAR_TO_DATE = 'YEAR TO DATE' )
       AND ( PM_DET.ACCOUNT_NUMBER_NK = '1550' )
			 AND ( SUBSTR ( SWD.REGION_NAME, 1 ,3 ) IN ( 
			 	    'D10', 'D11', 'D12', 'D14', 
				    'D30', 'D31', 'D32'
				    --'D50', 'D51', 'D53'
				 )
			)
GROUP BY SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       PM_DET.ACCOUNT_NUMBER_NK,
       PM_DET.PRICE_CATEGORY,
       PM_DET.CUSTOMER_TYPE
ORDER BY SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       PM_DET.ACCOUNT_NUMBER_NK,
       PM_DET.PRICE_CATEGORY,
       PM_DET.CUSTOMER_TYPE
		;