--STEP 3
--BUILD OUT PBOS FOR THE SELECTED MAIN BRANCH
--CHANGE TO PERSONAL SCHEMA

TRUNCATE TABLE AAD9606.PR_DIST_NONTRIL_PBO;

INSERT INTO AAD9606.PR_DIST_NONTRIL_PBO
   SELECT CUST.ACCOUNT_NUMBER_NK,
          CUST.ACCOUNT_NAME,
          CUST.CUST_NK CUSTOMER_NK,
          CUST.CUSTOMER_NAME,
          CUST.PRICE_COLUMN,
          PR_DIM.PRICE_TYPE,
          PR_DIM.MASTER_PRODUCT_NK,
          PR_DIM.LAST_UPDATE,
          PR_DIM.BASIS,
          PR_DIM.OPERATOR_USED,
          PR_DIM.MULTIPLIER,
          PR_DIM.INSERT_TIMESTAMP,
          PR_DIM.UPDATE_TIMESTAMP,
          PR_DIM.DELETE_DATE
   FROM DW_FEI.PRICE_DIMENSION PR_DIM
        INNER JOIN PRICE_MGMT.PR_DIST_BR_PC CUST
           ON (    CUST.ACCOUNT_NUMBER_NK = PR_DIM.BRANCH_NUMBER_NK
               AND CUST.PRICE_COLUMN = PR_DIM.PRICE_COLUMN)
   WHERE CUST.BRANCH_NK = '107'                  -- SPECIFY MAIN BRANCH NUMBER
         AND PR_DIM.DELETE_DATE IS NULL;

COMMIT;