SELECT DISTINCT
       VICT2.ACCOUNT_NUMBER BR_NO,
       VICT2.ACCOUNT_NAME BRANCH,
       VICT2.PRICE_COLUMN PC,
       PC_DEF.PC_SHORT_CAT PC_CAT,
       VICT2.DISCOUNT_GROUP_NK DG_NO,
       VICT2.DISCOUNT_GROUP_NAME,
       VICT2.ALT1_CODE,
       VICT2.PRODUCT_NAME,
       VICT2.TYPE_OF_SALE SALE_TYPE,
       CASE
         WHEN VICT2.PRICE_CATEGORY_OVR = 'OVERRIDE'
         THEN
           'OVERRIDE'
         WHEN VICT2.PRICE_CATEGORY = 'MATRIX_BID'
         THEN
           'MATRIX'
         WHEN VICT2.PRICE_CATEGORY IN ('TOOLS', 'QUOTE', 'OTH/ERROR')
         THEN
           'MANUAL'
         ELSE
           VICT2.PRICE_CATEGORY
       END
         PRICE_CAT,
       VICT2.PRICE_CODE,
       NULL AS "Discount Box",
       NULL AS "Calc Form",
       NULL AS "Net Box",
       VICT2.UNIT_NET_PRICE_AMOUNT "Unit Net",
       VICT2.PRICE_FORMULA "Form",
       VICT2.LIST_PRICE "List",
       VICT2.MATRIX_PRICE,
       VICT2.MATRIX,
       VICT2.SHIPPED_QTY SHPD,
       VICT2.MAIN_CUSTOMER_NK MAIN_NO,
       VICT2.CUSTOMER_NK CUST_NO,
       VICT2.CUSTOMER_NAME,
       VICT2.INVOICE_NUMBER_NK INV_NO,
       VICT2.OML_ASSOC_NAME OML_ASSOC,
       VICT2.WRITER WRTR
  FROM   (  (  DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCOR
             RIGHT OUTER JOIN
               DW_FEI.CUSTOMER_DIMENSION CUST
             ON ( CCOR.CUSTOMER_GK = CUST.CUSTOMER_GK ))
          RIGHT OUTER JOIN
            AAA6863.PR_VICT2_SKU_FITTINGS_6MO VICT2
          ON     ( VICT2.CUSTOMER_NK = CUST.CUSTOMER_NK )
             AND ( CCOR.BRANCH_NUMBER_NK = VICT2.ACCOUNT_NUMBER )
             AND ( CCOR.DISC_GROUP = VICT2.DISCOUNT_GROUP_NK ))
       LEFT OUTER JOIN
         AAA6863.PRICE_COLUMN_DEFINITION PC_DEF
       ON ( VICT2.PRICE_COLUMN = PC_DEF.PRICE_COLUMN )
 WHERE     VICT2.UNIT_NET_PRICE_AMOUNT > 0
       AND VICT2.ALT1_CODE NOT LIKE ( 'SP-%' )
       AND VICT2.DISCOUNT_GROUP_NK = '1076' --IN ('1072', '1076')
			 --AND VICT2.YEARMONTH = '201510'
			 
ORDER BY VICT2.ACCOUNT_NAME,
         VICT2.MAIN_CUSTOMER_NK,
         VICT2.CUSTOMER_NK,
         VICT2.CUSTOMER_NAME,
         VICT2.DISCOUNT_GROUP_NK,
         VICT2.ALT1_CODE,
         VICT2.TYPE_OF_SALE,
         CASE
           WHEN VICT2.PRICE_CATEGORY_OVR = 'OVERRIDE'
           THEN
             'OVERRIDE'
           WHEN VICT2.PRICE_CATEGORY = 'MATRIX_BID'
           THEN
             'MATRIX'
           WHEN VICT2.PRICE_CATEGORY IN ('TOOLS', 'QUOTE', 'OTH/ERROR')
           THEN
             'MANUAL'
           ELSE
             VICT2.PRICE_CATEGORY
         END,
         VICT2.WRITER;