SELECT 	WPF.WAREHOUSE_NK Whse,
		WPF.PRODUCT_NK Prod,
		PROD.ALT1_CODE "Alt-1",
		PROD.PRODUCT_NAME "Prod Description",
		CASE
			WHEN WPF.NEW_LIST = WPF.REP_COST
			THEN NULL
			ELSE WPF.NEW_LIST
		END   AS NEW_LIST,
		(WPF.LIST_PR) "List",
		WPF.BASIS_2 Bas_2,		
		BDG.RAW_DISC_TO_COST "DTC",
		WPF.WHSE_AVG_COST_AMOUNT AC,
		PROD.LIST_PRICE M_LIST,
		WPF.UM_CODE UM_Cd,
		WPF.UNIT_OF_MEASUREMENT UM,
		PROD.DISCOUNT_GROUP_NK DG,
		DISC_GRP.DISCOUNT_GROUP_NAME "DG Description",
		PROD.LINEBUY_NK LB

   FROM DW_FEI.WAREHOUSE_PRODUCT_FACT WPF,
		DW_FEI.WAREHOUSE_DIMENSION WHSE,
		DW_FEI.PRODUCT_DIMENSION PROD,
		DW_FEI.DISCOUNT_GROUP_DIMENSION DISC_GRP,
		DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG,
		AAA6863.CIN_TP_DWYER_DG_LIST CUST,
		AAA6863.OHVAL_BREAKOUT OHV

  WHERE WPF.WAREHOUSE_GK = WHSE.WAREHOUSE_GK
		AND WHSE.ACCOUNT_NAME = BDG.ACCOUNT_NAME
		AND PROD.DISCOUNT_GROUP_GK = BDG.DISCOUNT_GROUP_GK
		AND (WPF.YEARMONTH =
                TO_NUMBER (
							TO_CHAR (
									TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')))
		/* AND NVL (WPF.STATUS_TYPE, 'STOCK') IN
               ('STOCK', 'NN', 'NV', 'S', 'NQ') */
		AND WPF.PRODUCT_GK = PROD.PRODUCT_GK
		AND PROD.DISCOUNT_GROUP_GK = DISC_GRP.DISCOUNT_GROUP_GK
		AND PROD.DISCOUNT_GROUP_NK IN (CUST.DG_NK,4)
		AND WPF.WAREHOUSE_GK IN (OHV.WAREHOUSE_GK)
		AND WHSE.ACCOUNT_NUMBER_NK = '1480'

GROUP BY WPF.WAREHOUSE_NK,
		WPF.PRODUCT_NK,
		PROD.ALT1_CODE,
		PROD.PRODUCT_NAME,
		CASE
			WHEN WPF.NEW_LIST = WPF.REP_COST
			THEN NULL
			ELSE WPF.NEW_LIST
		END,
		WPF.LIST_PR,
		WPF.BASIS_2,		
		BDG.RAW_DISC_TO_COST,
		WPF.WHSE_AVG_COST_AMOUNT,
		PROD.LIST_PRICE,
		WPF.UM_CODE,
		WPF.UNIT_OF_MEASUREMENT,
		PROD.DISCOUNT_GROUP_NK,
		DISC_GRP.DISCOUNT_GROUP_NAME,
		PROD.LINEBUY_NK
		
  ORDER BY PROD.DISCOUNT_GROUP_NK ASC,
		PROD.ALT1_CODE ASC,
		WPF.WAREHOUSE_NK ASC
;