SELECT CUST.CUSTOMER_NK AS CUST_NK,
       CUST.CUSTOMER_ALPHA AS ALPHA,
       CUST.CUSTOMER_NAME AS CUST_NAME,
       CUST.MAIN_CUSTOMER_NK AS MAIN_NK,
       CUST.JOB_YN,
       CUST.SALESMAN_CODE AS SLSM,
       CUST.SEC_SLSM,
       CUST.ALT_SLSM,
       CUST.CUSTOMER_TYPE C_TYPE,
       CUST.BMI_BUDGET_CUST_TYPE,
       CUST.BMI_REPORT_CUST_TYPE,
       CUST.PRICE_COLUMN PC,
       CUST.GROSS_SALES,
       CUST.LAST_SALE,
       CUST.ACCOUNT_NAME ACCT,
       CUST.BRANCH_WAREHOUSE_NUMBER WH_NK,
       CUST.CREDIT_CODE CR_CD,
       CUST.ADDRESS1,
       CUST.ADDRESS2,
       CUST.CITY,
       CUST.STATE,
       CUST.ZIP
  FROM (DW_FEI.CUSTOMER_DIMENSION CUST)
 WHERE  (CUST.ACCOUNT_NUMBER_NK = '1480')
		AND CUST.DELETE_DATE IS NULL
    --AND CUST.PRICE_COLUMN <> 'C'
		AND NOT CUST.CUSTOMER_TYPE IN ('O_INTRBRNCH', 'O_BRCHACCT', 'E_EMPLOY')
ORDER BY CUST.MAIN_CUSTOMER_NK,
				 CUST.CUSTOMER_NK,
         CUST.SALESMAN_CODE
				 ;