CREATE TABLE AAD9606.PR_CTYPE_CONVERSION_ALL
AS

SELECT SWD.DIVISION_NAME REGION,
       SWD.REGION_NAME DISTRICT,
       CTYPE.CUSTOMER_TYPE,
       NVL (CUST.ACTIVE_ACCOUNT_NUMBER_NK, CUST.ACCOUNT_NUMBER_NK)
          ACTIVE_ACCOUNT_NK,
       NVL (CUST.ACTIVE_ACCOUNT_NAME, CUST.ACCOUNT_NAME) ACTIVE_ACCOUNT_NAME,
       CTYPE."CUSTOMER_TYPE _FUTURE" CTYPE_FUTURE,
       CASE
          WHEN CTYPE.CUSTOMER_TYPE || PRICE_COLUMN IN
                  ('P_PLBGCON006',
                   'P_PLBGCON007',
                   'P_PLBGCON008',
                   'P_PLBGCON009')
          THEN
             'P_PLUMBCON_NEW'
          ELSE
             NULL
       END
          CTYPE_HQ,
       CTYPE.TYPE_OBS,
       CTYPE.BUSINESS_GROUP,
       CTYPE.NEW_BUSINESS_GROUP,
       --NVL (CUST.ACTIVE_ACCOUNT_NUMBER_NK, CUST.ACCOUNT_NUMBER_NK)
       --   ACTIVE_ACCOUNT_NK,
       --NVL (CUST.ACTIVE_ACCOUNT_NAME, CUST.ACCOUNT_NAME) ACTIVE_ACCOUNT_NAME,
       NVL (CUST.ACTIVE_CUSTOMER_NK, CUST.CUSTOMER_NK) ACTIVE_CUSTOMER_NK,
       CUST.CUSTOMER_NAME,
       MAX (
          CASE
             WHEN CUST.ACTIVE_ACCOUNT_NAME = CUST.ACCOUNT_NAME
             THEN
                CUST.PRICE_COLUMN
             ELSE
                NULL
          END)
          AS PRICE_COLUMN,
       MAX (
          CASE
             WHEN CUST.ACTIVE_ACCOUNT_NAME = CUST.ACCOUNT_NAME
             THEN
                CUST.SALESMAN_CODE
             ELSE
                NULL
          END)
          AS REP,
       CUST.MSTR_TYPE,
       MAX (CUST.LAST_SALE) LAST_SALE,
       SUM (NVL (SLS.ROLL_12M_SLS, 0)) ROLL_12M_SLS,
       CUST.JOB_YN
  FROM (AAD9606.PR_CTYPE_CONVERT CTYPE
        INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUST
           ON (CTYPE.CUSTOMER_TYPE = CUST.CUSTOMER_TYPE))
       INNER JOIN SALES_MART.BG_CUBE_CUST_DATA SLS
          ON (CUST.CUSTOMER_GK = SLS.CUSTOMER_GK)
       INNER JOIN
       EBUSINESS.SALES_DIVISIONS SWD
          ON (NVL (CUST.ACTIVE_ACCOUNT_NAME, CUST.ACCOUNT_NAME) =
                 SWD.ACCOUNT_NAME)
 WHERE     (CUST.ACCOUNT_NAME <> 'DIST')
       AND (CUST.DELETE_DATE IS NULL)
       --AND (SLS.ROLL_12M_SLS > 0 OR CUST.LAST_SALE > '7/1/2014')
GROUP BY SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         CTYPE.CUSTOMER_TYPE,
         CTYPE."CUSTOMER_TYPE _FUTURE",
         CASE
            WHEN CTYPE.CUSTOMER_TYPE || PRICE_COLUMN IN
                    ('P_PLBGCON006',
                     'P_PLBGCON007',
                     'P_PLBGCON008',
                     'P_PLBGCON009')
            THEN
               'P_PLUMBCON_NEW'
            ELSE
               NULL
         END,
         CTYPE.TYPE_OBS,
         CTYPE.BUSINESS_GROUP,
         CTYPE.NEW_BUSINESS_GROUP,
         NVL (CUST.ACTIVE_ACCOUNT_NUMBER_NK, CUST.ACCOUNT_NUMBER_NK),
         NVL (CUST.ACTIVE_ACCOUNT_NAME, CUST.ACCOUNT_NAME),
         NVL (CUST.ACTIVE_CUSTOMER_NK, CUST.CUSTOMER_NK),
         CUST.CUSTOMER_NAME,
         CUST.MSTR_TYPE,
         CUST.JOB_YN
ORDER BY SWD.REGION_NAME ASC,
         NVL (CUST.ACTIVE_ACCOUNT_NAME, CUST.ACCOUNT_NAME) ASC,
         CTYPE.CUSTOMER_TYPE ASC,
         CUST.CUSTOMER_NAME ASC,
         NVL (CUST.ACTIVE_ACCOUNT_NUMBER_NK, CUST.ACCOUNT_NUMBER_NK) ASC