SELECT DISTINCT
       SALES_WAREHOUSE_DIM.ACCOUNT_NUMBER_NK AS BU_ID, 
       SALES_WAREHOUSE_DIM.ACCOUNT_NAME AS BU_NAME,
       PRICE_DIMENSION.PRICE_COLUMN AS PC
  FROM    DW_FEI.PRICE_DIMENSION PRICE_DIMENSION
       INNER JOIN
          SALES_MART.SALES_WAREHOUSE_DIM SALES_WAREHOUSE_DIM
       ON (PRICE_DIMENSION.BRANCH_NUMBER_NK =
              SALES_WAREHOUSE_DIM.WAREHOUSE_NUMBER_NK)
 WHERE (PRICE_DIMENSION.DELETE_DATE IS NULL)
        AND PRICE_DIMENSION.PRICE_COLUMN NOT IN(0)
        AND (PRICE_DIMENSION.BRANCH_NUMBER_NK =
              SALES_WAREHOUSE_DIM.ACCOUNT_NUMBER_NK)
 ORDER BY SALES_WAREHOUSE_DIM.ACCOUNT_NAME,
          PRICE_DIMENSION.PRICE_COLUMN
  ;
