SELECT MAX(PRICE.BRANCH_NUMBER_NK) AS BU_ID,
    CONTACTS.ALIAS AS BU_NAME,
    PRICE.PRICE_COLUMN AS PC,
    CONTACTS.RPC

FROM DW_FEI.PRICE_DIMENSION PRICE,
    AAF1046.BRANCH_CONTACTS CONTACTS     
     
WHERE CONTACTS.ACCOUNT_NK = PRICE.BRANCH_NUMBER_NK
    AND PRICE.DELETE_DATE IS NULL
    AND PRICE.PRICE_COLUMN NOT IN(0)
	  -- AND PRICE.BRANCH_NUMBER_NK NOT IN ('100', '420')

GROUP BY PRICE.BRANCH_NUMBER_NK,
    CONTACTS.ALIAS,
    PRICE.PRICE_COLUMN,
    CONTACTS.RPC

ORDER BY CONTACTS.ALIAS,
    PRICE.PRICE_COLUMN
    ;