SELECT /*csv*/ DISTINCT
CUST.ACCOUNT_NUMBER_NK As "Main Branch ID",
CUST.ACCOUNT_NAME As "Main Branch Name",
CUST.CUSTOMER_NK As "Cust#",
CUST.CUSTOMER_NAME As "Cust Name",
CUST.CUSTOMER_ALPHA As "Cust Alpha",
CUST.MAIN_CUSTOMER_NK As "Main Cust#",
CUST.JOB_YN As "Job Flag",
CUST.BRANCH_WAREHOUSE_NUMBER As "Branch WH#",
CUST.SALESMAN_CODE As "Sales Code",
CUST.CUSTOMER_TYPE As "Cust Type",
CUST.PRICE_COLUMN As "PC",
CUST.CREDIT_CODE As "Credit Code",
CUST.CREDIT_LIMIT As "Credit Limit",
CUST.GSA_LINK As "GSA Link",
CUST.ACCOUNT_SETUP_DATE As "Account Setup Date"

FROM DW_FEI.CUSTOMER_DIMENSION CUST

WHERE (SYSDATE - CUST.ACCOUNT_SETUP_DATE) <= 8
AND (SYSDATE - CUST.ACCOUNT_SETUP_DATE) >= 0


