DROP TABLE AAA6863.PR_MERGE_PC_COMPARE;

CREATE TABLE AAA6863.PR_MERGE_PC_COMPARE -- Insert Your AA#
AS
   SELECT LTRIM(TO_CHAR (PR_PC_GRP.PC, '000')) SRC_PC,
          LTRIM(TO_CHAR (PR_PC_GRP_1.PC, '000')) DEST_PC,
          PR_PC_GRP.PC_GRP,
          PR_PC_GRP.PC_SUBGRP SRC_PC_SUBGRP,
          PR_PC_GRP_1.PC_SUBGRP DEST_PC_SUBGRP
     FROM AAK9658.PR_PC_GRP PR_PC_GRP --LEAVE THIS AA#/TABLE ALONE
          INNER JOIN AAK9658.PR_PC_GRP PR_PC_GRP_1 --LEAVE THIS AA#/TABLE ALONE 
             ON (PR_PC_GRP.PC_GRP = PR_PC_GRP_1.PC_GRP)
   ORDER BY PR_PC_GRP.PC ASC, PR_PC_GRP_1.PC ASC