/*
    Use for both FYTD and YOY tables
    jb
*/
SELECT PR_CORE_YTD.TPD,
       PR_CORE_YTD.REGION,
       PR_CORE_YTD.DISTRICT,
       PR_CORE_YTD.ACCOUNT_NAME,
       PR_CORE_YTD.YEARMONTH,
       PR_CORE_YTD.HOUSE_FLAG,
       --PR_CORE_YTD.TITLE_DESC,
       --PR_CORE_YTD.SALESREP_NK,
       --PR_CORE_YTD.SALESREP_NAME,
       --HIER.BUSCAT2,
       NVL (HIER.HILEV, 'SP-'),
       HIER.DET1,
       HIER.DET2,
       HIER.DET6,
       SUM (PR_CORE_YTD.LINES) LINES,
       SUM (PR_CORE_YTD.AVG_COGS) AVG_COGS,
       SUM (PR_CORE_YTD.INVOICE_COGS) INVOICE_COGS,
       SUM (PR_CORE_YTD.SALES) SALES,
       SUM (PR_CORE_YTD.CORE_COST_SUBTOTAL) CORE_COST_SUBTOTAL,
       SUM (PR_CORE_YTD.CORE_ADJ_AVG_COGS) CORE_ADJ_AVG_COGS
  FROM AAA6863.PR_CORE_YOY2_041018 PR_CORE_YTD
       LEFT OUTER JOIN USER_SHARED.BUSGRP_PROD_HIERARCHY HIER
          ON (PR_CORE_YTD.DISCOUNT_GROUP_NK = HIER.DISCOUNT_GROUP_NK)
	-- WHERE PR_CORE_YTD.ACCOUNT_NAME = 'LAKEWOOD'
  WHERE HIER.DET2 = 'CARBON STEEL'
  AND HIER.DET1 = 'PIPE & TUBE'
GROUP BY PR_CORE_YTD.TPD,
       PR_CORE_YTD.REGION,
       PR_CORE_YTD.DISTRICT,
       PR_CORE_YTD.ACCOUNT_NAME,
       PR_CORE_YTD.YEARMONTH,
       PR_CORE_YTD.HOUSE_FLAG,
       --PR_CORE_YTD.TITLE_DESC,
       --PR_CORE_YTD.SALESREP_NK,
       --PR_CORE_YTD.SALESREP_NAME,
       --HIER.BUSCAT2,
       NVL (HIER.HILEV, 'SP-'),
       HIER.DET1,
       HIER.DET2,
       HIER.DET6
         --PR_CORE_YTD.DISCOUNT_GROUP_NK,
         --HIER.DESCRIPTION
	;
	
	--remove region
	