DROP TABLE PRICE_MGMT.MISSING_INVOICES;

CREATE TABLE PRICE_MGMT.MISSING_INVOICES
AS
   SELECT h.IC_FLAG,
          h.YEARMONTH,
          h.PO_WAREHOUSE_NUMBER,
          h.WAREHOUSE_NUMBER,
          l.INVOICE_NUMBER_GK,
          l.INVOICE_LINE_NUMBER,
          h.PROCESS_DATE               --,
   --p.INVOICE_NUMBER_GK,
   --p.INVOICE_LINE_NUMBER
   FROM DW_FEI.INVOICE_HEADER_FACT h
   
        INNER JOIN DW_FEI.INVOICE_LINE_FACT l
           ON (h.INVOICE_NUMBER_GK = l.INVOICE_NUMBER_GK)
           
        LEFT OUTER JOIN PRICE_MGMT.PR_PRICE_CAT_HIST p
           ON (    l.INVOICE_NUMBER_GK = p.INVOICE_NUMBER_GK
               AND l.INVOICE_LINE_NUMBER = p.INVOICE_LINE_NUMBER)
               
        LEFT OUTER JOIN PRICE_MGMT.PR_VICT2_SLS_CAT c
           ON h.INVOICE_NUMBER_GK = c.INVOICE_NUMBER_GK
           
   WHERE     h.IC_FLAG = 0
         AND h.PROCESS_DATE > DATE '2019-05-31'  --YEARMONTH BETWEEN 201906 AND 201906
         AND h.PO_WAREHOUSE_NUMBER IS NULL
         AND p.INVOICE_NUMBER_GK IS NULL
         AND p.INVOICE_LINE_NUMBER IS NULL
         AND c.INVOICE_NUMBER_GK IS NULL