SELECT IHF.ACCOUNT_NUMBER,
       IHF.CUSTOMER_NUMBER_NK,
       IHF.INVOICE_NUMBER_NK,
       --IHF.SALE_TYPE,
       IHF.INVOICE_DATE,
       IHF.CRIB_ID,
       IHF.CONSIGN_TYPE,
       PROD.DISCOUNT_GROUP_NK,
       PROD.ALT1_CODE,
       ILF.EXT_SALES_AMOUNT,
       ILF.EXT_AVG_COGS_AMOUNT,
       ILF.SHIPPED_QTY
  FROM   (  DW_FEI.INVOICE_HEADER_FACT IHF
          INNER JOIN
            DW_FEI.INVOICE_LINE_FACT ILF
          ON ( IHF.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK ))
       INNER JOIN
         DW_FEI.PRODUCT_DIMENSION PROD
       ON ( PROD.PRODUCT_GK = ILF.PRODUCT_GK )
 WHERE     ( IHF.ACCOUNT_NUMBER = '2000' )
       AND ( IHF.CUSTOMER_NUMBER_NK = '86729' )
       AND ( IHF.YEARMONTH BETWEEN 201412 AND 201511 )
			 AND ( IHF.CONSIGN_TYPE = 'U' )