/* 
	use for monthly reports in toolbox
		updated specials report to include the columns requested by John Jorstad
	AAE0376 - Jenn
	AAD9606 - Leigh
 */
SELECT DISTINCT
	SP.ACCOUNT_NAME,
	SP.ACCOUNT_NUMBER BR_NK,
	--SP.OML_ASSOC_INI OML INI,
	SP.WRITER WRITER,
	SP.OML_ASSOC_NAME ASSOC_NAME,
	--SP.PRICE_COLUMN PC,
	SP.WAREHOUSE_NUMBER SHIP_WH,
	SP.INVOICE_NUMBER_NK INV_NK,
	--SP.SHIP_VIA_NAME VIA,
	SP.ALT1_CODE ALT_1,
	SP.PRODUCT_NAME PRODUCT,
	SP.STATUS ST,
	SP.UM "U/M",
	SP.DISCOUNT_GROUP_NK DG,
	DG.DISCOUNT_GROUP_NAME DG_NAME,
	SP.SHIPPED_QTY SHPD,
	/* SP.UNIT_NET_PRICE_AMOUNT "UNIT NET",
	ROUND(SP.EXT_AVG_COGS_AMOUNT / SP.SHIPPED_QTY, 2) "UNIT AC",
  CASE
    WHEN SP.EXT_AVG_COGS_AMOUNT = 0 THEN 0
    WHEN SP.EXT_SALES_AMOUNT = 0 THEN 0
    ELSE ROUND((SP.EXT_SALES_AMOUNT - SP.EXT_AVG_COGS_AMOUNT) / SP.EXT_SALES_AMOUNT, 4)
  END "GP %",
	SP.MATRIX_PRICE "MATRIX","
	ROUND(SP.UNIT_NET_PRICE_AMOUNT - SP.MATRIX_PRICE, 2) "MATRIX VAR",*/
	SP.EXT_SALES_AMOUNT EXT_NET,
	SP.CORE_ADJ_AVG_COGS EXT_AC,
	SP.TYPE_OF_SALE SALE_TYPE,
	SP.ORDER_CODE ORDER_CODE,
	SP.CUSTOMER_NK CUST_#,
	SP.CUSTOMER_NAME CUST_NAME,
	/*SP.UNIT_INV_COST UNIT INV,
	SP.REPLACEMENT_COST UNIT REP,
	SP.LIST_PRICE LIST,
	SP.ORDER_ENTRY_DATE ORD DATE,*/
	SP.PRICE_FORMULA FORM,
	SP.PRICE_CODE PRCD,
	/*SP.PRICE_CATEGORY_OVR "PR CAT OVERRIDE",
	SP.TYPE_OF_SALE "SALE TYPE",
	SP.REF_BID_NUMBER "BID #",
	SP.SOURCE_SYSTEM "SOURCE",
	SP.INVOICE_LINE_NUMBER "INV LINE",
	SP.MANUFACTURER "MFG#",
	SP.PR_OVR "PR OVR",
	SP.PR_OVR_BASIS "PR OVR BASIS",
	SP.GR_OVR "GRP OVR"*/
	KOB.CATEGORY KOB,
	SP.CUSTOMER_TYPE

FROM	AAA6863.PR_VICT2_CUST_12MO SP
	LEFT OUTER JOIN DW_FEI.DISCOUNT_GROUP_DIMENSION DG
		ON SP.DISCOUNT_GROUP_NK = DG.DISCOUNT_GROUP_NK
	LEFT OUTER JOIN AAF1046.BRANCH_CONTACTS BC
		ON SP.ACCOUNT_NUMBER = BC.ACCOUNT_NK
	INNER JOIN
			SALES_MART.SALES_WAREHOUSE_DIM SWD
			ON ( SP.ACCOUNT_NUMBER = SWD.ACCOUNT_NUMBER_NK )
	INNER JOIN AAM1365.DG_BY_KOB KOB
			ON KOB.DG_NK = DG.DISCOUNT_GROUP_NK
			
WHERE SP.STATUS IN ('SP-', 'SP')
	AND SP.EXT_SALES_AMOUNT >= 0
	/*AND SP.ACCOUNT_NUMBER IN ('1350',
														'3370',
														'3014',
														'1001',
														'2504',
														'686',
														'3017',
														'3007',
														'109',
														'794',
														'1183',
														'1401',
														'1693',
														'716',
														'1743',
														'3371',
														'3067'
														)*/
	-- AND SP.PRICE_CODE <> 'C'

	/*AND UPPER(BC.RPC) = 'SOUTHERN'
	AND UPPER(BC.RPC) = 'WESTERN'
	AND UPPER(BC.RPC) = 'ATLANTIC'
	AND UPPER(BC.RPC) = 'MIDWEST'*/

	-- AND NOT UPPER(SP.ALT1_CODE) LIKE('SP-%')
	AND ( SUBSTR ( SWD.REGION_NAME, 1 ,3 ) IN (
        'D01', 'D02', 'D03', 'D04', 'D05', 
        'D10', 'D11', 'D12', 'D13',
        'D14', 'D30', 'D31', 'D32',
        'D41', 'D50', 'D51', 'D53'
      	)
			)
ORDER BY
	SP.ACCOUNT_NUMBER ASC,
	SP.DISCOUNT_GROUP_NK ASC,
	SP.ALT1_CODE ASC
	;
