/* 		
		Leigh North		AAD9606
		Jenn Orr 		AAE0376
		Kevin Balsly 	AAA3078
		Brian Shook		AAF1046
		Joe Bredow		AAA6863
*/
--Matrix Backup for all DGs/Products for all Atlantic RPC BUs. Exclude Basis 6

SELECT PRICE.BRANCH_NUMBER_NK AS BU,
	CONTACTS.ALIAS AS BU_NAME,
	
	--Trilogy Combo
	CASE
		WHEN (PRICE.PRICE_TYPE = 'G')
		THEN
			'G#' || PRICE.DISC_GROUP || '*' || PRICE.PRICE_COLUMN
		ELSE
			'P#' || PROD.PRODUCT_NK || '*' || PRICE.PRICE_COLUMN
	END
		AS TRICOMBO,
	
	--PMCM.AUTO Combo Code
	CASE
		WHEN (PRICE.PRICE_TYPE = 'G')
		THEN
			CONTACTS.ALIAS || '*' || PRICE.PRICE_COLUMN || '*G#' || PRICE.DISC_GROUP
		ELSE
			CONTACTS.ALIAS || '*' || PRICE.PRICE_COLUMN || '*P#' || PRICE.MASTER_PRODUCT_NK
		END
			AS PMCM_AUTO_PID,
	
	PRICE.PRICE_TYPE AS PTYPE,
	NVL(PRICE.DISC_GROUP,PROD.DISCOUNT_GROUP_NK) AS DG,  
	PRICE.PRICE_COLUMN AS PC,    
	NVL(PROD.ALT1_CODE,'N/A') AS ALT,            
	PRICE.BASIS B,
	PRICE.OPERATOR_USED AS O,    
	ROUND(PRICE.MULTIPLIER, 4) AS FACTOR,
	PRICE.UPDATE_TIMESTAMP UPDATE_DATE,
	CONTACTS.RPC 
	
FROM DW_FEI.PRICE_DIMENSION PRICE
	LEFT JOIN DW_FEI.PRODUCT_DIMENSION PROD
		ON PRICE.MASTER_PRODUCT_NK = PROD.PRODUCT_NK,
	AAF1046.BRANCH_CONTACTS CONTACTS

WHERE PRICE.BRANCH_NUMBER_NK = CONTACTS.ACCOUNT_NK
	AND PRICE.DELETE_DATE IS NULL
	AND PRICE.PRICE_TYPE NOT IN ('T')
	
	--Choose Group/Product Matrix?
	--AND PRICE.PRICE_TYPE = 'G'
	
	--Choose Regional Pricing Center?
	AND CONTACTS.RPC = 'Midwest'
	
	--Choose Branches?
	--AND CONTACTS.ACCOUNT_NK IN(140)
	
	--Exclude Branches
	--AND CONTACTS.ACCOUNT_NK NOT IN('2623')
	
	--Choose Discount Groups?
	--AND NVL(PRICE.DISC_GROUP, PROD.DISCOUNT_GROUP_NK) IN ('2001')
	
	--Exclude Basis
	AND PRICE.BASIS NOT IN ('6')
	
	--Exclude Price Columns
	AND PRICE.PRICE_COLUMN NOT IN ('0')
	
	--Choose Price Columns?
	--AND PRICE.PRICE_COLUMN NOT IN (170,171,172,173,175,180,181,182,183,190,191,192,193,205)
	
ORDER BY PRICE.BRANCH_NUMBER_NK,
	PRICE.PRICE_COLUMN;
;