SELECT *
FROM (
  (SELECT DISTINCT PRICE.PRICE_TYPE
    || '#'
    || PRICE.DISC_GROUP
    || '*'
    || PRICE.PRICE_COLUMN  AS COMBO_CODE,
    PRICE.BRANCH_NUMBER_NK AS BRANCH,
    CONTACTS.DISTRICT      AS DIST,
    PRICE.PRICE_COLUMN     AS PC,
    PRICE.PRICE_TYPE       AS PTYPE,
    PRICE.DISC_GROUP       AS DG,
    PRICE.DISC_GROUP       AS DG_ITEM,
    DG.DISCOUNT_GROUP_NAME AS DESCR,
    PRICE.BASIS            AS B,
    PRICE.OPERATOR_USED    AS OP,
    PRICE.MULTIPLIER       AS MULT,
    PRICE.UPDATE_TIMESTAMP AS UPDATE_DATE,
    CONTACTS.RPC,
    BDG.RAW_DISC_TO_COST   AS DTC
    --BDG.DISC_TO_COST
  FROM DW_FEI.PRICE_DIMENSION PRICE,
    DW_FEI.discount_group_dimension DG,
    BRANCH_CONTACTS CONTACTS,
    DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG
  WHERE PRICE.BRANCH_NUMBER_NK = CONTACTS.ACCOUNT_NK
  AND DG.DISCOUNT_GROUP_NK     = PRICE.DISC_GROUP
  AND BDG.BRANCH_DISC_GROUP_NK    = PRICE.DISC_GROUP
  AND BDG.ACCOUNT_NUMBER_NK    = CONTACTS.ACCOUNT_NK
  AND (PRICE.PRICE_TYPE        = 'G'
  AND CONTACTS.RPC             = 'Midwest'
  --AND PRICE.BASIS             <> '6'
  AND PRICE.DELETE_DATE       IS NULL)
  )
UNION
  (SELECT DISTINCT PRICE.PRICE_TYPE
    || '#'
    || PRICE.MASTER_PRODUCT_NK
    || '*'
    || PRICE.PRICE_COLUMN  AS COMBO_CODE,
    PRICE.BRANCH_NUMBER_NK AS BRANCH,
    CONTACTS.DISTRICT      AS DIST,
    PRICE.PRICE_COLUMN     AS PC,
    PRICE.PRICE_TYPE       AS PTYPE,
    PRICE.DISC_GROUP       AS DG,
    PROD.ALT1_CODE         AS DG_ITEM,
    PROD.PRODUCT_NAME      AS DESCR,
    PRICE.BASIS            AS B,
    PRICE.OPERATOR_USED    AS OP,
    PRICE.MULTIPLIER       AS MULT,
    PRICE.UPDATE_TIMESTAMP AS UPDATE_DATE,
    CONTACTS.RPC,
    NULL AS x
    --NULL AS y
  FROM DW_FEI.PRICE_DIMENSION PRICE,
    BRANCH_CONTACTS CONTACTS,
    DW_FEI.PRODUCT_DIMENSION PROD
  WHERE PRICE.BRANCH_NUMBER_NK = CONTACTS.ACCOUNT_NK
  AND PRICE.MASTER_PRODUCT_NK  = PROD.PRODUCT_NK
  AND (PRICE.PRICE_TYPE        = 'P'
  AND CONTACTS.RPC             = 'Midwest'
  AND PRICE.BASIS             <> '6'
  AND PRICE.DELETE_DATE       IS NULL)
  )) MTX
ORDER BY MTX.BRANCH,
  MTX.DG_ITEM,
  MTX.PC;