SELECT DISTINCT
       SWD.REGION_NAME,
       SWD.ACCOUNT_NUMBER_NK,
       PRICE.DISC_GROUP,
       PRICE.PRICE_TYPE,
       COUNT (PRICE.MULTIPLIER)
  FROM    DW_FEI.PRICE_DIMENSION PRICE
       INNER JOIN
          EBUSINESS.SALES_DIVISIONS SWD
       ON (PRICE.BRANCH_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK)
 WHERE (SUBSTR (SWD.REGION_NAME, 1, 3) IN
	     ('D10', 'D11', 'D12', 'D13', 'D14', 'D30', 'D31', 'D32')) 
      AND (PRICE.DELETE_DATE IS NULL)
		
 
GROUP BY SWD.REGION_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         PRICE.DISC_GROUP,
         PRICE.PRICE_TYPE;