SELECT DISTINCT
       SUBSTR (SWD.REGION_NAME, 1, 3) DIST,
       SWD.ACCOUNT_NUMBER_NK,
       PRICE.DISC_GROUP,
       NAT_PC.PRICE_COLUMN AS NAT_PC,
       COUNT (PRICE.MULTIPLIER) PC_COUNT
  FROM    (   AAA6863.NAT_BU_PRICE_COLUMNS NAT_PC
           RIGHT OUTER JOIN
              EBUSINESS.SALES_DIVISIONS SWD
           ON (NAT_PC.BRANCH_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK))
       LEFT OUTER JOIN
          DW_FEI.PRICE_DIMENSION PRICE
       ON (PRICE.BRANCH_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK)
 WHERE     (PRICE.DELETE_DATE IS NULL)
       AND (SWD.ACCOUNT_NUMBER_NK = '520')
			 AND (PRICE.PRICE_TYPE = 'G')
			 AND (PRICE.PRICE_COLUMN <> '000')
			 AND (PRICE.PRICE_COLUMN <> '0')
       AND (PRICE.DELETE_DATE IS NULL)
       AND (SUBSTR (SWD.REGION_NAME, 1, 3) IN
                  ('D10', 'D11', 'D12', 'D13', 'D14', 'D30', 'D31', 'D32'))
GROUP BY SWD.REGION_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         PRICE.DISC_GROUP,
         NAT_PC.PRICE_COLUMN
	-- Statement	10/30/2015 9:52:47 AM	0:00:00.561	Query OK	1	0
	;