SELECT PRICED_DGS.ACCOUNT_NAME,
       PRICED_DGS.ACCT,
       PRICED_DGS.DISC_GRP,
       PRICED_DGS.DISCOUNT_GROUP_NAME,
       SUM (PRICED_DGS.PROD_OVR_COUNT) PBO_COUNT,
       SUM (STOCK_DGS.STOCK_SKUS) STOCK_SKUS
  FROM (SELECT SWD.ACCOUNT_NAME,
               PR_DIM.BRANCH_NUMBER_NK ACCT,
               PR_DIM.PRICE_COLUMN PC,
               NVL (PR_DIM.DISC_GROUP, PROD.DISCOUNT_GROUP_NK) DISC_GRP,
               DGRP.DISCOUNT_GROUP_NAME,
               COUNT (PR_DIM.MASTER_PRODUCT_NK) PROD_OVR_COUNT
          FROM DW_FEI.PRICE_DIMENSION PR_DIM,
               DW_FEI.PRODUCT_DIMENSION PROD,
               DW_FEI.DISCOUNT_GROUP_DIMENSION DGRP,
               EBUSINESS.SALES_DIVISIONS SWD
         WHERE     PR_DIM.BRANCH_NUMBER_NK <> '39'
               AND PR_DIM.BRANCH_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK
               AND PR_DIM.MASTER_PRODUCT_NK = PROD.PRODUCT_NK(+)
               AND NVL (PR_DIM.DISC_GROUP, PROD.DISCOUNT_GROUP_NK) =
                      DGRP.DISCOUNT_GROUP_NK
               -- AND PR_DIM.PRICE_TYPE IN ('P')
               AND PR_DIM.DELETE_DATE IS NULL
     -- DO YOU WANT TO EXCLUDE MULT=0 PRICING RECORDS FROM THIS QUERY??                         
               AND NVL (PR_DIM.MULTIPLIER, 0) <> 0
               AND PR_DIM.BRANCH_NUMBER_NK = 226
        GROUP BY PR_DIM.PRICE_COLUMN,
                 PR_DIM.BRANCH_NUMBER_NK,
                 SWD.ACCOUNT_NAME,
                 PR_DIM.DISC_GROUP,
                 PROD.DISCOUNT_GROUP_NK,
                 DGRP.DISCOUNT_GROUP_NAME) PRICED_DGS
       LEFT OUTER JOIN
       (SELECT WPF.YEARMONTH,
               SWD.ACCOUNT_NAME,
               WPF.ACCOUNT_NUMBER_NK ACCT,
               PROD.DISCOUNT_GROUP_NK DISC_GRP,
               DISC_GRP.DISCOUNT_GROUP_NAME,
               COUNT (WPF.WAREHOUSE_NUMBER_NK) STOCKING_WHSES,
               COUNT (DISTINCT WPF.PRODUCT_NK) STOCK_SKUS,
               SUM (WPF.EXTENDED_VALUE) EXT_VALUE
          FROM SALES_MART.WAREHOUSE_PRODUCT_FACT_CURMON WPF,
               SALES_MART.SALES_WAREHOUSE_DIM SWD,
               DW_FEI.PRODUCT_DIMENSION PROD,
               DW_FEI.DISCOUNT_GROUP_DIMENSION DISC_GRP
         WHERE     WPF.WAREHOUSE_NUMBER_NK = SWD.WAREHOUSE_NUMBER_NK
               AND NVL (WPF.STATUS_TYPE, 'STOCK') IN
                      ('STOCK', 'NN', 'NV', 'S', 'NQ')
               AND WPF.PRODUCT_NK = PROD.PRODUCT_NK
               AND PROD.DISCOUNT_GROUP_NK = DISC_GRP.DISCOUNT_GROUP_NK
               AND SWD.ACCOUNT_NAME = 'KC'                        -- <> 'DIST'
        --AND SWD.ACCOUNT_NAME NOT LIKE 'INT%'

        GROUP BY WPF.YEARMONTH,
                 SWD.ACCOUNT_NAME,
                 WPF.ACCOUNT_NUMBER_NK,
                 PROD.DISCOUNT_GROUP_NK,
                 DISC_GRP.DISCOUNT_GROUP_NAME) STOCK_DGS
          ON     PRICED_DGS.ACCT = STOCK_DGS.ACCT
             AND PRICED_DGS.DISC_GRP = STOCK_DGS.DISC_GRP
 WHERE STOCK_DGS.ACCT || STOCK_DGS.DISC_GRP IS NULL
GROUP BY PRICED_DGS.ACCOUNT_NAME,
         PRICED_DGS.ACCT,
         PRICED_DGS.DISC_GRP,
         PRICED_DGS.DISCOUNT_GROUP_NAME