
SELECT SWD.DIVISION_NAME REGION,
       SUBSTR ( SWD.REGION_NAME, 1, 3 ) DIST,
       SWD.ACCOUNT_NUMBER_NK BR_NO,
       SWD.ALIAS_NAME ALIAS,
       PRICE.DISC_GROUP DG_NO,
       COUNT ( DISTINCT PRICE.PRICE_COLUMN ) NO_PCS
  FROM     DW_FEI.PRICE_DIMENSION PRICE
       INNER JOIN
           EBUSINESS.SALES_DIVISIONS SWD
       ON ( PRICE.BRANCH_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK )
 WHERE ( SUBSTR ( SWD.REGION_NAME, 1 ,3 ) ) IN (
              'D10', 'D11', 'D12', 'D13',
              'D14', 'D30', 'D31', 'D32',
              'D50', 'D51', 'D53'
              )
       AND ( PRICE.DELETE_DATE IS NULL )
			 AND ( SWD.ALIAS_NAME = 'OMAHA' )
			 
GROUP BY SWD.DIVISION_NAME,
       SUBSTR ( SWD.REGION_NAME, 1, 3 ),
       SWD.ACCOUNT_NUMBER_NK,
       SWD.ALIAS_NAME,
       PRICE.DISC_GROUP
ORDER BY SWD.DIVISION_NAME,
       SUBSTR ( SWD.REGION_NAME, 1, 3 ),
       SWD.ACCOUNT_NUMBER_NK,
       SWD.ALIAS_NAME,
       PRICE.DISC_GROUP			 
			 ;