SELECT CASE
         WHEN DTL.YEARMONTH BETWEEN 201408 AND 201507 THEN 'FY_15'
         ELSE 'FY_16'
       END
         TPD,
       DTL.ACCOUNT_NUMBER_NK ACCT,
			 DTL.SELL_WAREHOUSE_NUMBER_NK WHSE,
       --  DTL.IC_FLAG,
       DTL.DISCOUNT_GROUP_NK,
			 DTL.DISCOUNT_GROUP_NK_NAME,
			 DTL.PRICE_CATEGORY,
       SUM ( DTL.EXT_SALES_AMOUNT ) EX_SALES,
       SUM ( DTL.EXT_AVG_COGS_AMOUNT ) EX_AC
  FROM SALES_MART.PRICE_MGMT_DATA_DET DTL
 WHERE     ( DTL.YEARMONTH BETWEEN 201408 AND 201607 )
       AND ( DTL.ACCOUNT_NUMBER_NK = '61' )
       AND ( DTL.IC_FLAG = 'REGULAR' )
GROUP BY CASE
           WHEN DTL.YEARMONTH BETWEEN 201408 AND 201507 THEN 'FY_15'
           ELSE 'FY_16'
         END,
         DTL.ACCOUNT_NUMBER_NK,
				 DTL.SELL_WAREHOUSE_NUMBER_NK,
         --  DTL.IC_FLAG,
          DTL.DISCOUNT_GROUP_NK,
			 DTL.DISCOUNT_GROUP_NK_NAME,
				 DTL.PRICE_CATEGORY
				 ;