SELECT GPT_12MO.REGION,
       GPT_12MO.ACCOUNT_NUMBER,
       GPT_12MO.WAREHOUSE_NUMBER_NK,
       GPT_12MO.KOB,
       GPT_12MO.YEARMONTH,
       GPT_12MO.ROLLING_QTR,
       GPT_12MO.TYPE_OF_SALE,
       GPT_12MO.PRICE_CATEGORY,
       SUM (GPT_12MO.EXT_SALES),
       SUM (GPT_12MO.AVG_COGS),
       SUM (GPT_12MO.ACTUAL_COGS),
       SUM (GPT_12MO.INVOICE_LINES)
  FROM AAA6863.GP_TRACKER_13MO GPT_12MO
 WHERE     (GPT_12MO.ACCOUNT_NUMBER IN ('20', '1480', '61'))
       AND (GPT_12MO.PRICE_CATEGORY <> 'Total')
       AND (GPT_12MO.ROLLUP <> 'TOTAL')
GROUP BY GPT_12MO.REGION,
         GPT_12MO.ACCOUNT_NUMBER,
         GPT_12MO.WAREHOUSE_NUMBER_NK,
         GPT_12MO.KOB,
         GPT_12MO.YEARMONTH,
         GPT_12MO.ROLLING_QTR,
         GPT_12MO.TYPE_OF_SALE,
         GPT_12MO.PRICE_CATEGORY,
         GPT_12MO.ROLLUP