SELECT  
       CUST.ACCOUNT_NAME,
       CUST.MAIN_CUSTOMER_NK,
       CUST.CUSTOMER_NK,
       CUST.CUSTOMER_NAME,
       CUST.SALESMAN_CODE,
       CUST.JOB_YN,
       CUST.LAST_SALE,
       CUST.PRICE_COLUMN,
       REC.DEST_PC
  FROM AAA6863.PR_MERGE_REC2 REC
       INNER JOIN
       DW_FEI.CUSTOMER_DIMENSION CUST
          ON    (REC.ACCOUNT_NUMBER_NK = CUST.ACCOUNT_NUMBER_NK)
             AND (REC.MAIN_CUSTOMER_NK = CUST.MAIN_CUSTOMER_NK)
             AND (REC.SRC_PRICE_COLUMN = CUST.PRICE_COLUMN)
WHERE (CUST.DELETE_DATE IS NULL);
