INSERT INTO PRICE_MGMT.PR_PRICE_CAT_HIST

SELECT V.YEARMONTH,
       V.EOM_YEARMONTH,
       V.INVOICE_NUMBER_GK,
       V.INVOICE_LINE_NUMBER,
       V.PRODUCT_GK,
       V.SPECIAL_PRODUCT_GK,
       V.PROCESS_DATE,
       V.SHIPPED_QTY,
       V.EXT_SALES_AMOUNT,
       V.EXT_ACTUAL_COGS_AMOUNT,
       V.CORE_ADJ_AVG_COST,
       V.EXT_AVG_COGS_AMOUNT,
       V.INSERT_TIMESTAMP_IHF INSERT_TIMESTAMP,
       V.PRICE_CODE,
       V.GR_OVR PRICE_CATEGORY_OVR_PR,
       V.PR_OVR PRICE_CATEGORY_OVR_GR,
       V.PRICE_CATEGORY,
       V.ORIG_PRICE_CODE,
       --ORIG_PRICE_CATEGORY,
       V.PRICE_FORMULA,
       V.PRICE_CATEGORY_FINAL,
       V.WAREHOUSE_NUMBER,
       V.CUSTOMER_ACCOUNT_GK
FROM PRICE_MGMT.PR_VICT2_CUST_R2MO V
     LEFT OUTER JOIN PRICE_MGMT.PR_PRICE_CAT_HIST H
        ON     V.INVOICE_NUMBER_GK = H.INVOICE_NUMBER_GK
           AND V.INVOICE_LINE_NUMBER = H.INVOICE_LINE_NUMBER
WHERE H.INVOICE_NUMBER_GK IS NULL AND H.INVOICE_LINE_NUMBER IS NULL;