ALTER TABLE PRICE_MGMT.PR_VICT2_CUST_R2MO DROP COLUMN INVOICE_LINES;
ALTER TABLE PRICE_MGMT.PR_VICT2_CUST_R2MO DROP COLUMN INSERT_TIMESTAMP_ILF;
ALTER TABLE PRICE_MGMT.PR_VICT2_CUST_R2MO DROP COLUMN ORIG_PRICE_CATEGORY;
ALTER TABLE PRICE_MGMT.PR_VICT2_CUST_R2MO DROP COLUMN PRICE_CATEGORY_OVR_PR;
ALTER TABLE PRICE_MGMT.PR_VICT2_CUST_R2MO DROP COLUMN PRICE_CATEGORY_OVR_GR;