/* 
	run this query for the WW Core DG Report monthly 
	pulls 12 months of history from DW_FEI tables
*/

SELECT IHF.ACCOUNT_NUMBER,
	--IHF.WAREHOUSE_NUMBER WHSE,
	SWD.ACCOUNT_NAME,
	ILF.YEARMONTH,
	PROD.DISCOUNT_GROUP_NK,
	CASE
		WHEN  IHF.CHANNEL_TYPE IN('H3', 'H7', 'O3', 'O7') 
		THEN 'Direct'
		ELSE 'Stock'
	END
		AS CHANNEL,
	SUM(ILF.EXT_SALES_AMOUNT) SALES,
	SUM(ILF.EXT_AVG_COGS_AMOUNT) COGS_AC

FROM DW_FEI.INVOICE_LINE_FACT ILF
	
  INNER JOIN DW_FEI.INVOICE_HEADER_FACT IHF
		ON IHF.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK
	
  INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUST
		ON IHF.CUSTOMER_ACCOUNT_GK = CUST.CUSTOMER_GK
	
  /*INNER JOIN AAF1046.BRANCH_CONTACTS BC
		ON CUST.ACCOUNT_NUMBER_NK = BC.ACCOUNT_NK*/
	
	INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
		ON SWD.ACCOUNT_NUMBER_NK = IHF.ACCOUNT_NUMBER
	
  INNER JOIN DW_FEI.PRODUCT_DIMENSION PROD
		ON ILF.PRODUCT_NUMBER_NK   = PROD.PRODUCT_NK
  
  INNER JOIN AAA6863.WW_CORE_GROUPS WWCG
    ON WWCG.DG_NK = PROD.DISCOUNT_GROUP_NK

WHERE ( SUBSTR ( SWD.REGION_NAME, 1 ,3 )) IN ( 
																							'D50',
																							'D51',
																							'D52',
																							'D53',
																							'D54',
																							'D59'
																							)
	--AND IHF.ACCOUNT_NUMBER   = '1105'
	AND ILF.YEARMONTH BETWEEN TO_CHAR (
									TRUNC (
										SYSDATE
										- NUMTOYMINTERVAL (
												12,
										'MONTH'),
									'MONTH'),
								'YYYYMM')
			AND TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')
	AND IHF.YEARMONTH BETWEEN TO_CHAR (
									TRUNC (
										SYSDATE
										- NUMTOYMINTERVAL (
											12,
										'MONTH'),
									'MONTH'),
								'YYYYMM')
			AND TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM') 
	--AND BC.DISTRICT IN ('W50', 'W51', 'W52', 'W53', 'W54')
	
GROUP BY IHF.ACCOUNT_NUMBER,
	--IHF.WAREHOUSE_NUMBER,
	SWD.ACCOUNT_NAME,
	ILF.YEARMONTH,
	PROD.DISCOUNT_GROUP_NK,
	IHF.CHANNEL_TYPE,
	CASE
		WHEN  IHF.CHANNEL_TYPE IN('H3', 'H7', 'O3', 'O7') 
		THEN 'Direct'
		ELSE 'Stock'
	END
;