SELECT SWD.DIVISION_NAME AS REGION,
       SWD.REGION_NAME AS DISTRICT,
       SWD.ACCOUNT_NUMBER_NK,
       PR_V2.DISCOUNT_GROUP_NK,
       PR_V2.DISCOUNT_GROUP_NAME,
       PR_V2.PRICE_CATEGORY,
       SUM (PR_V2.EXT_SALES_AMOUNT),
       SUM (PR_V2.EXT_AVG_COGS_AMOUNT),
       SUM (PR_V2.CORE_ADJ_AVG_COST),
       SWD.WAREHOUSE_NUM_NAME
  FROM AAA6863.PR_VICT2_CUST_12MO PR_V2
       INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
          ON (PR_V2.WAREHOUSE_NUMBER =
                 SWD.WAREHOUSE_NUMBER_NK)
 WHERE ( SUBSTR ( SWD.DIVISION_NAME, 1, 4 ) IN ( 
			 	    'EAST', 'NORT', 'SOUT', 'WEST'
  				 ) )
GROUP BY SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         PR_V2.DISCOUNT_GROUP_NK,
         PR_V2.DISCOUNT_GROUP_NAME,
         PR_V2.PRICE_CATEGORY,
         SWD.WAREHOUSE_NUM_NAME