SELECT HIST.YEARMONTH,
       SWD.ACCOUNT_NUMBER_NK,
       SWD.ACCOUNT_NAME,
       HIST.WAREHOUSE_NUMBER,
       IHF.WRITER,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.MANUFACTURER
          ELSE SP_PROD.PRIMARY_VNDR
       END
          MANUFACTURER,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NK
          ELSE SP_PROD.SPECIAL_PRODUCT_NK
       END
          AS PRODUCT_NK,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.ALT1_CODE
          ELSE SP_PROD.ALT_CODE
       END
          AS ALT1_CODE,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NAME
          ELSE SP_PROD.SPECIAL_PRODUCT_NAME
       END
          AS PRODUCT_NAME,
       SUM (HIST.SHIPPED_QTY)
          SHIPPED_QTY,
       SUM (HIST.EXT_SALES_AMOUNT)
          EXT_SALES_AMOUNT,
       SUM (HIST.EXT_AVG_COGS_AMOUNT)
          EXT_AVG_COGS_AMOUNT,
       SUM (HIST.CORE_ADJ_AVG_COST)
          CORE_ADJ_AVG_COST,
       CHAN.ORDER_CHANNEL,
       CHAN.DELIVERY_CHANNEL,
       DECODE (HIST.PRICE_CATEGORY_FINAL,
               'MATRIX', 'MATRIX',
               'MATRIX_BID', 'MATRIX',
               'NDP', 'MATRIX',
               'MANUAL', 'MANUAL',
               'QUOTE', 'MANUAL',
               'TOOLS', 'MANUAL',
               'OTH/ERROR', 'MANUAL',
               'OVERRIDE', 'OVERRIDE',
               'SPECIALS', 'SPECIALS',
               HIST.PRICE_CATEGORY_FINAL)
          PRICE_CATEGORY,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.DISCOUNT_GROUP_NK
          ELSE SP_PROD.SPECIAL_DISC_GROUP
       END
          AS DISCOUNT_GROUP_NK,
       DG.DISCOUNT_GROUP_NAME,
       REPS.SALESREP_NK,
       REPS.SALESREP_NAME,
       CUST.MAIN_CUSTOMER_NK,
       CUST.CUSTOMER_NK,
       CUST.CUSTOMER_NAME,
       CUST.CUSTOMER_TYPE,
       BG.BUSINESS_GROUP,
       CUST.PRICE_COLUMN
FROM PRICE_MGMT.PR_PRICE_CAT_HIST HIST
     INNER JOIN DW_FEI.INVOICE_HEADER_FACT IHF
        ON (    HIST.INVOICE_NUMBER_GK = IHF.INVOICE_NUMBER_GK
            AND HIST.YEARMONTH = IHF.YEARMONTH)
     INNER JOIN DW_FEI.INVOICE_LINE_FACT ILF
        ON (    HIST.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK
            AND HIST.INVOICE_LINE_NUMBER = ILF.INVOICE_LINE_NUMBER)
     -- USE FOR CUSTOMER BUS GRP
     INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUST
        ON HIST.CUSTOMER_ACCOUNT_GK = CUST.CUSTOMER_GK
     LEFT OUTER JOIN USER_SHARED.BG_CUSTTYPE_XREF BG
        ON COALESCE (CUST.BMI_BUDGET_CUST_TYPE,
                     CUST.BMI_REPORT_CUST_TYPE,
                     CUST.CUSTOMER_TYPE) =
           BG.CUSTOMER_TYPE
     -- USE FOR SALESREP REPORTING
     LEFT OUTER JOIN PRICE_MGMT.CURRENT_SALESREP REPS
        ON     CUST.ACCOUNT_NAME = REPS.ACCOUNT_NAME
           AND CUST.SALESMAN_CODE = REPS.SALESREP_NK
     -- USE FOR CHANNEL TYPE ANALYSIS
     INNER JOIN SALES_MART.INVOICE_CHANNEL_DIMENSION CHAN
        ON IHF.INVOICE_NUMBER_GK = CHAN.INVOICE_NUMBER_GK
     -- USE FOR PRODUCT AND DISCOUNT GROUP
     INNER JOIN DW_FEI.PRODUCT_DIMENSION PROD
        ON HIST.PRODUCT_GK = PROD.PRODUCT_GK
     INNER JOIN DW_FEI.DISCOUNT_GROUP_DIMENSION DG
        ON PROD.DISCOUNT_GROUP_NK = DG.DISCOUNT_GROUP_NK
     LEFT OUTER JOIN USER_SHARED.BUSGRP_PROD_HIERARCHY HIER
        ON PROD.DISCOUNT_GROUP_GK = HIER.DISCOUNT_GROUP_GK
     LEFT OUTER JOIN DW_FEI.SPECIAL_PRODUCT_DIMENSION SP_PROD
        ON HIST.SPECIAL_PRODUCT_GK = SP_PROD.SPECIAL_PRODUCT_GK
--WHERE IHF.ACCOUNT_NUMBER = '1300' AND IHF.YEARMONTH = 201911
GROUP BY HIST.YEARMONTH,
         SWD.ACCOUNT_NUMBER_NK,
         SWD.ACCOUNT_NAME,
         HIST.WAREHOUSE_NUMBER,
         IHF.WRITER,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.MANUFACTURER
            ELSE SP_PROD.PRIMARY_VNDR
         END,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NK
            ELSE SP_PROD.SPECIAL_PRODUCT_NK
         END,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.ALT1_CODE
            ELSE SP_PROD.ALT_CODE
         END,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NAME
            ELSE SP_PROD.SPECIAL_PRODUCT_NAME
         END,
         CHAN.ORDER_CHANNEL,
         CHAN.DELIVERY_CHANNEL,
         DECODE (HIST.PRICE_CATEGORY_FINAL,
                 'MATRIX', 'MATRIX',
                 'MATRIX_BID', 'MATRIX',
                 'NDP', 'MATRIX',
                 'MANUAL', 'MANUAL',
                 'QUOTE', 'MANUAL',
                 'TOOLS', 'MANUAL',
                 'OTH/ERROR', 'MANUAL',
                 'OVERRIDE', 'OVERRIDE',
                 'SPECIALS', 'SPECIALS',
                 HIST.PRICE_CATEGORY_FINAL),
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.DISCOUNT_GROUP_NK
            ELSE SP_PROD.SPECIAL_DISC_GROUP
         END,
         DG.DISCOUNT_GROUP_NAME,
         REPS.SALESREP_NK,
         REPS.SALESREP_NAME,
         CUST.MAIN_CUSTOMER_NK,
         CUST.CUSTOMER_NK,
         CUST.CUSTOMER_NAME,
         CUST.CUSTOMER_TYPE,
         BG.BUSINESS_GROUP,
         CUST.PRICE_COLUMN