Sql.Database("feieimazsrv1.database.windows.net,1433", "feieimazsdw1", [Query="SELECT p_cat.YEARMONTH,
	   tpd.FISCAL_YEAR_TO_DATE,
       tpd.ROLLING_MONTH,
	   icd.ORDER_CHANNEL, 
	   icd.DELIVERY_CHANNEL,
	   wh.WAREHOUSE_NUMBER_NK,
       wh.REGION_NAME,
       SUBSTRING (wh.DISTRICT, 1, 3) AS DIST,
       wh.ACCOUNT_NAME,
       h.HILEV,
       h.DET1,
       h.DET2,
       h.DET6,
       CONCAT (h.DISCOUNT_GROUP_NK, ' - ', h.DESCRIPTION) AS DG_NUM_NAME,
       h.DISCOUNT_GROUP_NK,
       h.DESCRIPTION,
       CASE
          WHEN h.DET2 LIKE '%TANKLESS' THEN 'TKLS'
          WHEN h.DET2 LIKE '%POINT%' THEN 'TKLS'
          WHEN h.DET2 LIKE 'COMM%' THEN 'COMM'
          WHEN h.DET2 LIKE 'RES%' THEN 'RES'
          ELSE 'OTHER'
       END
          AS HIER_CAT,
       SUM (p_cat.EXT_SALES_AMOUNT) AS SUM_EXT_SALES_AMOUNT,
       SUM (p_cat.CORE_ADJ_AVG_COST) AS SUM_CORE_ADJ_AVG_COST,
       SUM (p_cat.SHIPPED_QTY) AS SUM_SHIPPED_QTY
FROM [DWFEI_STG].[TIME_PERIOD_DIMENSION] tpd
  INNER JOIN [DWFEI_STG].[PR_PRICE_CAT_HIST] p_cat
    ON (tpd.YEARMONTH = p_cat.YEARMONTH)
  INNER JOIN [DWFEI_STG].[WHSE_RPT_AREA_VW] wh
    ON  (CONVERT(VARCHAR(8),p_cat.WAREHOUSE_NUMBER) = CONVERT(VARCHAR(8),wh.WAREHOUSE_NUMBER_NK))
  INNER JOIN [DWFEI_STG].[PRODUCT_DIMENSION] prod
    ON (p_cat.PRODUCT_GK = prod.PRODUCT_GK)
  INNER JOIN [DWFEI_STG].[BUSGRP_PROD_HIERARCHY] h
    ON (prod.DISCOUNT_GROUP_GK = h.DISCOUNT_GROUP_GK)
  INNER JOIN[DWFEI_STG].[INVOICE_CHANNEL_DIMENSION]  icd
        ON (p_cat.INVOICE_NUMBER_GK = icd.INVOICE_NUMBER_GK)
WHERE h.DET1 = 'WATER HEATERS'
  AND h.DET6 <> 'OTHER MANUFACTURERS'
  AND (SUBSTRING (wh.REGION_NAME, 1, 4) IN ('EAST', 'CENT', 'WEST'))
  AND (tpd.FISCAL_YEAR_TO_DATE) IS NOT NULL
GROUP BY p_cat.YEARMONTH,
	   tpd.FISCAL_YEAR_TO_DATE,
       tpd.ROLLING_MONTH,
	   icd.ORDER_CHANNEL, 
	   icd.DELIVERY_CHANNEL,
	   wh.WAREHOUSE_NUMBER_NK,
       wh.REGION_NAME,
       SUBSTRING (wh.DISTRICT, 1, 3),
       wh.ACCOUNT_NAME,
       h.HILEV, h.DET1,
       h.DET2, h.DET6,
       CONCAT(h.DISCOUNT_GROUP_NK, ' - ', h.DESCRIPTION),
       h.DISCOUNT_GROUP_NK,
       h.DESCRIPTION,
       CASE
          WHEN h.DET2 LIKE '%TANKLESS'
          THEN 'TKLS'
          WHEN h.DET2 LIKE '%POINT%'
          THEN 'TKLS'
          WHEN h.DET2 LIKE 'COMM%'
          THEN 'COMM'
          WHEN h.DET2 LIKE 'RES%'
          THEN 'RES' ELSE 'OTHER'
      END
"])