SELECT PM_DET.YEARMONTH,
       SWD.DIVISION_NAME AS REGION,
       SWD.REGION_NAME AS DISTRICT,
       SWD.ACCOUNT_NUMBER_NK,
       SWD.ACCOUNT_NAME,
       SWD.WAREHOUSE_NUMBER_NK,
       SWD.WAREHOUSE_NAME,
       PM_DET.WRITER,
       EMP.ASSOC_NAME,
       EMP.TITLE_DESC,
       PM_DET.PRICE_CATEGORY,
       SUM (PM_DET.EXT_SALES_AMOUNT) AS EXT_SALES,
       SUM (PM_DET.EXT_AVG_COGS_AMOUNT) AS EXT_AVG_COGS,
       SUM (PM_DET.TOTAL_LINES) AS EXT_LINES
  FROM ((SALES_MART.PRICE_MGMT_DATA_DET PM_DET
         INNER JOIN SALES_MART.TIME_PERIOD_DIMENSION TIME_PERIOD_DIMENSION
            ON (PM_DET.YEARMONTH = TIME_PERIOD_DIMENSION.YEARMONTH))
        INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
           ON (PM_DET.SELL_WAREHOUSE_NUMBER_NK = SWD.WAREHOUSE_NUMBER_NK))
       LEFT OUTER JOIN DW_FEI.EMPLOYEE_DIMENSION_ORIGINAL EMP
          ON     (PM_DET.WRITER = EMP.INITIALS)
             AND (PM_DET.SELL_WAREHOUSE_NUMBER_NK = EMP.WAREHOUSE_ASSIGNED_NK)
 WHERE     (PM_DET.IC_FLAG = 'REGULAR')
       AND (TIME_PERIOD_DIMENSION.ROLL12MONTHS = 'LAST TWELVE MONTHS')
       AND ( SUBSTR ( SWD.DIVISION_NAME, 1, 4 ) IN ( 
            			 	    'EAST', 'NORT', 'SOUT', 'WEST'
              				 ))
GROUP BY SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         SWD.ACCOUNT_NAME,
         SWD.WAREHOUSE_NUMBER_NK,
         SWD.WAREHOUSE_NAME,
         PM_DET.WRITER,
         EMP.ASSOC_NAME,
         EMP.TITLE_DESC,
         PM_DET.YEARMONTH,
         PM_DET.IC_FLAG,
         PM_DET.PRICE_CATEGORY;