TRUNCATE TABLE AAA6863.PR_SM_TABLEAU_TEST;

DROP TABLE AAA6863.PR_SM_TABLEAU_TEST;

CREATE TABLE AAA6863.PR_SM_TABLEAU_TEST
AS
SELECT PM_DET.YEARMONTH,
       SWD.DIVISION_NAME AS REGION,
       SWD.REGION_NAME AS DISTRICT,
       SWD.ALIAS_NAME,
       SWD.ACCOUNT_NUMBER_NK AS ACCT_HK,
       SWD.ACCOUNT_NAME,
       SWD.WAREHOUSE_NUM_NAME AS SELL_WHSE,
       PM_DET.WRITER,
       PM_DET.DISCOUNT_GROUP_NK_NAME,
       PM_DET.ALT1_CODE_AND_PRODUCT_NAME,
       PM_DET.PRICE_COLUMN,
       PM_DET.SALES_TYPE,
       PM_DET.CUSTOMER_TYPE,
       PM_DET.TYPE_CATEGORY,
       SUM (PM_DET.EXT_SALES_AMOUNT) EXT_SALES,
       SUM (PM_DET.EXT_AVG_COGS_AMOUNT) EXT_AVG_COGS
  FROM SALES_MART.P_PRICE_MGMT_DATA_DET PM_DET
       INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
          ON (PM_DET.SELL_WAREHOUSE_NUMBER_NK = SWD.WAREHOUSE_NUMBER_NK)
 WHERE (SWD.ACCOUNT_NUMBER_NK = '2000') 
    AND (PM_DET.IC_FLAG = 'REGULAR')
    AND (PM_DET.YEARMONTH = '201802')
GROUP BY PM_DET.YEARMONTH,
         SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ALIAS_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         SWD.ACCOUNT_NAME,
         SWD.WAREHOUSE_NUM_NAME,
         PM_DET.WRITER,
         PM_DET.DISCOUNT_GROUP_NK_NAME,
         PM_DET.ALT1_CODE_AND_PRODUCT_NAME,
         PM_DET.PRICE_COLUMN,
         PM_DET.SALES_TYPE,
         PM_DET.IC_FLAG,
         PM_DET.CUSTOMER_TYPE,
         PM_DET.TYPE_CATEGORY;