SELECT/*PARALLEL */
     PRICE_DIMENSION.PRICE_ID,
     PRICE_DIMENSION.DISC_GROUP,
     PRICE_DIMENSION.MASTER_PRODUCT_NK,
     PRICE_DIMENSION.LAST_UPDATE,
     PRICE_DIMENSION.PRICE_COLUMN,
     PRICE_DIMENSION.BASIS,
     PRICE_DIMENSION.OPERATOR_USED,
     PRICE_DIMENSION.MULTIPLIER,
     PRICE_DIMENSION.BRANCH_NUMBER_NK
FROM  DW_FEI.PRICE_DIMENSION PRICE_DIMENSION
WHERE PRICE_DIMENSION.BRANCH_NUMBER_NK IN ('209', '39')
      AND PRICE_DIMENSION.DELETE_DATE IS NULL