/* Formatted on 3/31/2015 2:24:04 PM (QP5 v5.139.911.3011) */
SELECT                                                           /*PARALLEL */
      PRODUCT_DIMENSION.PRODUCT_NK,
       PRODUCT_DIMENSION.ALT1_CODE,
       PRODUCT_DIMENSION.ALT2_CODE,
       PRODUCT_DIMENSION.PRODUCT_NAME,
       DISCOUNT_GROUP_DIMENSION.DISCOUNT_GROUP_NAME,
       PRODUCT_DIMENSION.DISCOUNT_GROUP_NK,
       PRODUCT_DIMENSION.UNIT_OF_MEASURE,
       PRODUCT_DIMENSION.LIST_PRICE,
       PRODUCT_DIMENSION.MANUFACTURER AS MASTER_VENDOR_NK,
       MASTER_VENDOR_DIMENSION.MASTER_VENDOR_NAME
  FROM DW_FEI.DISCOUNT_GROUP_DIMENSION DISCOUNT_GROUP_DIMENSION,
       DW_FEI.MASTER_VENDOR_DIMENSION MASTER_VENDOR_DIMENSION,
       DW_FEI.PRODUCT_DIMENSION PRODUCT_DIMENSION
 WHERE ( (DISCOUNT_GROUP_DIMENSION.DISCOUNT_GROUP_GK =
             PRODUCT_DIMENSION.DISCOUNT_GROUP_GK)
        AND (PRODUCT_DIMENSION.MANUFACTURER =
                MASTER_VENDOR_DIMENSION.MASTER_VENDOR_NK))
       AND PRODUCT_DIMENSION.DELETE_DATE IS NULL