SELECT    BRANCH_DISC_GROUP_GK,
    DISCOUNT_GROUP_GK,
    BRANCH_DISC_GROUP_NK,
    ACCOUNT_NUMBER_NK,
    ACCOUNT_NAME,
    DISC_TO_COST,
    RAW_DISC_TO_COST,
    REP_COST_OK,
    AVG_COST_FACTOR,
    DELETE_DATE,
    INSERT_TIMESTAMP,
    UPDATE_TIMESTAMP
FROM   DW_FEI.BRANCH_DISC_GROUP_DIMENSION
WHERE  DELETE_DATE IS NULL