SELECT SWD.[DIVISION_NAME] REGION,
       SWD.[REGION_NAME] DISTRICT,
       SWD.[ACCOUNT_NUMBER_NK],
       SWD.[WAREHOUSE_NUM_NAME],
       SWD.[ALIAS_NAME],
	   H.[WRITER_INITIALS],
       H.[ORDER_ACCT],
       H.[SELL_WHSE_ID],
       H.[ORDER_ID],
	   LD.[ORDER_LINES_DTL_POS] LN,
       'OPEN' ORDER_STATUS,
       H.[ORDER_CUST],
       CU.[CUST_NAME],
       H.[ORDER_DATE],
       MP.[MASTER_PRODUCT_ID],
       MP.[V_ALT_CODE1],
       MP.[PRODUCT_DESC],
	   LD.[SP_ALT_CODE],
       H.[ORDER_CODE],
       H.[CUST_PO_ID],
       H.[PO_ID],
	   LD.[PER_QTY] "U/M",
	   LD.[ORDER_QTY],
	   LD.[PRICE_FORMULA] FORM,
	   LD.[NET_PRICE],
	   LD.[PRICE_COLUMN],
	   LD.[LIST_PRICE],
	   LD.[UNIT_COST_AMT],
	   LD.[SHIP_QTY],
	   LD.[COST_ADJ_INFO],
	   LD.[ORDER_AVG_COST_AMT],
	   LD.[INV_AVG_COST_AMT],
	   LD.[AVG_COST_CODE],
	   LD.[MPD_AMT],
	   LD.[MPD_FLAG],
	   LD.[ORIG_BASIS],
	   LD.[MANUAL_OVERRIDE_TYPE],
	   LD.[MATRIX_PRICE],
	   LD.[MATRIX_FORMULA],
	   LD.[PRICE_ID],
	   LD.[PROD_UOM],
	   LD.[CORE_CLAIM_ID],
	   LD.[CORE_CNTRT_ID],
	   LD.[CNTRT_COST_TYPE],
	   LD.[DB_INSERT_TS],
	   LD.[ORIG_PRICE_CODE],
       CONVERT (  VARCHAR (10), H.[REQRD_SHIP_DATE], 101) REQRD_SHIP_DATE,
       (LD.NET_PRICE * LD.[RSRV_QTY] / LD.PER_QTY) EXT_SLS,
       (LD.ORDER_AVG_COST_AMT * LD.[RSRV_QTY] / LD.PER_QTY) AVG_COGS,
          LD.[RSRV_QTY] QTY,
         LD.[RSRV_QTY]* MP.[SHIP_WEIGHT]/ LD.PER_QTY  SHIP_WGT,
       CASE WHEN H.SHIP_DATE IS NOT NULL THEN 'Y' ELSE 'N' END SHIP_YN,
       CONVERT (VARCHAR (10), H.[INVOICE_DATE], 101) INVOICE_DATE,
       CONVERT (VARCHAR (10), H.[SHIP_DATE], 101) SHIP_DATE
FROM [ODS_STG].[ORDER_HDR] H
     INNER JOIN [ODS_STG].[ORDER_LINES_DTL] LD
        ON (H.ORDER_KEY = LD.ORDER_KEY)
     INNER JOIN [ODS_STG].[CUSTOMER] CU
        ON H.ORDER_ACCT = CU.CUSTOMER_ACCT AND H.ORDER_CUST = CU.CUSTOMER_ID
     INNER JOIN ODS_STG.MASTER_PRODUCT MP
        ON SUBSTRING(LD.LINE_ITEM,0,CHARINDEX('*',LD.LINE_ITEM,0)) = MP.[MASTER_PRODUCT_ID]
  INNER JOIN DWFEI_STG.SALES_WAREHOUSE_DIM SWD
  ON [WAREHOUSE_NUMBER_NK]=[SELL_WHSE_ID]

WHERE     H.ORDER_DATE >= GETDATE () - 14
  AND SWD.[ACCOUNT_NUMBER_NK] = '2000'
  AND H.[SELL_WHSE_ID] = '945'
  ;