SELECT HIST.YEARMONTH,
       HIST.WAREHOUSE_NUMBER,
       IHF.WRITER,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.MANUFACTURER
          ELSE SP_PROD.PRIMARY_VNDR
       END
          MANUFACTURER,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NK
          ELSE SP_PROD.SPECIAL_PRODUCT_NK
       END
          AS PRODUCT_NK,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.ALT1_CODE
          ELSE SP_PROD.ALT_CODE
       END
          AS ALT1_CODE,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NAME
          ELSE SP_PROD.SPECIAL_PRODUCT_NAME
       END
          AS PRODUCT_NAME,
       SUM (HIST.SHIPPED_QTY)
          SHIPPED_QTY,
       SUM (HIST.EXT_SALES_AMOUNT)
          EXT_SALES_AMOUNT,
       SUM (HIST.EXT_AVG_COGS_AMOUNT)
          EXT_AVG_COGS_AMOUNT,
       SUM (HIST.CORE_ADJ_AVG_COST)
          CORE_ADJ_AVG_COST,
       CHAN.ORDER_CHANNEL,
       CHAN.DELIVERY_CHANNEL,
       CASE HIST.PRICE_CATEGORY_FINAL
            WHEN 'MATRIX' THEN 'MATRIX'
            WHEN 'MATRIX_BID' THEN 'MATRIX'
            WHEN 'NDP' THEN 'MATRIX'
            WHEN 'MANUAL' THEN 'MANUAL'
            WHEN 'QUOTE' THEN 'MANUAL'
            WHEN 'TOOLS' THEN 'MANUAL'
            WHEN 'OTH/ERROR' THEN 'MANUAL'
            WHEN 'OVERRIDE' THEN 'OVERRIDE'
            WHEN 'SPECIALS' THEN 'SPECIALS'
            ELSE HIST.PRICE_CATEGORY_FINAL
       END
          AS PRICE_CATEGORY,
       CASE
          WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.DISCOUNT_GROUP_NK
          ELSE SP_PROD.SPECIAL_DISC_GROUP
       END
          AS DISCOUNT_GROUP_NK,
       DG.DISCOUNT_GROUP_NAME,
       REPS.SALESREP_NK,
       REPS.SALESREP_NAME,
       CUST.MAIN_CUSTOMER_NK,
       CUST.CUSTOMER_NK,
       CUST.CUSTOMER_NAME,
       CUST.CUSTOMER_TYPE,
       BG.BUSINESS_GROUP,
       CUST.PRICE_COLUMN
FROM                [DWFEI_STG].[PR_PRICE_CAT_HIST] HIST
 INNER JOIN [DWFEI_STG].[INVOICE_HEADER_FACT] IHF
  ON HIST.INVOICE_NUMBER_GK = IHF.INVOICE_NUMBER_GK
   AND HIST.YEARMONTH = IHF.YEARMONTH
 INNER JOIN [DWFEI_STG].[INVOICE_LINE_FACT] ILF
        ON (    HIST.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK
            AND HIST.INVOICE_LINE_NUMBER = ILF.INVOICE_LINE_NUMBER)
 INNER JOIN [DWFEI_STG].[CUSTOMER_DIMENSION] CUST
        ON HIST.CUSTOMER_ACCOUNT_GK = CUST.CUSTOMER_GK
 LEFT OUTER JOIN [DWFEI_STG].[BG_CUSTTYPE_XREF] BG
        ON COALESCE (CUST.BMI_BUDGET_CUST_TYPE,
                     CUST.BMI_REPORT_CUST_TYPE,
                     CUST.CUSTOMER_TYPE) = BG.CUSTOMER_TYPE
 LEFT OUTER JOIN [DWFEI_STG].[SALESREP_DIMENSION] REPS
        ON     CUST.ACCOUNT_NAME = REPS.ACCOUNT_NAME
           AND CUST.SALESMAN_CODE = REPS.SALESREP_NK
 INNER JOIN [DWFEI_STG].[INVOICE_CHANNEL_DIMENSION] CHAN
        ON IHF.INVOICE_NUMBER_GK = CHAN.INVOICE_NUMBER_GK
 INNER JOIN [DWFEI_STG].[PRODUCT_DIMENSION] PROD
        ON HIST.PRODUCT_GK = PROD.PRODUCT_GK
 INNER JOIN [DWFEI_STG].[DISCOUNT_GROUP_DIMENSION] DG
        ON PROD.DISCOUNT_GROUP_NK = DG.DISCOUNT_GROUP_NK
 LEFT OUTER JOIN [DWFEI_STG].[BUSGRP_PROD_HIERARCHY] HIER
        ON PROD.DISCOUNT_GROUP_GK = HIER.DISCOUNT_GROUP_GK
 LEFT OUTER JOIN [DWFEI_STG].[SPECIAL_PRODUCT_DIMENSION] SP_PROD
        ON HIST.SPECIAL_PRODUCT_GK = SP_PROD.SPECIAL_PRODUCT_GK
-- WHERE HIST.WAREHOUSE_NUMBER = '2000'
GROUP BY HIST.YEARMONTH,
         HIST.WAREHOUSE_NUMBER,
         IHF.WRITER,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.MANUFACTURER
            ELSE SP_PROD.PRIMARY_VNDR
         END,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NK
            ELSE SP_PROD.SPECIAL_PRODUCT_NK
         END,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.ALT1_CODE
            ELSE SP_PROD.ALT_CODE
         END,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.PRODUCT_NAME
            ELSE SP_PROD.SPECIAL_PRODUCT_NAME
         END,
         CHAN.ORDER_CHANNEL,
         CHAN.DELIVERY_CHANNEL,
         CASE HIST.PRICE_CATEGORY_FINAL
            WHEN 'MATRIX' THEN 'MATRIX'
            WHEN 'MATRIX_BID' THEN 'MATRIX'
            WHEN 'NDP' THEN 'MATRIX'
            WHEN 'MANUAL' THEN 'MANUAL'
            WHEN 'QUOTE' THEN 'MANUAL'
            WHEN 'TOOLS' THEN 'MANUAL'
            WHEN 'OTH/ERROR' THEN 'MANUAL'
            WHEN 'OVERRIDE' THEN 'OVERRIDE'
            WHEN 'SPECIALS' THEN 'SPECIALS'
            ELSE HIST.PRICE_CATEGORY_FINAL
         END,
         CASE
            WHEN HIST.PRODUCT_GK IS NOT NULL THEN PROD.DISCOUNT_GROUP_NK
            ELSE SP_PROD.SPECIAL_DISC_GROUP
         END,
         DG.DISCOUNT_GROUP_NAME,
         REPS.SALESREP_NK,
         REPS.SALESREP_NAME,
         CUST.MAIN_CUSTOMER_NK,
         CUST.CUSTOMER_NK,
         CUST.CUSTOMER_NAME,
         CUST.CUSTOMER_TYPE,
         BG.BUSINESS_GROUP,
         CUST.PRICE_COLUMN