-- REVIEW ACCUMULATION AND GROUPINGS WITH BI TEAM

SELECT 
CONTRACT_ACCT,
AREA,
AREA_NAME,
SLSM_CODE,
SALESMAN_NAME,
CONTRACT_PK,
VENDOR_ID,
VENDOR_NAME,
VENDOR_AGREEMENT,
CONTR_TYPE,
X.CONTRACT_NAME CONTR_NAME,
CONTRACT_STATUS,
CNTRT_START,
CNTRT_EXPIRE,
MAX_MPD_LIMIT,
SUM(MPD_ACCUM) MPD_ACCUM,
SUM(MQ_LIMIT) MQ_LIMIT,
SUM(MPQ_ACCUM) MPQ_ACCUM
FROM

(SELECT ISNULL(CU.[CUSTOMER_ACCT],W.ACCOUNT_NAME) CONTRACT_ACCT,
CU.CUST_BRANCH_ID CUST_WHSE,
CC.WHSE_ID CONTR_WHSE,
W.AREA AREA,
W.RPT_NAME AREA_NAME,
CU.[SLSM_CODE],
SR.[SALESMAN_NAME],
CU.[CUSTOMER_ID],
CU.[CUST_NAME],
C.[CONTRACT_PK],
CASE WHEN C.[CONTRACT_TYPE] = 3 THEN 'COST ONLY' ELSE 'CLAIM ACCRUAL' END CONTR_TYPE,
C.[VENDOR_ID],
V.VENDOR_NAME,
C.[VENDOR_AGREEMENT],
C.[CONTRACT_NAME],
C.[CONTRACT_STATUS],
CONVERT(VARCHAR(10), C.[START_DATE], 101)  CNTRT_START,
CONVERT(VARCHAR(10), C.[END_DATE], 101)  CNTRT_EXPIRE,
C.[REVIEW_DAYS],
CONVERT(VARCHAR(10), C.[LAST_REVIEW_DATE], 101) LAST_REVIEW_DATE,
C.[MAX_MPD_LIMIT],
CP.[GROUP_ID] DISC_GROUP,
DG.[DISC_GROUP_DESC] DISC_GROUP_NAME,
MP.[MASTER_PRODUCT_ID] MPID,
MP.[V_ALT_CODE1] ALT1_CODE,
MP.[PRODUCT_DESC],
CP.[CORE_BASIS],
CP.[CORE_OPERATOR] CORE_OP,
CP.[CORE_VALUE] CORE_MULT,
CP.[CCOR_NET] CORE_NET,
CP.[MD_LIMIT],
CA.[MPD_ACCUM],
--SUM(CA.[MPD_ACCUM]) MPD_ACCUM,
CP.[MQ_LIMIT],
CA.[MPQ_ACCUM],
--SUM(CA.[MPQ_ACCUM]) MPQ_ACCUM,
C.[SUBMITTED_BY],
C.[ENTERED_BY],
C.[APPROVED_BY],
C.[APPROVER_EMAIL]

FROM
[SEC_CORE_STG].[CONTRACT] C

INNER JOIN [SEC_CORE_STG].[CUSTOMER] CC
ON C.[CONTRACT_PK]=CC.[CONTRACT_FK]

INNER JOIN [SEC_CORE_STG].[PRODUCT] CP
ON C.[CONTRACT_PK]=CP.[CONTRACT_FK]

LEFT OUTER JOIN [ODS_STG].[MASTER_PRODUCT] MP
ON CP.[PRODUCT_ID]=MP.[MASTER_PRODUCT_ID]

INNER JOIN [ODS_STG].[DISC_GROUP] DG
ON CP.[GROUP_ID]=DG.[DISC_GROUP_ID]

LEFT OUTER JOIN [ODS_STG].[CUSTOMER] CU
ON CC.[CUSTOMER_ID]=CU.[CUSTOMER_ID]
AND CC.[ACCOUNT_ID]=CU.[CUSTOMER_ACCT]

LEFT OUTER JOIN [ODS_STG].[SALESMAN] SR
ON CU.CUSTOMER_ACCT = SR.SALESMAN_ACCT
AND CU.SLSM_CODE = SR.SALESMAN_ID

LEFT OUTER JOIN [SEC_CORE_STG].[CONTRACT_ACCUM] CA
ON  C.[CONTRACT_PK]=CA.[CONTRACT_FK]
AND CP.PRODUCT_ID = CA.PRODUCT_ID

LEFT OUTER JOIN [SEC_CORE_STG].[MASTER_VENDOR] V
ON C.VENDOR_ID = V.VENDOR_ID

LEFT OUTER JOIN [DWFEI_STG].[WHSE_RPT_AREA_VW] W
ON ISNULL(CC.WHSE_ID,CU.CUST_BRANCH_ID) = W.[WAREHOUSE_NUMBER_NK]

WHERE ISNULL(CU.CUSTOMER_ACCT,'WHSE') = 'LAKEWOOD'
--AND CC.CUSTOMER_ID IS NULL
--AND C.[CONTRACT_PK] = 142119
GROUP BY
ISNULL(CU.[CUSTOMER_ACCT],W.ACCOUNT_NAME),
CU.[SLSM_CODE],
SR.[SALESMAN_NAME],
CU.[CUSTOMER_ID],
CU.[CUST_NAME],
C.[CONTRACT_PK],
CC.WHSE_ID,
CASE WHEN C.[CONTRACT_TYPE] = 3 THEN 'COST ONLY' ELSE 'CLAIM ACCRUAL' END,
C.[VENDOR_ID],
V.VENDOR_NAME,
C.[VENDOR_AGREEMENT],
C.[CONTRACT_NAME],
C.[START_DATE],
C.[END_DATE],
C.[REVIEW_DAYS],
C.[LAST_REVIEW_DATE],
C.[MAX_MPD_LIMIT],
C.[CONTRACT_STATUS],
CP.[GROUP_ID],
DG.[DISC_GROUP_DESC],
MP.[MASTER_PRODUCT_ID],
MP.[V_ALT_CODE1],
MP.[PRODUCT_DESC],
CP.[CORE_BASIS],
CP.[CORE_OPERATOR],
CP.[CORE_VALUE],
CP.[CCOR_NET],
CA.[MPD_ACCUM],
CP.[MD_LIMIT],
CA.[MPQ_ACCUM],
CP.[MQ_LIMIT],
C.[SUBMITTED_BY],
C.[ENTERED_BY],
C.[APPROVED_BY],
C.[APPROVER_EMAIL],
CU.CUST_BRANCH_ID,
W.AREA,
W.RPT_NAME) X
WHERE X.CONTR_TYPE = 'CLAIM ACCRUAL'
AND (ISNULL(X.MAX_MPD_LIMIT,0) + ISNULL(X.MQ_LIMIT,0)) > 0
GROUP BY 
CONTRACT_ACCT,
AREA,
AREA_NAME,
SLSM_CODE,
SALESMAN_NAME,
CONTRACT_PK,
VENDOR_ID,
VENDOR_NAME,
VENDOR_AGREEMENT,
CONTR_TYPE,
CONTRACT_NAME,
CONTRACT_STATUS,
CNTRT_START,
CNTRT_EXPIRE,
MAX_MPD_LIMIT