SELECT CORE.REGION,
       CORE.DISTRICT,
       CORE.ACCOUNT_NAME,
       CORE.TPD,
       CASE
          WHEN CORE.HOUSE_FLAG IN ('O/S', 'H/A') THEN CORE.TITLE_DESC
          ELSE 'HOUSE'
       END
          "TITLE",
       CORE.SALESREP_NK,
       CORE.SALESREP_NAME,
       NVL (HIER.HILEV, 'SP-') HILEV,
       HIER.DET1,
       HIER.FAB5_CAT,
       SUM (CORE.LINES) AS SUM_LINES,
       SUM (CORE.AVG_COGS) AS SUM_AVG_COGS,
       SUM (CORE.INVOICE_COGS) AS SUM_INVOICE_COGS,
       SUM (CORE.SALES) AS SUM_SALES,
       SUM (CORE.CORE_ADJ_AVG_COGS) AS SUM_CORE_ADJ_AVG_COGS,
       SUM (CORE.CLAIM_AMOUNT) AS SUM_CLAIM_AMOUNT,  --UNUSED IN MACRO
       SUM (CORE.COST_ONLY_ADJ) AS SUM_COST_ONLY_ADJ,
       SUM (CORE.CORE_COST_DELTA) AS SUM_CORE_COST_DELTA
       
FROM USER_SHARED.BUSGRP_PROD_HIERARCHY HIER
     INNER JOIN PRICE_MGMT.PR_CORE_YOY_NEW CORE
        ON (HIER.DISCOUNT_GROUP_NK = CORE.DISCOUNT_GROUP_NK)
-- WHERE CORE.ACCOUNT_NAME IN ('LAKEWOOD', 'DETROIT')
GROUP BY CORE.REGION,
         CORE.DISTRICT,
         CORE.ACCOUNT_NAME,
         CORE.TPD,
         CASE
          WHEN CORE.HOUSE_FLAG IN ('O/S', 'H/A') THEN CORE.TITLE_DESC
          ELSE 'HOUSE'
       END,
         CORE.SALESREP_NK,
         CORE.SALESREP_NAME,
         NVL (HIER.HILEV, 'SP-'),
         HIER.DET1,
         HIER.FAB5_CAT
ORDER BY CORE.REGION,
         CORE.DISTRICT,
         CORE.SALESREP_NAME,
         NVL (HIER.HILEV, 'SP-'),
         HIER.DET1,
         CORE.TPD