
SELECT DISTINCT  (CCORG.BRANCH_NUMBER_NK || "^" || CCORG.CUSTOMER_NK) CAT
	CONTACTS.RPC,
	CONTACTS.DISTRICT,
	CCORG.BRANCH_NUMBER_NK,
    CONTACTS.ALIAS,
    CCORG.CUSTOMER_NK,
    CCORG.CONTRACT_ID,
    CCORG.OVERRIDE_ID_NK,
    CCORG.OVERRIDE_TYPE,
    CCORG.DISC_GROUP,
    DG.DISCOUNT_GROUP_NAME,
    NULL AS ALT1_CODE,
    NULL AS PRODUCT_NAME,
    CCORG.EXPIRE_DATE,
    CCORG.BASIS,
    CCORG.OPERATOR_USED,
    CCORG.MULTIPLIER,
    CCORG.INSERT_TIMESTAMP,
    CCORG.UPDATE_TIMESTAMP,
    CCORG.LAST_UPDATE,
    CCORG.DELETE_DATE

FROM DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCORG,
     DW_FEI.DISCOUNT_GROUP_DIMENSION DG,
     AAF1046.BRANCH_CONTACTS CONTACTS
	 LEFT OUTER JOIN (SELECT PS.ACCOUNT_NUMBER_NK BR_NUMBER,
						CUST.CUSTOMER_NK,
						PS.ACCOUNT_NUMBER_NK || '^' || cust.CUSTOMER_NK CAT,
						SUM (NVL (IHF.AVG_COST_SUBTOTAL_AMOUNT, '0')) avg_cogs,
						SUM (NVL (IHF.SALES_SUBTOTAL_AMOUNT, '0')) ext_sales,
						SUM (NVL (IHF.TOTAL_SALES_AMOUNT, '0')) sls_total
							   
					FROM DW_FEI.INVOICE_HEADER_FACT ihf,
						DW_FEI.CUSTOMER_DIMENSION cust,
						SALES_MART.SALES_WAREHOUSE_DIM ps

					WHERE IHF.CUSTOMER_ACCOUNT_GK = CUST.CUSTOMER_GK
						AND IHF.ACCOUNT_NUMBER = 13 
						AND CUST.CUSTOMER_TYPE LIKE ('B_%') 
						AND (IHF.WAREHOUSE_NUMBER) = (PS.WAREHOUSE_NUMBER_NK)
						AND IHF.IC_FLAG = 0
						AND IHF.PO_WAREHOUSE_NUMBER IS NULL
						AND NVL (ihf.CONSIGN_TYPE, 'N') <> 'R'
						AND IHF.YEARMONTH BETWEEN
											TO_CHAR (
													TRUNC (
													   SYSDATE
													   - NUMTOYMINTERVAL (7, 'MONTH'),
													   'MONTH'),
													'YYYYMM')
											 AND TO_CHAR (TRUNC (SYSDATE, 'MM') - 1,
														  'YYYYMM')
						AND DECODE (NVL (cust.ar_gl_number, '9999'),
														  '1320', 0,
														  '1360', 0,
														  '1380', 0,
														  '1400', 0,
														  '1401', 0,
														  '1500', 0,
														  '4000', 0,
														  '7100', 0,
														  '9999', 0,
																  1) <> 0

						AND CUST.AR_GL_NUMBER IS NOT NULL) SLS
				ON SLS.CAT = CCORG.BRANCH_NUMBER_NK || "^" || CCORG.CUSTOMER_NK
     
WHERE CCORG.DISC_GROUP = DG.DISCOUNT_GROUP_NK
    AND CONTACTS.ACCOUNT_NK = CCORG.BRANCH_NUMBER_NK
    AND CCORG.OVERRIDE_TYPE = 'G'
    --AND (SYSDATE - CCORG.INSERT_TIMESTAMP > 365)
    AND CCORG.DELETE_DATE IS NULL
    AND CONTACTS.RPC = 'Midwest'
    
UNION
--Old Product CCORs (12 Month)
SELECT DISTINCT CONTACTS.RPC,
	CONTACTS.DISTRICT,
	CCORP.BRANCH_NUMBER_NK,
    CONTACTS.ALIAS,
    CCORP.CUSTOMER_NK,
    CCORP.CONTRACT_ID,
    CCORP.OVERRIDE_ID_NK,
    CCORP.OVERRIDE_TYPE,
    PROD.DISCOUNT_GROUP_NK,
    DG.DISCOUNT_GROUP_NAME,
    PROD.ALT1_CODE,
    PROD.PRODUCT_NAME,
    CCORP.EXPIRE_DATE,
    CCORP.BASIS,
    CCORP.OPERATOR_USED,
    CCORP.MULTIPLIER,
    CCORP.INSERT_TIMESTAMP,
    CCORP.UPDATE_TIMESTAMP,
    CCORP.LAST_UPDATE,
    CCORP.DELETE_DATE
    
FROM DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCORP,
     DW_FEI.PRODUCT_DIMENSION PROD,
     DW_FEI.DISCOUNT_GROUP_DIMENSION DG,
     AAF1046.BRANCH_CONTACTS CONTACTS
     
WHERE CCORP.MASTER_PRODUCT = PROD.PRODUCT_NK
    AND PROD.DISCOUNT_GROUP_NK = DG.DISCOUNT_GROUP_NK
    AND CONTACTS.ACCOUNT_NK = CCORP.BRANCH_NUMBER_NK
    AND CCORP.OVERRIDE_TYPE = 'P'
    --AND (SYSDATE - CCORP.INSERT_TIMESTAMP > 365)
    AND CCORP.DELETE_DATE IS NULL
    AND CONTACTS.RPC = 'Midwest';

	--GRANT SELECT ON AAA6863.CCOR_MIDWEST_1213 TO PUBLIC;