SELECT IHF.ACCOUNT_NUMBER,
       IHF.YEARMONTH,
       ILF.DISCOUNT_GROUP_GK,
       IHF.CUSTOMER_NUMBER_NK,
       CD.CUSTOMER_NAME,
       CD.MAIN_CUSTOMER_NK,
       ILF.PRICE_CODE,
       IHF.CONTRACT_NUMBER,
       CD.SALESMAN_CODE,
       SUM( ILF.UNIT_NET_PRICE_AMOUNT) EX_SALES,
       SUM( ILF.EXT_AVG_COGS_AMOUNT) EX_AVG_COGS,
       SUM( ILF.CORE_ADJ_AVG_COST) EX_CORE_AC
  
FROM (((DW_FEI.INVOICE_HEADER_FACT IHF
        INNER JOIN SALES_MART.TIME_PERIOD_DIMENSION TPD
           ON (IHF.YEARMONTH = TPD.YEARMONTH))
       INNER JOIN DW_FEI.INVOICE_LINE_FACT ILF
          ON (ILF.INVOICE_NUMBER_GK = IHF.INVOICE_NUMBER_GK))
      INNER JOIN DW_FEI.CUSTOMER_CONTRACT_DIMENSION CCD
         ON (CCD.CUSTOMER_NK = IHF.CUSTOMER_NUMBER_NK))
     INNER JOIN DW_FEI.CUSTOMER_DIMENSION CD
        ON (CCD.CUSTOMER_GK = CD.CUSTOMER_GK)
        
WHERE     (IHF.ACCOUNT_NUMBER = '5')
      AND (TPD.ROLL12MONTHS = 'LAST TWELVE MONTHS')
      AND (ILF.PRICE_CODE = 'CB')
      AND (IHF.CONTRACT_NUMBER = 'GOODMANCB')

GROUP BY IHF.ACCOUNT_NUMBER,
       IHF.YEARMONTH,
       ILF.DISCOUNT_GROUP_GK,
       IHF.CUSTOMER_NUMBER_NK,
       CD.CUSTOMER_NAME,
       CD.MAIN_CUSTOMER_NK,
       ILF.PRICE_CODE,
       IHF.CONTRACT_NUMBER,
       CD.SALESMAN_CODE;