SELECT 
	BC.DISTRICT,
	JOBS.ACCOUNT_NUMBER_NK,
	JOBS.CUSTOMER_NK,
	CCD.CUSTOMER_NAME,
	JOBS.JOB_NAME,
	JOBS.JOB_DESC,
	JOBS.JOB_LOC
FROM 
	BRANCH_CONTACTS BC
	INNER JOIN DW_FEI.JOBS_FACT JOBS
		ON BC.ACCOUNT_NK = JOBS.ACCOUNT_NUMBER_NK
	INNER JOIN DW_FEI.CUSTOMER_DIMENSION CCD
		ON JOBS.CUSTOMER_GK        = CCD.CUSTOMER_GK
		AND JOBS.ACCOUNT_NUMBER_NK = CCD.ACCOUNT_NUMBER_NK
WHERE BC.DISTRICT LIKE ('W%')
	AND JOBS.DELETE_DATE IS NULL
ORDER BY 
	BC.DISTRICT,
	JOBS.CUSTOMER_NK
;