-- working delivery and install report for Scott King

SELECT X.*, WD.WAREHOUSE_NUMBER_NK
FROM (

SELECT ILF.YEARMONTH,
       SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       SWD.WAREHOUSE_NUM_NAME,
       PROD.ALT1_CODE,
       PROD.PRODUCT_NAME,
       IHF.INVOICE_NUMBER_NK,
       IHF.WRITER "Writer",
       P_CAT.PRICE_CATEGORY_FINAL,
       DC.REGIONAL_DC,
       IHF.SHIP_FROM_WAREHOUSE_GK,
       SUM (ILF.SHIPPED_QTY) AS SHIPPED_QTY,
       SUM (ILF.EXT_SALES_AMOUNT) AS EXT_SALES_AMOUNT,
       SUM (ILF.EXT_ACTUAL_COGS_AMOUNT) AS EXT_ACTUAL_COGS_AMOUNT
FROM ((((DW_FEI.INVOICE_LINE_FACT ILF
         INNER JOIN DW_FEI.PRODUCT_DIMENSION PROD
            ON (ILF.PRODUCT_GK = PROD.PRODUCT_GK))
        INNER JOIN PRICE_MGMT.PR_PRICE_CAT_HIST P_CAT
           ON     (P_CAT.INVOICE_NUMBER_GK =
                   ILF.INVOICE_NUMBER_GK)
              AND (P_CAT.PRODUCT_GK = ILF.PRODUCT_GK))
       INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
          ON (P_CAT.WAREHOUSE_NUMBER = SWD.WAREHOUSE_NUMBER_NK))
      INNER JOIN SALES_MART.TIME_PERIOD_DIMENSION TPD
         ON (P_CAT.YEARMONTH = TPD.YEARMONTH))
     INNER JOIN DW_FEI.INVOICE_HEADER_FACT IHF
        ON     (ILF.INVOICE_NUMBER_GK = IHF.INVOICE_NUMBER_GK)
           AND (ILF.YEARMONTH = IHF.YEARMONTH)
    LEFT OUTER JOIN USER_SHARED.BRANCH_REGIONAL_DC DC
       ON (SWD.WAREHOUSE_NUMBER_NK = DC.BRANCH_NO)
    LEFT OUTER JOIN (
          SELECT DISTINCT
                   WD.ACCOUNT_NUMBER_NK, WD.WAREHOUSE_NUMBER_NK, WD.WAREHOUSE_NAME, WAREHOUSE_GK
            FROM DW_FEI.INVOICE_HEADER_FACT IHF
                 LEFT OUTER JOIN DW_FEI.WAREHOUSE_DIMENSION WD
                    ON (IHF.SHIP_FROM_WAREHOUSE_GK = WD.WAREHOUSE_GK)) SHP_WHSE
        ON IHF.SHIP_TO_WAREHOUSE_GK = SHP_WHSE.WAREHOUSE_GK        
WHERE     (PROD.DISCOUNT_GROUP_NK = '9181')
      AND (TPD.FISCAL_YEAR_TO_DATE = 'YEAR TO DATE')
      --AND (SWD.WAREHOUSE_NUMBER_NK = '945')
GROUP BY ILF.YEARMONTH,
       SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       SWD.WAREHOUSE_NUM_NAME,
       PROD.ALT1_CODE,
       PROD.PRODUCT_NAME,
       IHF.INVOICE_NUMBER_NK,
       IHF.WRITER,       
       P_CAT.PRICE_CATEGORY_FINAL,
       DC.REGIONAL_DC,
       IHF.SHIP_FROM_WAREHOUSE_GK) X
 LEFT OUTER JOIN DW_FEI.WAREHOUSE_DIMENSION WD
  ON (X.SHIP_FROM_WAREHOUSE_GK = WD.WAREHOUSE_GK)
  ;