--------------------------------------------------------
--  File created - Thursday-October-03-2013   
--------------------------------------------------------
REM INSERTING into CUSTOMER_TYPES
SET DEFINE OFF;
Insert into CUSTOMER_TYPES (CUSTOMER_TYPE,C_TYPE_DESC,C_TYPE_GROUPING) values ('B_COMMER','COMMERCIAL CONSTRUCTION','ASSOCIATED CONTRACTOR');
Insert into CUSTOMER_TYPES (CUSTOMER_TYPE,C_TYPE_DESC,C_TYPE_GROUPING) values ('B_INDUS','INDUSTRIAL CONSTRUCTION','ASSOCIATED CONTRACTOR');
Insert into CUSTOMER_TYPES (CUSTOMER_TYPE,C_TYPE_DESC,C_TYPE_GROUPING) values ('C_CARPENTRY','CARPENTRY WORK (INCLUDING CABINETS}','ASSOCIATED CONTRACTOR');
Insert into CUSTOMER_TYPES (CUSTOMER_TYPE,C_TYPE_DESC,C_TYPE_GROUPING) values ('C_CONCRETE','CONCRETE WORK CONTRACTORS','ASSOCIATED CONTRACTOR');
Insert into CUSTOMER_TYPES (CUSTOMER_TYPE,C_TYPE_DESC,C_TYPE_GROUPING) values ('C_ELECTRIC','ELECTRICAL','ASSOCIATED CONTRACTOR');
Insert into CUSTOMER_TYPES (CUSTOMER_TYPE,C_TYPE_DESC,C_TYPE_GROUPING) values ('C_ENERGY','ENERGY MANAGEMENT CONTRACTORS','ASSOCIATED CONTRACTOR');
