DROP TABLE AAA6863.PRICE_COLUMN_DEFINITION;

CREATE TABLE AAA6863.PRICE_COLUMN_DEFINITION (
  "PRICE_COLUMN" INTEGER NOT NULL ENABLE,
	"PRICE_COLUMN" VARCHAR2 ( 10 CHAR ) NOT NULL ENABLE,
  "PC_SHORT_CAT" VARCHAR2 ( 15 CHAR )
);

INTEGER

INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('1', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('2', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('3', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('4', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('6', 'NW Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('7', 'NW Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('8', 'NW Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('9', 'NW Plbg');