DROP TABLE AAA6863.PRICE_COLUMN_DEFINITION;

CREATE TABLE AAA6863.PRICE_COLUMN_DEFINITION (
  "PRICE_COLUMN" INTEGER NOT NULL ENABLE,
	"PRICE_COLUMN" VARCHAR2 ( 10 CHAR ) NOT NULL ENABLE,
  "PC_SHORT_CAT" VARCHAR2 ( 15 CHAR )
);

INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('1', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('2', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('3', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('4', 'RR Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('6', 'NW Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('7', 'NW Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('8', 'NW Plbg');
INSERT INTO AAA6863.PRICE_COLUMN_DEFINITION VALUES ('9', 'NW Plbg');

GRANT SELECT ON AAA6863.PRICE_COLUMN_DEFINITION TO PUBLIC;

/* ############################################################# */

DROP TABLE AAA6863.DG_BY_KOB;

CREATE TABLE AAA6863.DG_BY_KOB (
	"DG_NK" INTEGER NOT NULL ENABLE,
	"CATEGORY" VARCHAR2 ( 25 CHAR ),
	"BG_HIERARCHY" VARCHAR2 ( 50 CHAR ),
	"HQ_HI_LEVEL" VARCHAR2 ( 25 CHAR ),
	"CMRO" VARCHAR2 ( 10 CHAR )
);

INSERT INTO AAA6863.DG_BY_KOB (DG_NK, CATEGORY, BG_HIERARCHY, HQ_HI_LEVEL, CMRO) VALUES ('1', 'M STL PIPE', 'COMMERCIAL / INDUSTRIAL', 'PVF ROUGH PRODUCTS', 'NDP');
INSERT INTO AAA6863.DG_BY_KOB (DG_NK, CATEGORY, BG_HIERARCHY, HQ_HI_LEVEL, CMRO) VALUES ('2', 'M STL PIPE', 'COMMERCIAL', 'PVF ROUGH PRODUCTS', '');
INSERT INTO AAA6863.DG_BY_KOB (DG_NK, CATEGORY, BG_HIERARCHY, HQ_HI_LEVEL, CMRO) VALUES ('3', 'M STL PIPE', 'COMMERCIAL / FIRE/FABRICATION', 'PVF ROUGH PRODUCTS', 'NDP');
INSERT INTO AAA6863.DG_BY_KOB (DG_NK, CATEGORY, BG_HIERARCHY, HQ_HI_LEVEL, CMRO) VALUES ('4', 'M STL PIPE', 'COMMERCIAL / FIRE/FABRICATION', 'PVF ROUGH PRODUCTS', 'NDP');
INSERT INTO AAA6863.DG_BY_KOB (DG_NK, CATEGORY, BG_HIERARCHY, HQ_HI_LEVEL, CMRO) VALUES ('5', 'M STL PIPE', 'COMMERCIAL / INDUSTRIAL', 'PVF ROUGH PRODUCTS', 'NDP');

GRANT SELECT ON AAA6863.DG_BY_KOB TO PUBLIC;


INSERT INTO AAA6863.MEGA_BRANCHES VALUES ('907', 'NASHVILLE', '20', 'NASH', '20', '47');

WHSE	NVARCHAR2(50)
REG_ACCT_NAME	NVARCHAR2(50)
REG_ACCT_NUM	NVARCHAR2(50)
NEW_ACCT_NAME	NVARCHAR2(50)
ACCT_NUM	NVARCHAR2(50)
PC	NVARCHAR2(50)