INSERT INTO PRICE_MGMT.PR_VICT2_CUST_R2MO
   SELECT SRC.*
   FROM PRICE_MGMT.PR_VICT2_SLS_CAT SRC
        LEFT OUTER JOIN PRICE_MGMT.PR_VICT2_CUST_R2MO DEST
           ON     (SRC.INVOICE_NUMBER_GK = DEST.INVOICE_NUMBER_GK)
              AND (SRC.INVOICE_LINE_NUMBER = DEST.INVOICE_LINE_NUMBER)
   WHERE (DEST.INVOICE_NUMBER_GK IS NULL AND DEST.INVOICE_LINE_NUMBER IS NULL);

COMMIT;

INSERT INTO PRICE_MGMT.PR_PRICE_CAT_HIST
   SELECT YEARMONTH,
          EOM_YEARMONTH,
          INVOICE_NUMBER_GK,
          INVOICE_LINE_NUMBER,
          PRODUCT_GK,
          SPECIAL_PRODUCT_GK,
          PROCESS_DATE,
          SHIPPED_QTY,
          EXT_SALES_AMOUNT,
          EXT_ACTUAL_COGS_AMOUNT,
          CORE_ADJ_AVG_COST,
          EXT_AVG_COGS_AMOUNT,
          INSERT_TIMESTAMP_IHF INSERT_TIMESTAMP,
          PRICE_CODE,
          GR_OVR PRICE_CATEGORY_OVR_PR,
          PR_OVR PRICE_CATEGORY_OVR_GR,
          PRICE_CATEGORY,
          ORIG_PRICE_CODE,
          PRICE_FORMULA,
          PRICE_CATEGORY_FINAL,
          WAREHOUSE_NUMBER,
          CUSTOMER_ACCOUNT_GK
   FROM PRICE_MGMT.PR_VICT2_SLS_CAT SRC
        LEFT OUTER JOIN PRICE_MGMT.PR_PRICE_CAT_HIST DEST
           ON     SRC.INVOICE_NUMBER_GK = DEST.INVOICE_NUMBER_GK
              AND SRC.INVOICE_LINE_NUMBER = DEST.INVOICE_LINE_NUMBER
   WHERE (DEST.INVOICE_NUMBER_GK IS NULL AND DEST.INVOICE_LINE_NUMBER IS NULL);

COMMIT;