SELECT PM_DATA.WRITER,
       PM_DATA.YEARMONTH,
       SUM ( PM_DATA.EXT_SALES_AMOUNT ) AS EX_SALES,
       SUM ( PM_DATA.EXT_AVG_COGS_AMOUNT ) AS EX_AC,
			 SUM (
			 	CASE 
					WHEN PM_DATA.PRICE_SUB_CATEGORY = 'SPECIAL' THEN
						PM_DATA.EXT_SALES_AMOUNT
					ELSE 0
				END )
					SP_SALES,
				SUM (
			 	CASE 
					WHEN PM_DATA.PRICE_SUB_CATEGORY = 'SPECIAL' THEN
						PM_DATA.EXT_AVG_COGS_AMOUNT
					ELSE 0
				END )
					SP_AC
  FROM     SALES_MART.PRICE_MGMT_DATA_DET PM_DATA
       INNER JOIN
           SALES_MART.TIME_PERIOD_DIMENSION TPD
       ON ( PM_DATA.YEARMONTH = TPD.YEARMONTH )
 WHERE ( TPD.ROLL12MONTHS = 'LAST TWELVE MONTHS' )
       AND ( PM_DATA.ACCOUNT_NUMBER_NK = '1020' )
			 AND (  PM_DATA.IC_FLAG = 'REGULAR' )
GROUP BY TPD.ROLL12MONTHS,
         PM_DATA.ACCOUNT_NUMBER_NK,
         PM_DATA.WRITER,
       	 PM_DATA.YEARMONTH
