SELECT IHF.ACCOUNT_NUMBER,
       IHF.YEARMONTH,
       INVOICE_LINE_FACT.DISCOUNT_GROUP_GK,
       IHF.CUSTOMER_NUMBER_NK,
       INVOICE_LINE_FACT.PRICE_CODE,
       IHF.CONTRACT_NUMBER,
       CUSTOMER_DIMENSION.SALESMAN_CODE
FROM (((DW_FEI.INVOICE_HEADER_FACT IHF
        INNER JOIN SALES_MART.TIME_PERIOD_DIMENSION TPD
           ON (IHF.YEARMONTH = TPD.YEARMONTH))
       INNER JOIN DW_FEI.INVOICE_LINE_FACT INVOICE_LINE_FACT
          ON (INVOICE_LINE_FACT.INVOICE_NUMBER_GK = IHF.INVOICE_NUMBER_GK))
      INNER JOIN
      DW_FEI.CUSTOMER_CONTRACT_DIMENSION CUSTOMER_CONTRACT_DIMENSION
         ON (CUSTOMER_CONTRACT_DIMENSION.CUSTOMER_NK = IHF.CUSTOMER_NUMBER_NK))
     INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUSTOMER_DIMENSION
        ON (CUSTOMER_CONTRACT_DIMENSION.CUSTOMER_GK =
            CUSTOMER_DIMENSION.CUSTOMER_GK)
WHERE     (IHF.ACCOUNT_NUMBER = '5')
      AND (TPD.ROLL12MONTHS = 'LAST TWELVE MONTHS')
      AND (INVOICE_LINE_FACT.PRICE_CODE = 'CB')
      AND (IHF.CONTRACT_NUMBER = 'GOODMANCB');