SELECT DISTINCT
       SWD.ACCOUNT_NUMBER_NK,
			 POHF.BRANCH_VENDOR_NK,
       BVD.VENDOR_NAME,
       POHF.PO_DATE_YEARMONTH,
       POHF.PO_NUMBER_NK,
       POHF.WAREHOUSE_NUMBER_NK,
       POLF.PO_DATE,
       POLF.RECEIPT_DATE,
       PROD.DISCOUNT_GROUP_NK,
       PROD.ALT1_CODE,
       PROD.PRODUCT_NK,
       PROD.PRODUCT_NAME,
       PROD.UNIT_OF_MEASURE,
       POLF.ORDERED_QTY,
       POLF.RECEIVED_QTY,
       POLF.UNIT_COST,
       POLF.EXT_LINE_COST,
       PROD.LINEBUY_NK
  FROM   (  (  (  (  DW_FEI.PO_LINE_FACT POLF
                   INNER JOIN
                     DW_FEI.PRODUCT_DIMENSION PROD
                   ON ( POLF.PRODUCT_GK = PROD.PRODUCT_GK ))
                INNER JOIN
                  DW_FEI.PO_HEADER_FACT POHF
                ON ( POLF.PO_GK = POHF.PO_GK ))
             INNER JOIN
               DW_FEI.BRANCH_VENDOR_DIMENSION BVD
             ON ( POHF.BRANCH_VENDOR_GK = BVD.VENDOR_GK ))
          INNER JOIN
            SALES_MART.TIME_PERIOD_DIMENSION TPD
          ON ( POHF.PO_DATE_YEARMONTH = TPD.YEARMONTH ))
       INNER JOIN
         SALES_MART.SALES_WAREHOUSE_DIM SWD
       ON ( SWD.WAREHOUSE_NUMBER_NK = POHF.WAREHOUSE_NUMBER_NK )
 WHERE ( TPD.ROLL12MONTHS = 'LAST TWELVE MONTHS' )
       AND ( SWD.ACCOUNT_NUMBER_NK = '2000' )
			 AND PROD.DISCOUNT_GROUP_NK IN (  '2013',
																															'2014',
																															'2016',
																															'2017',
																															'2018',
																															'2019',
																															'2020',
																															'2021',
																															'2028',
																															'2205',
																															'2216',
																															'2224',
																															'2226',
																															'2228',
																															'2229',
																															'2230',
																															'2231',
																															'2232',
																															'2233',
																															'2234',
																															'2235',
																															'2236',
																															'2237',
																															'2238',
																															'2239',
																															'2240',
																															'2241',
																															'2242',
																															'2243',
																															'2244',
																															'2245',
																															'2246',
																															'2247',
																															'2248',
																															'2249',
																															'2250',
																															'2251',
																															'2252',
																															'2253',
																															'2254',
																															'2255',
																															'2256',
																															'2257',
																															'2258',
																															'2259',
																															'2260',
																															'2261',
																															'2262',
																															'2263',
																															'2264',
																															'2265',
																															'2266',
																															'2267',
																															'2269',
																															'2270',
																															'2271',
																															'2272',
																															'2273',
																															'2274',
																															'2275',
																															'2276',
																															'2277',
																															'2278',
																															'2279',
																															'2281',
																															'2282',
																															'2283',
																															'2284',
																															'2285',
																															'2289',
																															'2290',
																															'2291',
																															'2298',
																															'2300',
																															'2301',
																															'2303',
																															'2326',
																															'3823',
																															'5031',
																															'8031',
																															'8037',
																															'8699',
																															'8700',
																															'8701',
																															'8702',
																															'8703',
																															'8704',
																															'8705',
																															'8706',
																															'8707',
																															'8709',
																															'8710',
																															'8711',
																															'8712',
																															'8713',
																															'8714',
																															'8715',
																															'8716',
																															'8717',
																															'8718',
																															'8719',
																															'8720',
																															'8721',
																															'8722',
																															'8723',
																															'8725',
																															'8726',
																															'8727',
																															'8728',
																															'8729',
																															'8755',
																															'8756',
																															'8766',
																															'8772',
																															'9129'
																															)