SELECT DISTINCT
       SWD.ACCOUNT_NUMBER_NK AS ACCT_NK,
       SWD.ACCOUNT_NAME,
       POHF.EMPLOYEE_PSOFT_NK AS P_SOFT_NK,
       POHF.EMPLOYEE_TRILOGIE_NK AS TRILOGY_NK,
       EMPL.ASSOC_NAME,
       EMPL.INITIALS,
       SWD.WAREHOUSE_NUMBER_NK AS WHSE_NK,
       POHF.PO_DATE_YEARMONTH AS YYYYMM,
       POHF.PO_DATE,
       POHF.PO_NUMBER_NK,
       POHF.CHECKOUT_DATE AS CHECKOUT,
       POHF.INTERBRANCH_WHSE_NK,
       POHF.ORD_EXTENDED_DOLLARS AS EX_DOLLARS,
       POHF.SPC_YN,
       POHF.LPU_YN
  FROM    (   (   DW_FEI.PO_HEADER_FACT POHF
               INNER JOIN
                  DW_FEI.PO_LINE_FACT POLF
               ON (POHF.PO_GK = POLF.PO_GK))
           INNER JOIN
              SALES_MART.SALES_WAREHOUSE_DIM SWD
           ON (SWD.WAREHOUSE_NUMBER_NK = POHF.WAREHOUSE_NUMBER_NK))
       INNER JOIN
          DW_FEI.EMPLOYEE_DIMENSION EMPL
       ON (EMPL.EMPLOYEE_TRILOGIE_NK = POHF.EMPLOYEE_TRILOGIE_NK)
 WHERE     (SWD.ACCOUNT_NUMBER_NK = '1480')
       AND (POHF.PO_DATE_YEARMONTH BETWEEN 201601 AND 201612)
       AND (POHF.DELETE_DATE IS NULL)
;