
SELECT *

 FROM (

    SELECT 
       PM_DET.DISCOUNT_GROUP_NK_NAME,
       PM_DET.ALT1_CODE_AND_PRODUCT_NAME,
       --PM_DET.CHANNEL_TYPE,
       --PM_DET.PRICE_CATEGORY,
       SUM (PM_DET.SHIPPED_QTY),
       SUM (PM_DET.EXT_SALES_AMOUNT) AS EX_SALES,
       SUM (PM_DET.EXT_AVG_COGS_AMOUNT) AS EX_AC
  FROM    EBUSINESS.SALES_DIVISIONS SWD
       INNER JOIN
          SALES_MART.PRICE_MGMT_DATA_DET PM_DET
       ON (SWD.ACCOUNT_NUMBER_NK = PM_DET.ACCOUNT_NUMBER_NK)
 WHERE (PM_DET.YEARMONTH = 201509) AND (PM_DET.IC_FLAG = 'REGULAR')
 	AND ( SUBSTR ( SWD.REGION_NAME, 1 ,3 ) IN ( 
			 	 'D10', 'D11', 'D12', 'D13', 
				 'D14', 'D30', 'D31', 'D32', 
				 'D50', 'D51', 'D53'
				 ))
GROUP BY PM_DET.DISCOUNT_GROUP_NK_NAME,
       PM_DET.ALT1_CODE_AND_PRODUCT_NAME
       --PM_DET.CHANNEL_TYPE,
       --PM_DET.PRICE_CATEGORY
			 
ORDER BY SUM (PM_DET.EXT_SALES_AMOUNT) DESC
    )PROD_SALES
		
 WHERE ROWNUM <= 50

ORDER BY ROWNUM;