/*
    Use for both FYTD and YOY tables
    jb 
*/
SELECT 
       PR_CORE_YTD.REGION,
			 PR_CORE_YTD.DISTRICT,
       PR_CORE_YTD.ACCOUNT_NAME,
       --PR_CORE_YTD.YEARMONTH,
       PR_CORE_YTD.TITLE_DESC,
       PR_CORE_YTD.SALESREP_NK REP_CODE,
       PR_CORE_YTD.SALESREP_NAME,
       --HIER.BUSCAT2,
       NVL (HIER.HILEV, 'SP-') HILEV,
       HIER.DET1,
       --HIER.DET2,
      -- NVL (PR_CORE_YTD.DISCOUNT_GROUP_NK, 'SP-') AS DISC_GRP,
      -- HIER.DESCRIPTION,
       SUM (PR_CORE_YTD.LINES) LINES,
       SUM (PR_CORE_YTD.AVG_COGS) AVG_COGS,
       SUM (PR_CORE_YTD.INVOICE_COGS) INVOICE_COGS,
       SUM (PR_CORE_YTD.SALES) SALES,
       SUM (PR_CORE_YTD.CORE_COST_SUBTOTAL) CORE_COST_SUBTOTAL,
       SUM (PR_CORE_YTD.CORE_ADJ_AVG_COGS) CORE_ADJ_AVG_COGS,
			 PR_CORE_YTD.TPD
       
  FROM AAA6863.PR_CORE_YOY PR_CORE_YTD
       LEFT OUTER JOIN USER_SHARED.BUSGRP_PROD_HIERARCHY HIER
          ON (PR_CORE_YTD.DISCOUNT_GROUP_NK = HIER.DISCOUNT_GROUP_NK)
	-- WHERE PR_CORE_YTD.ACCOUNT_NAME = 'LAKEWOOD'
GROUP BY PR_CORE_YTD.TPD,
       PR_CORE_YTD.REGION,
       PR_CORE_YTD.DISTRICT,
       PR_CORE_YTD.ACCOUNT_NAME,
       --PR_CORE_YTD.YEARMONTH,
       PR_CORE_YTD.TITLE_DESC,
       PR_CORE_YTD.SALESREP_NK,
       PR_CORE_YTD.SALESREP_NAME,
       --HIER.BUSCAT2,
       NVL (HIER.HILEV, 'SP-'),
       HIER.DET1,
         --HIER.DET2,
         --PR_CORE_YTD.DISCOUNT_GROUP_NK,
         --HIER.DESCRIPTION
			 PR_CORE_YTD.TPD,
       PR_CORE_YTD.REGION
	;
	
	--remove region
	