DROP TABLE PRICE_MGMT.PR_CORE_COST_ADJ_YOY;

CREATE TABLE PRICE_MGMT.PR_CORE_COST_ADJ_YOY
AS
SELECT PR_CORE_YTD.REGION,
       PR_CORE_YTD.DISTRICT,
       PR_CORE_YTD.ACCOUNT_NAME,
       PR_CORE_YTD.TPD,
       CASE
          WHEN HOUSE_FLAG = 'O/S' THEN PR_CORE_YTD.TITLE_DESC
          WHEN HOUSE_FLAG = 'H/A' THEN 'Other Salesrep'
          ELSE 'Unassigned'
       END
          TITLE_ROLLUP,
       PR_CORE_YTD.TITLE_DESC,
       CASE
          WHEN HOUSE_FLAG IN ('O/S', 'H/A') THEN PR_CORE_YTD.SALESREP_NK
          ELSE 'HOUSE'
       END
          REP_CODE,
       CASE
          WHEN HOUSE_FLAG IN ('O/S', 'H/A') THEN PR_CORE_YTD.SALESREP_NAME
          ELSE 'HOUSE UNASSIGNED'
       END
          SALESREP_NAME,
       NVL (HIER.HILEV, 'SP-')
          HILEV,
       HIER.DET1,
       HIER.FAB5_CAT,
       CASE WHEN CORE_VDR.DET6 IS NOT NULL THEN HIER.DET6 ELSE 'CORE N/A' END
          AS VENDOR,
       SUM (PR_CORE_YTD.LINES)
          LINES,
       SUM (PR_CORE_YTD.AVG_COGS)
          AVG_COGS,
       SUM (PR_CORE_YTD.INVOICE_COGS)
          INVOICE_COGS,
       SUM (PR_CORE_YTD.SALES)
          SALES,
       SUM (PR_CORE_YTD.CORE_ADJ_AVG_COGS)
          CORE_ADJ_AVG_COGS,
       SUM (PR_CORE_YTD.AVG_COGS - PR_CORE_YTD.CORE_ADJ_AVG_COGS)
          EXT_CLAIM_AMOUNT,
       SUM (PR_CORE_YTD.COST_ONLY_ADJ) 
          COST_ONLY_ADJ,
       SUM (PR_CORE_YTD.AVG_COGS - PR_CORE_YTD.CORE_ADJ_AVG_COGS)
          CORE_COST_DELTA
FROM PRICE_MGMT.PR_CORE_YOY_NEW PR_CORE_YTD
     LEFT OUTER JOIN USER_SHARED.BUSGRP_PROD_HIERARCHY HIER
        ON (PR_CORE_YTD.DISCOUNT_GROUP_NK = HIER.DISCOUNT_GROUP_NK)
     LEFT OUTER JOIN SALES_MART.TIME_PERIOD_DIMENSION TPD
        ON PR_CORE_YTD.YEARMONTH = TPD.YEARMONTH
     LEFT OUTER JOIN
     (SELECT H.DET6
      FROM PRICE_MGMT.PR_CORE_YOY_NEW X
           INNER JOIN USER_SHARED.BUSGRP_PROD_HIERARCHY H
              ON X.DISCOUNT_GROUP_NK = H.DISCOUNT_GROUP_NK
      WHERE AVG_COGS - CORE_ADJ_AVG_COGS + COST_ONLY_ADJ <> 0
      GROUP BY H.DET6) CORE_VDR
        ON (HIER.DET6 = CORE_VDR.DET6)

GROUP BY PR_CORE_YTD.TPD,
         PR_CORE_YTD.REGION,
         PR_CORE_YTD.DISTRICT,
         PR_CORE_YTD.ACCOUNT_NAME,
         PR_CORE_YTD.TITLE_DESC,
         CASE
            WHEN HOUSE_FLAG = 'O/S' THEN PR_CORE_YTD.TITLE_DESC
            WHEN HOUSE_FLAG = 'H/A' THEN 'Other Salesrep'
            ELSE 'Unassigned'
         END,
         CASE
            WHEN HOUSE_FLAG IN ('O/S', 'H/A') THEN PR_CORE_YTD.SALESREP_NK
            ELSE 'HOUSE'
         END,
         CASE
            WHEN HOUSE_FLAG IN ('O/S', 'H/A') THEN PR_CORE_YTD.SALESREP_NAME
            ELSE 'HOUSE UNASSIGNED'
         END,
         NVL (HIER.HILEV, 'SP-'),
         HIER.DET1,
         HIER.FAB5_CAT,
         CASE
            WHEN CORE_VDR.DET6 IS NOT NULL THEN HIER.DET6
            ELSE 'CORE N/A'
         END;