/*
	andrew's post merge main cust number
*/

SELECT SMART.ACCOUNT_NUMBER_NK AS "MAIN BRANCH",
       SMART.SELL_DISTRICT AS "DISTRICT",
			 
       CUST.MAIN_CUSTOMER_NK AS "MAIN CUST ID",
       SMART.CUSTOMER_NAME AS "CUST NAME",
       -- SMART.DISCOUNT_GROUP_NK DG,
       -- SMART.DISCOUNT_GROUP_NK_NAME DG_DESC,
			 -- SMART.ALT1_CODE_AND_PRODUCT_NAME ITEM,
			 SMART.PRICE_CATEGORY PR_CAT,
       SUM ( SMART.EXT_SALES_AMOUNT ) AS "EXT SALES",
       SUM ( SMART.EXT_AVG_COGS_AMOUNT ) AS "EXT COGS"
			 
  FROM   DW_FEI.CUSTOMER_DIMENSION CUST
       RIGHT JOIN
         SALES_MART.PRICE_MGMT_DATA_DET SMART
       ON SMART.ACTIVE_CUSTOMER_GK = CUST.CUSTOMER_GK
 WHERE SMART.YEARMONTH BETWEEN '201404' AND '201411'
       -- AND SMART.SELL_DISTRICT = 'D32 SC BLENDED SOUTHERN PLAINS'
       -- AND SMART.ACCOUNT_NUMBER_NK = '1480' 
			 AND SMART.IC_FLAG = 'REGULAR'
			 --AND SMART.MAIN_CUSTOMER_NK IN ( '108964', '31732' )
			 AND SMART.SELL_WAREHOUSE_NUMBER_NK IN (  '102', '142', '144',
			 																					'915', '916', '5866' )
GROUP BY SMART.ACCOUNT_NUMBER_NK,
         SMART.SELL_DISTRICT,
         CUST.MAIN_CUSTOMER_NK,
         SMART.CUSTOMER_NAME,
         SMART.CUSTOMER_NK,
         SMART.MAIN_CUSTOMER_NK,
         SMART.ACTIVE_ACCOUNT_NUMBER_NK,
         SMART.PRICE_CATEGORY,
         -- SMART.DISCOUNT_GROUP_NK,
         -- SMART.DISCOUNT_GROUP_NK_NAME,
				 -- SMART.ALT1_CODE_AND_PRODUCT_NAME,
				 SMART.PRICE_CATEGORY
				 ;