SELECT DISTINCT
       SWD.ACCOUNT_NUMBER_NK,
       PM_DET.DISCOUNT_GROUP_NK,
       SUM (PM_DET.EXT_SALES_AMOUNT) EXT_SALES,
       SUM (PM_DET.EXT_AVG_COGS_AMOUNT) EXT_AC
  FROM    (   SALES_MART.PRICE_MGMT_DATA_DET PM_DET
           INNER JOIN
              EBUSINESS.SALES_DIVISIONS SWD
           ON (PM_DET.ACCOUNT_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK))
       INNER JOIN
          SALES_MART.TIME_PERIOD_DIMENSION TPD
       ON (TPD.YEARMONTH = PM_DET.YEARMONTH)
 WHERE (SWD.ACCOUNT_NUMBER_NK = '520')
       AND (TPD.ROLL12MONTHS = 'LAST TWELVE MONTHS')
       AND (SUBSTR (SWD.REGION_NAME, 1, 3) IN
                  ('D10', 'D11', 'D12', 'D13', 'D14', 'D30', 'D31', 'D32'))
GROUP BY SWD.ACCOUNT_NUMBER_NK, PM_DET.DISCOUNT_GROUP_NK

-- 3.34.97 min/sec
;