/* 
	sales by customer with channel sales broken out 
	horizontal view
*/
SELECT
	TPD.ROLL12MONTHS TPD,
	x.OLD_ACCOUNT_NUMBER_NK,
	X.ACCOUNT_NUMBER_NK BRANCH,
	NVL ( X.SELL_ALIAS_NAME, NULL ) LOGON_NAME, 
	X.SELL_WAREHOUSE_NUMBER_NK,
	X.CUSTOMER_NK CUST_NO,
	X.CUSTOMER_NAME,
	--X.CUSTOMER_TYPE C_TYPE,
	--X.PRICE_COLUMN PC,
	X.MAIN_CUSTOMER_NK MAIN_NO,
	X.MAIN_CUSTOMER_NAME,
	X.ACTIVE_CUSTOMER_NK,
	X.CHANNEL_TYPE,
	X.SALES_TYPE,
	X.PRICE_CATEGORY,
	--X.CHANNEL_TYPE CHANNEL,
	SUM ( X.EXT_SALES_AMOUNT ) SALES,
	SUM ( X.EXT_AVG_COGS_AMOUNT ) AVG_COST,
	
  ROUND (
    (SUM ( X.EXT_SALES_AMOUNT ) - SUM ( X.EXT_AVG_COGS_AMOUNT ))
		/ CASE
        WHEN SUM ( X.EXT_SALES_AMOUNT ) > 0
        THEN SUM ( X.EXT_SALES_AMOUNT )
        ELSE
          1
      END
        , 3 )
     "GP %",
     
	-- MATRIX SALES
	SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'MATRIX'
			THEN 
				( X.EXT_SALES_AMOUNT )
			ELSE
				0
		END )
			MTX_SALES,
	SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'MATRIX'
			THEN 
				( X.EXT_AVG_COGS_AMOUNT )
			ELSE
				0
		END )
			MTX_AC,
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'MATRIX'
				THEN
					( X.EXT_SALES_AMOUNT - X.EXT_AVG_COGS_AMOUNT )
				ELSE
					0
			END)
	/ SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'MATRIX'
			THEN
			CASE
				WHEN X.EXT_SALES_AMOUNT > 0
				THEN
					(X.EXT_SALES_AMOUNT)
				ELSE
					1
			END
			ELSE
				1
		END),
		3 )
			"MTX GP%",
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'MATRIX'
				THEN
					(X.EXT_SALES_AMOUNT)
				ELSE
				0
			END)
		/ SUM (
			CASE
				WHEN X.EXT_SALES_AMOUNT > 0
				THEN
					X.EXT_SALES_AMOUNT
				ELSE
					1
			END),
			3)
				"PM Use%$",
	-- CCOR SALES
	SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'OVERRIDE'
			THEN 
				( X.EXT_SALES_AMOUNT )
			ELSE
			0
		END )
			CCOR_SALES,
	SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'OVERRIDE'
			THEN 
				( X.EXT_AVG_COGS_AMOUNT )
			ELSE
			0
		END )
			CCOR_AC,
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'OVERRIDE'
				THEN
					( X.EXT_SALES_AMOUNT - X.EXT_AVG_COGS_AMOUNT )
				ELSE
					0
			END)
		/ SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'OVERRIDE'
				THEN
					CASE
						WHEN X.EXT_SALES_AMOUNT > 0
						THEN
							(X.EXT_SALES_AMOUNT)
						ELSE
							1
					END
				ELSE
					1
				END),
			3)
				"MAN GP%",
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'OVERRIDE'
				THEN
					(X.EXT_SALES_AMOUNT)
				ELSE
					0
			END)
			/ SUM (
				CASE
					WHEN X.EXT_SALES_AMOUNT > 0
					THEN
						X.EXT_SALES_AMOUNT
					ELSE
						1
				END),
			3)
				"Ovr Use%$",
		
	-- MANUAL SALES
	SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'MANUAL'
			THEN 
				( X.EXT_SALES_AMOUNT )
			ELSE
				0
		END )
			CCOR_SALES,
		SUM (
			CASE
			WHEN X.PRICE_CATEGORY IN 'MANUAL'
			THEN 
				( X.EXT_AVG_COGS_AMOUNT )
			ELSE
				0
		END )
			MAN_AC,
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'MANUAL'
				THEN
					( X.EXT_SALES_AMOUNT - X.EXT_AVG_COGS_AMOUNT )
				ELSE
					0
			END)
		/ SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'MANUAL'
				THEN
					CASE
						WHEN X.EXT_SALES_AMOUNT > 0
						THEN
							(X.EXT_SALES_AMOUNT)
						ELSE
							1
					END
				ELSE
					1
			END),
		3)
			"MAN GP%",
	ROUND (
		SUM (
			CASE
			WHEN X.PRICE_CATEGORY IN 'MANUAL'
			THEN
				(X.EXT_SALES_AMOUNT)
			ELSE
				0
		END)
		/ SUM (
			CASE
			WHEN X.EXT_SALES_AMOUNT > 0
			THEN
				X.EXT_SALES_AMOUNT
			ELSE
				1
		END),
		3)
			"Man Use%$",
			
	-- SPECIAL SALES
	SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'SPECIAL'
			THEN 
				( X.EXT_SALES_AMOUNT )
			ELSE
				0
		END )
			"SP- SALES",
		SUM (
			CASE
			WHEN X.PRICE_CATEGORY IN 'SPECIAL'
			THEN 
				( X.EXT_AVG_COGS_AMOUNT )
			ELSE
				0
		END )
			"SP- AC",
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'SPECIAL'
				THEN
					( X.EXT_SALES_AMOUNT - X.EXT_AVG_COGS_AMOUNT )
				ELSE
					0
			END)
		/ SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'SPECIAL'
				THEN
					CASE
					WHEN X.EXT_SALES_AMOUNT > 0
					THEN
						(X.EXT_SALES_AMOUNT)
					ELSE
						1
					END
				ELSE
					1
			END),
		3)
		"SP- GP%",
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'SPECIAL'
				THEN
					(X.EXT_SALES_AMOUNT)
				ELSE
					0
			END)
		/ SUM (
			CASE
				WHEN X.EXT_SALES_AMOUNT > 0
				THEN
					X.EXT_SALES_AMOUNT
				ELSE
					1
			END ),
		3 )
		"SP- Use%$",
		
	-- CREDIT SALES
	SUM (
		CASE
			WHEN X.PRICE_CATEGORY IN 'CREDITS'
			THEN 
				( X.EXT_SALES_AMOUNT )
			ELSE
				0
		END )
			CREDITS_SALES,
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'CREDITS'
				THEN 
					( X.EXT_AVG_COGS_AMOUNT )
				ELSE
					0
			END )
				CREDITS_AC,
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'CREDITS'
				THEN
					( X.EXT_SALES_AMOUNT - X.EXT_AVG_COGS_AMOUNT )
				ELSE
					0
			END)
		/ SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'CREDITS'
				THEN
				CASE
					WHEN X.EXT_SALES_AMOUNT > 0
					THEN
						(X.EXT_SALES_AMOUNT)
					ELSE
						1
				END
				ELSE
					1
			END),
		3)
			"CR GP%",
	ROUND (
		SUM (
			CASE
				WHEN X.PRICE_CATEGORY IN 'CREDITS'
				THEN
					(X.EXT_SALES_AMOUNT)
				ELSE
					0
			END)
			/ SUM (
				CASE
					WHEN X.EXT_SALES_AMOUNT > 0
					THEN
						X.EXT_SALES_AMOUNT
					ELSE
						1
				END),
			3)
			"CR Use%$"
		
FROM SALES_MART.PRICE_MGMT_DATA_SUMM X
	LEFT OUTER JOIN SALES_MART.TIME_PERIOD_DIMENSION TPD
		ON ( X.YEARMONTH = TPD.YEARMONTH ) 
WHERE X.ACCOUNT_NUMBER_NK = '20'  -- IN ( '20', '13', '26', '56', '93', '185', '100', '150', '1717' )
	AND X.IC_FLAG = 'REGULAR'
	/*AND X.SELL_WAREHOUSE_NUMBER_NK IN ('740',
																														'1121',
																														'1123',
																														'1124',
																														'1177',
																														'1550',
																														'1551',
																														'1643',
																														'1645',
																														'2431'
																														)*/
	-- AND X.YEARMONTH BETWEEN  '201410' AND  '201609'
	AND TPD.ROLL12MONTHS IS NOT NULL
	-- AND X.PRICE_CATEGORY
	-- AND X.PRICE_SUB_CATEGORY
	-- AND X.CHANNEL_TYPE
	-- AND X.SALES_TYPE

GROUP BY 
	TPD.ROLL12MONTHS,
	x.OLD_ACCOUNT_NUMBER_NK,
	X.ACCOUNT_NUMBER_NK,
	NVL ( X.SELL_ALIAS_NAME, NULL ), 
	X.SELL_WAREHOUSE_NUMBER_NK,
	X.CUSTOMER_NK,
	X.CUSTOMER_NAME,
	--X.CUSTOMER_TYPE C_TYPE,
	--X.PRICE_COLUMN PC,
	X.CHANNEL_TYPE,
	X.SALES_TYPE,
	X.PRICE_CATEGORY,
	X.MAIN_CUSTOMER_NK,
	X.MAIN_CUSTOMER_NAME,
	X.ACTIVE_CUSTOMER_NK
  
ORDER BY X.ACCOUNT_NUMBER_NK ASC,
	X.MAIN_CUSTOMER_NK ASC,
  X.CUSTOMER_NAME
;
