SELECT TPD.ROLL12MONTHS,
       SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       SWD.ACCOUNT_NUMBER_NK,
       SWD.ACCOUNT_NAME,
       PM_DET.OLD_ACCOUNT_NUMBER_NK,
       PM_DET.CUSTOMER_NK,
       PM_DET.MAIN_CUSTOMER_NK,
       PM_DET.CUSTOMER_NAME,
       PM_DET.ACTIVE_CUSTOMER_NK,
       PM_DET.PRICE_CATEGORY,
       SUM (PM_DET.EXT_SALES_AMOUNT),
       SUM (PM_DET.EXT_AVG_COGS_AMOUNT)
  FROM    (   (   SALES_MART.PRICE_MGMT_DATA_DET PM_DET
               INNER JOIN
                  DW_FEI.CUSTOMER_DIMENSION CUST_DIM
               ON (PM_DET.CUSTOMER_GK = CUST_DIM.CUSTOMER_GK))
           INNER JOIN
              SALES_MART.TIME_PERIOD_DIMENSION TPD
           ON (TPD.YEARMONTH = PM_DET.YEARMONTH))
       INNER JOIN
          SALES_MART.SALES_WAREHOUSE_DIM SWD
       ON (PM_DET.SELL_WAREHOUSE_NUMBER_NK = SWD.WAREHOUSE_NUMBER_NK)
 WHERE (TPD.ROLL12MONTHS IS NOT NULL)
       AND (SWD.ACCOUNT_NUMBER_NK IN
                  ('61', '116', '190', '454', '480', '1869'))
GROUP BY SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         SWD.ACCOUNT_NAME,
         PM_DET.OLD_ACCOUNT_NUMBER_NK,
         PM_DET.CUSTOMER_NK,
         PM_DET.MAIN_CUSTOMER_NK,
         PM_DET.ACTIVE_CUSTOMER_NK,
         TPD.ROLL12MONTHS,
         PM_DET.CUSTOMER_NAME,
         PM_DET.PRICE_CATEGORY