SELECT DISTINCT VENDOR.ALPHA,
                VENDOR.ALPHA_TYPE,
                VENDOR.MASTER_VENDOR_NK,
                VENDOR.MASTER_VENDOR_NAME,
                DG_DIM.DISCOUNT_GROUP_NK,
                DG_DIM.DISCOUNT_GROUP_NAME,
                LB_DIM.LINEBUY_NK,
                LB_DIM.LINEBUY_NAME
FROM ((DW_FEI.PRODUCT_DIMENSION PROD
       INNER JOIN DW_FEI.DISCOUNT_GROUP_DIMENSION DG_DIM
          ON (PROD.DISCOUNT_GROUP_GK = DG_DIM.DISCOUNT_GROUP_GK))
      INNER JOIN DW_FEI.MASTER_VENDOR_DIMENSION VENDOR
         ON (VENDOR.MASTER_VENDOR_NK = PROD.MANUFACTURER))
     INNER JOIN DW_FEI.LINE_BUY_DIMENSION LB_DIM
        ON (LB_DIM.LINEBUY_NK = PROD.LINEBUY_NK)
WHERE     (DG_DIM.DISCOUNT_GROUP_NAME NOT LIKE 'DEAD%')
      AND (LB_DIM.LINEBUY_NAME NOT LIKE 'DEAD%')
      AND (LB_DIM.LINEBUY_NAME NOT LIKE 'PRODUCT FILE CLEAN-UP%')
      AND (VENDOR.DELETE_DATE IS NULL)
ORDER BY VENDOR.ALPHA ASC,
         DG_DIM.DISCOUNT_GROUP_NK ASC,
         LB_DIM.LINEBUY_NK ASC;