--CREATE TABLE AAA6863.PRICING_STATS_BLENDED
--AS
SELECT
	DPRO.DISTRICT DIST,
	DPRO.ACCOUNT_NUMBER_NK BR_NO,
	DPRO.BRANCH_NAME,
	DPRO.DISCOUNT_GROUP_NK DG_NO,
	DPRO.DISCOUNT_GROUP_NAME DG_NAME,
	DPRO.PRICE_COLUMN NAT_PC,
	COUNT ( DPRO.DISCOUNT_GROUP_NK ) STOCK_COUNT,
	--COUNT ( DPRO2.DISCOUNT_GROUP_NK ) TOTAL_COUNT,
	--OHB.ON_HAND,
	CONTRACTS.CCOR_COUNT,
	MATRIX.PC_COUNT

FROM (
	SELECT 
				PC.PRICE_COLUMN,
				BC.DISTRICT,
				BC.BRANCH_NAME,
        WPF.PRODUCT_GK,
        WHSE.ACCOUNT_NUMBER_NK,
        PROD.DISCOUNT_GROUP_NK,
				DG.DISCOUNT_GROUP_NAME
				
      FROM 
        DW_FEI.WAREHOUSE_PRODUCT_FACT WPF,
        DW_FEI.WAREHOUSE_DIMENSION WHSE,
        DW_FEI.PRODUCT_DIMENSION PROD,
        DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG,
        AAF1046.BRANCH_CONTACTS BC,
        AAA6863.NAT_BU_PRICE_COLUMNS PC,
				DW_FEI.DISCOUNT_GROUP_DIMENSION DG
      
      WHERE WPF.WAREHOUSE_GK     		= WHSE.WAREHOUSE_GK(+)
        AND WPF.PRODUCT_GK         	= PROD.PRODUCT_GK(+)
				AND DG.DISCOUNT_GROUP_GK		= BDG.DISCOUNT_GROUP_GK
        AND PROD.DISCOUNT_GROUP_GK 	= BDG.DISCOUNT_GROUP_GK
        AND WHSE.ACCOUNT_NUMBER_NK 	= BC.ACCOUNT_NK
        AND WHSE.ACCOUNT_NUMBER_NK 	= BDG.ACCOUNT_NUMBER_NK
        AND PC.BRANCH_NUMBER_NK     = BC.ACCOUNT_NK
        AND BC.DISTRICT            IN ( 'C10', 'C11', 'C12', 'C14', 'C30', 'C31', 'C32' )
        AND NVL (WPF.STATUS_TYPE, 'STOCK') IN
                ('STOCK', 'NN', 'NV', 'S', 'NQ')
        --AND PROD.DISCOUNT_GROUP_NK 	= '0545'
        --AND WHSE.ACCOUNT_NAME      IN ('KC')
        AND (WPF.YEARMONTH =
              (SELECT MAX (WPF.YEARMONTH)
                  FROM DW_FEI.WAREHOUSE_PRODUCT_FACT WPF
                  WHERE WPF.YEARMONTH BETWEEN TO_CHAR (
                              TRUNC (
                                 SYSDATE - 
                                  NUMTOYMINTERVAL (3, 'MONTH'),
                                 'MONTH'),
                              'YYYYMM')
                               AND TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')))
															) DPRO
	/* JOIN 1 */
			
			LEFT JOIN ( 
							SELECT DISTINCT 
                CCOR.BRANCH_NUMBER_NK,
                CCOR.DISC_GROUP,
                COUNT ( CCOR.DISC_GROUP ) CCOR_COUNT
              FROM DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCOR
              WHERE CCOR.DELETE_DATE          IS NULL
                AND CCOR.EXPIRE_DATE          IS NULL OR CCOR.EXPIRE_DATE > SYSDATE
								--AND CCOR.DISC_GROUP = '0545'
              GROUP BY 	CCOR.BRANCH_NUMBER_NK, 
												CCOR.DISC_GROUP
              ) CONTRACTS
							
         ON CONTRACTS.BRANCH_NUMBER_NK  = DPRO.ACCOUNT_NUMBER_NK
          AND CONTRACTS.DISC_GROUP      = DPRO.DISCOUNT_GROUP_NK
	
	/* JOIN 2 */
	
			LEFT JOIN ( 
							SELECT DISTINCT 
								PRICE.BRANCH_NUMBER_NK,
                PRICE.DISC_GROUP,
                COUNT ( PRICE.PRICE_COLUMN ) PC_COUNT
                
              FROM DW_FEI.PRICE_DIMENSION PRICE
              WHERE PRICE.DELETE_DATE       IS NULL 
                AND PRICE.PRICE_TYPE         = 'G'
								--AND PRICE.DISC_GROUP = '0545'
              GROUP BY PRICE.BRANCH_NUMBER_NK,
                PRICE.DISC_GROUP
              ) MATRIX
							
          ON MATRIX.BRANCH_NUMBER_NK = DPRO.ACCOUNT_NUMBER_NK
            AND MATRIX.DISC_GROUP = DPRO.DISCOUNT_GROUP_NK
						
	/* JOIN 3 */
	


	GROUP BY 	
			DPRO.DISTRICT,
			DPRO.ACCOUNT_NUMBER_NK,
			DPRO.BRANCH_NAME,
			DPRO.DISCOUNT_GROUP_NK,
			DPRO.DISCOUNT_GROUP_NAME,
			DPRO.PRICE_COLUMN,
			--COUNT ( DPRO.DISCOUNT_GROUP_NK ) STOCK_COUNT,
			--COUNT ( DPRO2.DISCOUNT_GROUP_NK ) TOTAL_COUNT,
			--OHB.ON_HAND,
			CONTRACTS.CCOR_COUNT,
			MATRIX.PC_COUNT
	ORDER BY
			DPRO.DISTRICT,
			DPRO.ACCOUNT_NUMBER_NK,
			DPRO.DISCOUNT_GROUP_NK
	;
	
	-- GRANT SELECT ON AAA6863.PRICING_STATS_BLENDED TO PUBLIC;