SELECT
  DPRO.DISTRICT,
  DPRO.ACCOUNT_NUMBER_NK BRANCH_NO,
  DPRO.ACCOUNT_NAME "ALIAS",
  DPRO.PRICE_COLUMN PC,
  DPRO.DISCOUNT_GROUP_NK DG,
  DPRO.DISCOUNT_GROUP_NAME,
  CONTRACTS.CCOR_COUNT,
  MTX.PC MTX_COUNT,
  SUM ( DPRO.ON_HAND_QTY ) OHB,
  COUNT ( DPRO.DISCOUNT_GROUP_NK ) STOCK_COUNT

FROM ( SELECT DISTINCT
							SWD.REGION_NAME AS DISTRICT,
							WPF.ACCOUNT_NUMBER_NK,
							SWD.ACCOUNT_NAME,
							PC.PRICE_COLUMN,
							PROD.PRODUCT_NK,
							PROD.ALT1_CODE,
							WPF.ON_HAND_QTY,
							DG_DIM.DISCOUNT_GROUP_NK,
							DG_DIM.DISCOUNT_GROUP_NAME
					FROM    (   (   (   SALES_MART.WAREHOUSE_PRODUCT_FACT_LSTMON WPF
													LEFT OUTER JOIN
															DW_FEI.PRODUCT_DIMENSION PROD
													ON (WPF.PRODUCT_NK = PROD.PRODUCT_NK))
											INNER JOIN
													DW_FEI.DISCOUNT_GROUP_DIMENSION DG_DIM
											ON (PROD.DISCOUNT_GROUP_GK = DG_DIM.DISCOUNT_GROUP_GK))
									INNER JOIN
											EBUSINESS.SALES_DIVISIONS SWD
									ON (SWD.ACCOUNT_NUMBER_NK = WPF.ACCOUNT_NUMBER_NK))
							INNER JOIN
									AAA6863.NAT_BU_PRICE_COLUMNS PC
							ON (PC.BRANCH_NUMBER_NK = WPF.ACCOUNT_NUMBER_NK)
				WHERE (SUBSTR (SWD.REGION_NAME, 1, 3) IN
											('D10', 'D11', 'D12', 'D13', 'D14', 'D30', 'D31', 'D32'))
							AND NVL (WPF.STATUS_TYPE, 'STOCK') IN ('STOCK', 'NN', 'NV', 'S', 'NQ')
							AND PROD.DISCOUNT_GROUP_NK IN ('0545', '0540', '1072', '1076')
							AND WPF.ACCOUNT_NUMBER_NK IN ('215', '230')
  ) DPRO
	
	-- snippet below good
	RIGHT OUTER JOIN ( SELECT DISTINCT
									PROD.PRODUCT_NK, WPF.ACCOUNT_NUMBER_NK, DG_DIM.DISCOUNT_GROUP_NK
							FROM    (   (   SALES_MART.WAREHOUSE_PRODUCT_FACT_LSTMON WPF
													LEFT OUTER JOIN
															DW_FEI.PRODUCT_DIMENSION PROD
													ON (WPF.PRODUCT_NK = PROD.PRODUCT_NK))
											INNER JOIN
													DW_FEI.DISCOUNT_GROUP_DIMENSION DG_DIM
											ON (PROD.DISCOUNT_GROUP_GK = DG_DIM.DISCOUNT_GROUP_GK))
									INNER JOIN
											EBUSINESS.SALES_DIVISIONS SWD
									ON (SWD.ACCOUNT_NUMBER_NK = WPF.ACCOUNT_NUMBER_NK)
						WHERE (SUBSTR (SWD.REGION_NAME, 1, 3) IN
													('D10', 'D11', 'D12', 'D13', 'D14', 'D30', 'D31', 'D32'))
									AND NVL (WPF.STATUS_TYPE, 'STOCK') IN ('STOCK', 'NN', 'NV', 'S', 'NQ')
									AND PROD.DISCOUNT_GROUP_NK IN ('0545', '0540', '1072', '1076')
									AND WPF.ACCOUNT_NUMBER_NK IN ( '215', '230' )
									) ALT_COUNT
											ON ALT_COUNT.ACCOUNT_NUMBER_NK = DPRO.ACCOUNT_NUMBER_NK
												AND ALT_COUNT.DISCOUNT_GROUP_NK = DPRO.DISCOUNT_GROUP_NK
												AND ALT_COUNT.PRODUCT_NK = DPRO.PRODUCT_NK
					
	-- snippet below good
	RIGHT OUTER JOIN ( SELECT DISTINCT
											CCOR.BRANCH_NUMBER_NK,
											CCOR.DISC_GROUP,
											COUNT (CCOR.DISC_GROUP) CCOR_COUNT
									FROM DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCOR
								WHERE CCOR.DELETE_DATE IS NULL AND CCOR.EXPIRE_DATE IS NULL
											OR CCOR.EXPIRE_DATE > SYSDATE
								GROUP BY CCOR.BRANCH_NUMBER_NK, CCOR.DISC_GROUP
              ) CONTRACTS
							
         ON CONTRACTS.BRANCH_NUMBER_NK  = DPRO.ACCOUNT_NUMBER_NK
          AND CONTRACTS.DISC_GROUP       = DPRO.DISCOUNT_GROUP_NK
					AND CONTRACTS.BRANCH_NUMBER_NK IN ( '215', '230' )
	
	-- snippet below good
  RIGHT OUTER JOIN ( SELECT DISTINCT
										PRICE.BRANCH_NUMBER_NK, 
										PRICE.DISC_GROUP, 
										COUNT (PRICE.PRICE_COLUMN) PC
								FROM DW_FEI.PRICE_DIMENSION PRICE
							WHERE PRICE.DELETE_DATE IS NULL AND PRICE.PRICE_TYPE = 'G'
							GROUP BY PRICE.BRANCH_NUMBER_NK, PRICE.DISC_GROUP
              ) MTX
							
          ON MTX.BRANCH_NUMBER_NK = DPRO.ACCOUNT_NUMBER_NK
            AND MTX.DISC_GROUP = DPRO.DISCOUNT_GROUP_NK
						AND MTX.BRANCH_NUMBER_NK IN ( '215', '230' )

  
group by
  DPRO.DISTRICT,
  DPRO.ACCOUNT_NUMBER_NK,
  DPRO.ACCOUNT_NAME,
  DPRO.PRICE_COLUMN,
  DPRO.DISCOUNT_GROUP_NK,
  DPRO.DISCOUNT_GROUP_NAME,
  CONTRACTS.CCOR_COUNT,
  MTX.PC
  
order by 
  DPRO.DISTRICT,
  DPRO.ACCOUNT_NUMBER_NK,
  DPRO.ACCOUNT_NAME,
  DPRO.PRICE_COLUMN,
  DPRO.DISCOUNT_GROUP_NK,
  DPRO.DISCOUNT_GROUP_NAME,
  CONTRACTS.CCOR_COUNT
  ;