SELECT
  DPRO.DISTRICT,
  DPRO.ACCOUNT_NUMBER_NK BRANCH_NO,
  DPRO.ACCOUNT_NAME "ALIAS",
  DPRO.PRICE_COLUMN PC,
  DPRO.DISCOUNT_GROUP_NK DG,
  DPRO.DISCOUNT_GROUP_NAME,
  CONTRACTS.CCOR_COUNT,
  MTX.PC MTX_COUNT,
  SUM ( DPRO.ON_HAND_QTY ) OHB,
  COUNT ( DPRO.DISCOUNT_GROUP_NK ) STOCK_COUNT

FROM ( 
      SELECT DISTINCT
        SUBSTR ( SWD.REGION_NAME, 1 ,3 ) DISTRICT,
        WPF.PRODUCT_GK,
        WHSE.ACCOUNT_NUMBER_NK,
        WHSE.ACCOUNT_NAME,
        PC.PRICE_COLUMN,
        WPF.PRODUCT_NK,
        PROD.ALT1_CODE,
        WPF.ON_HAND_QTY,
        PROD.DISCOUNT_GROUP_NK,
        DISC_GRP.DISCOUNT_GROUP_NAME 
      
      FROM 
        DW_FEI.WAREHOUSE_PRODUCT_FACT WPF,
        DW_FEI.WAREHOUSE_DIMENSION WHSE,
        DW_FEI.PRODUCT_DIMENSION PROD,
        DW_FEI.DISCOUNT_GROUP_DIMENSION DISC_GRP,
        DW_FEI.MASTER_VENDOR_DIMENSION VEND,
        DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG,
      	EBUSINESS.SALES_DIVISIONS SWD,
        AAA6863.NAT_BU_PRICE_COLUMNS PC
				
      WHERE WPF.WAREHOUSE_GK     		= WHSE.WAREHOUSE_GK(+)
        AND WPF.PRODUCT_GK         	= PROD.PRODUCT_GK(+)
        AND PROD.DISCOUNT_GROUP_GK 	= DISC_GRP.DISCOUNT_GROUP_GK
        AND PROD.MANUFACTURER      	= VEND.MASTER_VENDOR_NK
        AND PROD.DISCOUNT_GROUP_GK 	= BDG.DISCOUNT_GROUP_GK
        AND WHSE.ACCOUNT_NUMBER_NK 	= SWD.ACCOUNT_NUMBER_NK
        AND PC.BRANCH_NUMBER_NK     = SWD.ACCOUNT_NUMBER_NK
        AND WHSE.ACCOUNT_NUMBER_NK 	= BDG.ACCOUNT_NUMBER_NK
				AND ( SUBSTR ( SWD.REGION_NAME, 1 ,3 ) IN ( 
										'D10', 'D11', 'D12', 'D13', 
										'D14', 'D30', 'D31', 'D32'
									) )

        AND NVL (WPF.STATUS_TYPE, 'STOCK') IN
                ('STOCK', 'NN', 'NV', 'S', 'NQ')
        --AND PROD.DISCOUNT_GROUP_NK 	IN ( '0545', '0540', '1072', '1076' )
        --AND WHSE.ACCOUNT_NAME      IN ('WICHITA')
        AND (WPF.YEARMONTH =
              (SELECT MAX (WPF.YEARMONTH)
                  FROM DW_FEI.WAREHOUSE_PRODUCT_FACT WPF
                  WHERE WPF.YEARMONTH BETWEEN TO_CHAR (
                              TRUNC (
                                 SYSDATE - 
                                  NUMTOYMINTERVAL (3, 'MONTH'),
                                 'MONTH'),
                              'YYYYMM')
                               AND TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')))
  ) DPRO
	
	LEFT JOIN ( SELECT DISTINCT
        WPF.PRODUCT_GK,
        WHSE.ACCOUNT_NUMBER_NK,
        PROD.DISCOUNT_GROUP_NK
      FROM 
        DW_FEI.WAREHOUSE_PRODUCT_FACT WPF,
        DW_FEI.WAREHOUSE_DIMENSION WHSE,
        DW_FEI.PRODUCT_DIMENSION PROD,
        DW_FEI.DISCOUNT_GROUP_DIMENSION DISC_GRP,
        DW_FEI.MASTER_VENDOR_DIMENSION VEND,
        DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG,
				EBUSINESS.SALES_DIVISIONS SWD,
        AAA6863.NAT_BU_PRICE_COLUMNS PC
      
      WHERE WPF.WAREHOUSE_GK     		= WHSE.WAREHOUSE_GK(+)
        AND WPF.PRODUCT_GK         	= PROD.PRODUCT_GK(+)
        AND PROD.DISCOUNT_GROUP_GK 	= DISC_GRP.DISCOUNT_GROUP_GK
        AND PROD.DISCOUNT_GROUP_GK 	= BDG.DISCOUNT_GROUP_GK
        AND WHSE.ACCOUNT_NUMBER_NK 	= SWD.ACCOUNT_NUMBER_NK
        AND PC.BRANCH_NUMBER_NK     = SWD.ACCOUNT_NUMBER_NK
        AND WHSE.ACCOUNT_NUMBER_NK 	= BDG.ACCOUNT_NUMBER_NK
        AND ( SUBSTR ( SWD.REGION_NAME, 1 ,3 ) IN ( 
										'D10', 'D11', 'D12', 'D13', 
										'D14', 'D30', 'D31', 'D32'
									) )
        AND NVL (WPF.STATUS_TYPE, 'STOCK') IN
                ('STOCK', 'NN', 'NV', 'S', 'NQ')
        --AND PROD.DISCOUNT_GROUP_NK 	IN ( '0545', '0540', '1072', '1076' )
        --AND WHSE.ACCOUNT_NAME      IN ('WICHITA')
        AND (WPF.YEARMONTH =
              (SELECT MAX (WPF.YEARMONTH)
                  FROM DW_FEI.WAREHOUSE_PRODUCT_FACT WPF
                  WHERE WPF.YEARMONTH BETWEEN TO_CHAR (
                              TRUNC (
                                 SYSDATE - 
                                  NUMTOYMINTERVAL (3, 'MONTH'),
                                 'MONTH'),
                              'YYYYMM')
                               AND TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')))
							) ALT_COUNT
							
					ON ALT_COUNT.ACCOUNT_NUMBER_NK = DPRO.ACCOUNT_NUMBER_NK
						AND ALT_COUNT.DISCOUNT_GROUP_NK = DPRO.DISCOUNT_GROUP_NK
						AND ALT_COUNT.PRODUCT_GK = DPRO.PRODUCT_GK
					
  LEFT JOIN ( SELECT DISTINCT 
                CCOR.BRANCH_NUMBER_NK,
                CCOR.DISC_GROUP,
                COUNT ( CCOR.DISC_GROUP ) CCOR_COUNT
              FROM DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCOR
              WHERE CCOR.DELETE_DATE          IS NULL
                AND CCOR.EXPIRE_DATE          IS NULL OR CCOR.EXPIRE_DATE > SYSDATE
              GROUP BY CCOR.BRANCH_NUMBER_NK, CCOR.DISC_GROUP
              ) CONTRACTS
							
         ON CONTRACTS.BRANCH_NUMBER_NK  = DPRO.ACCOUNT_NUMBER_NK
          AND CONTRACTS.DISC_GROUP       = DPRO.DISCOUNT_GROUP_NK
					
  LEFT JOIN ( SELECT DISTINCT 
								PRICE.BRANCH_NUMBER_NK,
                PRICE.DISC_GROUP,
                COUNT ( PRICE.PRICE_COLUMN ) PC
                
              FROM DW_FEI.PRICE_DIMENSION PRICE
              WHERE PRICE.DELETE_DATE       IS NULL 
                AND PRICE.PRICE_TYPE         = 'G'
              GROUP BY PRICE.BRANCH_NUMBER_NK,
                PRICE.DISC_GROUP
              ) MTX
							
          ON MTX.BRANCH_NUMBER_NK = DPRO.ACCOUNT_NUMBER_NK
            AND MTX.DISC_GROUP = DPRO.DISCOUNT_GROUP_NK

  
group by
  DPRO.DISTRICT,
  DPRO.ACCOUNT_NUMBER_NK,
  DPRO.ACCOUNT_NAME,
  DPRO.PRICE_COLUMN,
  DPRO.DISCOUNT_GROUP_NK,
  DPRO.DISCOUNT_GROUP_NAME,
  CONTRACTS.CCOR_COUNT,
  MTX.PC
  
order by 
  DPRO.DISTRICT,
  DPRO.ACCOUNT_NUMBER_NK,
  DPRO.ACCOUNT_NAME,
  DPRO.PRICE_COLUMN,
  DPRO.DISCOUNT_GROUP_NK,
  DPRO.DISCOUNT_GROUP_NAME,
  CONTRACTS.CCOR_COUNT
  ;