SELECT SD.DIVISION_NAME,
       SD.REGION_NAME,
       SD.ACCOUNT_NUMBER_NK ACCT_NK,
       SD.ACCOUNT_NAME,
       PR001.DISC_GROUP,
       DG.DISCOUNT_GROUP_NAME,
       PR001.PRICE_COLUMN PC001,
       PR001.BASIS,
       PR001.OPERATOR_USED OPER,
       PR001.MULTIPLIER "001_MULT",
       PR022.PRICE_COLUMN PC022,
       PR022.MULTIPLIER "022_MULT",
       ROUND (
            ( (1 - PR001.MULTIPLIER) - (1 - PR022.MULTIPLIER))
          / (1 - PR001.MULTIPLIER),
          4)
          DECREASE
  FROM DW_FEI.PRICE_DIMENSION PR001
       INNER JOIN EBUSINESS.SALES_DIVISIONS SD
          ON (PR001.BRANCH_NUMBER_NK = SD.ACCOUNT_NUMBER_NK)
       INNER JOIN
       (SELECT PR.BRANCH_NUMBER_NK,
               PR.DISC_GROUP,
               PR.PRICE_TYPE,
               PR.PRICE_COLUMN,
               PR.BASIS,
               PR.OPERATOR_USED,
               PR.MULTIPLIER
          FROM DW_FEI.PRICE_DIMENSION PR
         WHERE     PR.DELETE_DATE IS NULL
               AND PR.PRICE_COLUMN = '022'
               AND PR.PRICE_TYPE = 'G') PR022
          ON (    PR001.BRANCH_NUMBER_NK = PR022.BRANCH_NUMBER_NK
              AND PR001.DISC_GROUP = PR022.DISC_GROUP
              AND PR001.BASIS = PR022.BASIS
              AND PR001.OPERATOR_USED = PR022.OPERATOR_USED)
       INNER JOIN DW_FEI.DISCOUNT_GROUP_DIMENSION DG
          ON (PR001.DISC_GROUP = DG.DISCOUNT_GROUP_NK)
 WHERE     PR001.PRICE_COLUMN = '001'
       AND PR001.DELETE_DATE IS NULL
       AND PR001.OPERATOR_USED = '-'
       AND PR022.MULTIPLIER > PR001.MULTIPLIER
       AND SD.ACCOUNT_NAME NOT IN ('DIST', 'PIPE','CORPSALES')
			 AND  ( SUBSTR ( SD.REGION_NAME, 1 ,3 ) IN ( 
			 	 		'D10', 'D11', 'D12', 'D14', 
				    'D30', 'D31', 'D32', 
				    'D50', 'D51', 'D53'
				 )
			);