SELECT
	PSTAT.ACCOUNT_NUMBER_NK,
	PSTAT.YEARMONTH,
	-- total
	NVL ( SUM ( PSTAT.EXT_SALES_AMOUNT ), 0 ) EXT_SALES,
	NVL ( SUM ( PSTAT.EXT_AVG_COGS_AMOUNT ), 0 ) EXT_AC,
	( SUM ( PSTAT.EXT_SALES_AMOUNT ) - SUM ( PSTAT.EXT_AVG_COGS_AMOUNT ) )
									/ SUM ( PSTAT.EXT_SALES_AMOUNT ) GP_PCT,
	-- outbound
	NVL ( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES )+ SUM ( PSTAT.SPECIAL_SALES ) , 0 ) OB_EXT_SALES,
	NVL ( SUM ( PSTAT.MATRIX_AC ) + SUM ( PSTAT.CCOR_AC )+ SUM ( PSTAT.MANUAL_AC )+ SUM ( PSTAT.SPECIAL_AC ) , 0 ) OB_EXT_AC,
			
	NVL ( 
		( ( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES )+ SUM ( PSTAT.SPECIAL_SALES ) ) -
					( SUM ( PSTAT.MATRIX_AC ) + SUM ( PSTAT.CCOR_AC ) + SUM ( PSTAT.MANUAL_AC ) + SUM ( PSTAT.SPECIAL_AC ) ) ) /
					( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES )+ SUM ( PSTAT.SPECIAL_SALES ) )
			, 0 ) OB_GP_PCT,
			
	-- matrix
	NVL ( SUM ( PSTAT.MATRIX_SALES ), 0 ) MATRIX_SALES,
	NVL ( SUM ( PSTAT.MATRIX_AC ), 0 ) MATRIX_AC,
	NVL ( ( SUM ( PSTAT.MATRIX_SALES ) - SUM ( PSTAT.MATRIX_AC ) )	/ SUM ( PSTAT.MATRIX_SALES ), 0 ) MATRIX_GP_PCT,
	NVL ( SUM ( PSTAT.MATRIX_SALES ) / ( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES ) + SUM ( PSTAT.SPECIAL_SALES ) ), 0 ) MATRIX_USAGE,
	-- ccor
	NVL ( SUM ( PSTAT.CCOR_SALES ), 0 ) CCOR_SALES,
	NVL ( SUM ( PSTAT.CCOR_AC ), 0 ) CCOR_AC,
	NVL ( ( SUM ( PSTAT.CCOR_SALES ) - SUM ( PSTAT.CCOR_AC ) )	/ SUM ( PSTAT.CCOR_SALES ), 0 ) CCOR_GP_PCT,
	NVL ( SUM ( PSTAT.CCOR_SALES ) /
				( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES )+ SUM ( PSTAT.SPECIAL_SALES ) ), 0  ) CONTRACT_USAGE,
	-- manual
	NVL ( SUM ( PSTAT.MANUAL_SALES ), 0 ) MANUAL_SALES,
	NVL ( SUM ( PSTAT.MANUAL_AC ), 0 ) MANUAL_AC,
	NVL ( ( SUM ( PSTAT.MANUAL_SALES ) - SUM ( PSTAT.MANUAL_AC ) ) / SUM ( PSTAT.MANUAL_SALES ), 0 ) MANUAL_GP_PCT,
	NVL ( SUM ( PSTAT.MANUAL_SALES ) /
				( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES )+ SUM ( PSTAT.SPECIAL_SALES ) ), 0 )	MANUAL_USAGE,
	-- specials
	NVL ( SUM ( PSTAT.SPECIAL_SALES ), 0 ) SPECIAL_SALES,
	NVL ( SUM ( PSTAT.SPECIAL_AC ), 0 ) SPECIAL_AC,
	NVL ( ( SUM ( PSTAT.SPECIAL_SALES ) - SUM ( PSTAT.SPECIAL_AC ) ) / SUM ( PSTAT.SPECIAL_SALES ), 0 ) SPECIAL_GP_PCT,
	NVL ( SUM ( PSTAT.SPECIAL_SALES ) /
				( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES )+ SUM ( PSTAT.SPECIAL_SALES ) ), 0 ) SPECIALS_USAGE,
	-- credits
	NVL ( SUM ( PSTAT.CREDIT_SALES ), 0 ) CREDIT_SALES,
	NVL ( SUM ( PSTAT.CREDIT_AC ), 0 ) CREDIT_AC,
	NVL ( ( SUM ( PSTAT.CREDIT_SALES ) - SUM ( PSTAT.CREDIT_AC ) ) / SUM ( PSTAT.CREDIT_SALES ), 0 ) CREDIT_GP_PCT,
	NVL ( SUM ( PSTAT.CREDIT_SALES ) /
				( SUM ( PSTAT.MATRIX_SALES ) + SUM ( PSTAT.CCOR_SALES ) + SUM ( PSTAT.MANUAL_SALES ) + SUM ( PSTAT.SPECIAL_SALES ) ), 0 ) SPECIALS_USAGE,
	
	-- SP- sales < $1,500
	NVL ( SUM ( PSTAT.EX_SALES_LT1500 ), 0 ) SALES_LT1500,
	NVL ( SUM ( PSTAT.EX_AC_LT1500 ), 0 ) AC_LT1500,
	NVL ( ( SUM ( PSTAT.EX_SALES_LT1500 ) - SUM ( PSTAT.EX_AC_LT1500 ) ) / SUM ( PSTAT.EX_SALES_LT1500 ), 0 ) LT_1500_GP_PCT
								
FROM	(	SELECT 
						PM_DATA.YEARMONTH,
						PM_DATA.ACCOUNT_NUMBER_NK,
						PM_DATA.PRODUCT_GK,
						PM_DATA.PRICE_CATEGORY,
						-- total
						SUM ( PM_DATA.EXT_SALES_AMOUNT ) EXT_SALES_AMOUNT,
						SUM ( PM_DATA.EXT_AVG_COGS_AMOUNT ) EXT_AVG_COGS_AMOUNT,
						-- matrix
						SUM (
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'MATRIX' 
								THEN PM_DATA.EXT_SALES_AMOUNT
								ELSE 0
							END )
								MATRIX_SALES,
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'MATRIX' 
								THEN PM_DATA.EXT_AVG_COGS_AMOUNT
								ELSE 0
							END )
								MATRIX_AC,
						-- contracts
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'OVERRIDE' 
								THEN PM_DATA.EXT_SALES_AMOUNT
								ELSE 0
							END )
								CCOR_SALES,
						SUM (
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'OVERRIDE' 
								THEN PM_DATA.EXT_AVG_COGS_AMOUNT
								ELSE 0
							END )
								CCOR_AC,
							-- manual
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'MANUAL' 
								THEN PM_DATA.EXT_SALES_AMOUNT 
								ELSE 0
							END )
								MANUAL_SALES,
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'MANUAL' 
								THEN PM_DATA.EXT_AVG_COGS_AMOUNT
								ELSE 0
							END )
								MANUAL_AC,
						-- specials
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'SPECIAL' 
								THEN PM_DATA.EXT_SALES_AMOUNT
								ELSE 0
							END )
								SPECIAL_SALES,
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'SPECIAL' 
								THEN PM_DATA.EXT_AVG_COGS_AMOUNT
								ELSE 0
							END )
								SPECIAL_AC,
						-- credits
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'CREDITS' 
								THEN PM_DATA.EXT_SALES_AMOUNT
								ELSE 0
							END )
								CREDIT_SALES,
								
						SUM ( 
							CASE
								WHEN PM_DATA.PRICE_CATEGORY = 'CREDITS' 
								THEN PM_DATA.EXT_AVG_COGS_AMOUNT
								ELSE 0
							END )
								CREDIT_AC,
						-- <$1500
						SUM ( 
							CASE
								WHEN PM_DATA.EXT_SALES_AMOUNT > 1500
									AND PM_DATA.PRICE_CATEGORY = 'SPECIAL'
								THEN PM_DATA.EXT_SALES_AMOUNT
								ELSE 0
							END )
								AS "EX_SALES_LT1500",
						SUM ( 
							CASE
								WHEN PM_DATA.EXT_SALES_AMOUNT > 1500
									AND PM_DATA.PRICE_CATEGORY = 'SPECIAL'
								THEN PM_DATA.EXT_AVG_COGS_AMOUNT
								ELSE 0 
							END )
								AS "EX_AC_LT1500"
								
					FROM SALES_MART.PRICE_MGMT_DATA_PROD PM_DATA
					
					
						
						WHERE  PM_DATA.ACCOUNT_NUMBER_NK IN ( 
											'480'--,'88','116','190','230','454','61','1869'
											)
							AND PM_DATA.YEARMONTH BETWEEN 201401 AND 201412
 
					GROUP BY
						PM_DATA.YEARMONTH,
						PM_DATA.ACCOUNT_NUMBER_NK,
						PM_DATA.PRODUCT_GK,
						PM_DATA.PRICE_CATEGORY
	) PSTAT
	
	GROUP BY 
		PSTAT.ACCOUNT_NUMBER_NK,
		PSTAT.YEARMONTH
		
	ORDER BY
		PSTAT.YEARMONTH,
		PSTAT.ACCOUNT_NUMBER_NK ASC
		