SELECT 
	CASE	
		WHEN UPPER(GP_DATA.TYPE_OF_SALE) = 'SHOWROOM DIRECT' 
		THEN 'ShDir'
		ELSE GP_DATA.TYPE_OF_SALE
	END	
		"Sale Type",
	CASE
		WHEN GP_DATA.REGION IS NULL THEN ACCT.ACCOUNT_NAME
		WHEN GP_DATA.REGION = 'EAST' THEN 'EASTERN'
		WHEN GP_DATA.REGION = 'WEST' THEN 'WESTERN'
		ELSE GP_DATA.REGION
	END
		"Region",
	CASE
		WHEN  GP_DATA.WAREHOUSE_NUMBER IN ('141', '148', '348', '473', 
			'563', '580', '1038', '1480', '1554', '1977', '1992', '2052', 
			'2073', '2503', '1591') 
		THEN	 'CINCINNATI'
		WHEN  GP_DATA.WAREHOUSE_NUMBER IN ('124', '541', '1589', ' 1979', 
			'1980', '8124')
		THEN 'COLUMBUS'
		WHEN  GP_DATA.WAREHOUSE_NUMBER IN ('78', '493', '1482', '2050',
			'2072', '8072')
		THEN 'EVANSVILLE'
		WHEN  GP_DATA.WAREHOUSE_NUMBER IN ('290', '750', '1483', '1546',
			'1583', '2579', '2580', '2581')
		THEN 'INDIANAPOLIS'
		WHEN  GP_DATA.WAREHOUSE_NUMBER IN ('93', '213', '291', '479', '566',
			'917', '1484')			
		THEN 'LEXINGTON'
		WHEN  GP_DATA.WAREHOUSE_NUMBER IN ('185', '1481', '2727', '2097')			
		THEN 'LOUISVILLE'
		ELSE ACCT.ACCOUNT_NAME
	END 
		"Branch Name",
	GP_DATA.WAREHOUSE_NUMBER "Whse",
	--change the showroom direct to showroom only
	
	SUM (
		GP_DATA.SLS_SUBTOTAL
		+ GP_DATA.SLS_FREIGHT
		+ GP_DATA.SLS_MISC
		+ GP_DATA.SLS_RESTOCK)
					"Total Sales",
	SUM (GP_DATA.SLS_SUBTOTAL) "Sales, Sub-Total",
	SUM (GP_DATA.SLS_FREIGHT) "Sales, Freight",
	SUM (GP_DATA.SLS_MISC) "Sales, Misc",
	SUM (GP_DATA.SLS_RESTOCK) "Sales, Restock",
	SUM (
		GP_DATA.AVG_COST_SUBTOTAL
		+ GP_DATA.AVG_COST_FREIGHT
		+ GP_DATA.AVG_COST_MISC)
			"Total Cost",
	SUM (GP_DATA.AVG_COST_SUBTOTAL) "Cost, Sub-Total",
	SUM (GP_DATA.AVG_COST_FREIGHT) "Cost, Freight",
	SUM (GP_DATA.AVG_COST_MISC) "Cost, Misc",
	SUM (
		(GP_DATA.SLS_SUBTOTAL
			+ GP_DATA.SLS_FREIGHT
			+ GP_DATA.SLS_MISC
			+ GP_DATA.SLS_RESTOCK)
		- ( GP_DATA.AVG_COST_SUBTOTAL
			+ GP_DATA.AVG_COST_FREIGHT
			+ GP_DATA.AVG_COST_MISC))
				"Total GP$",
	ROUND (
		SUM (
			(  GP_DATA.SLS_SUBTOTAL
				+ GP_DATA.SLS_FREIGHT
				+ GP_DATA.SLS_MISC
				+ GP_DATA.SLS_RESTOCK)
			- (  GP_DATA.AVG_COST_SUBTOTAL
				+ GP_DATA.AVG_COST_FREIGHT
				+ GP_DATA.AVG_COST_MISC))
		/ SUM (
				GP_DATA.SLS_SUBTOTAL
					+ GP_DATA.SLS_FREIGHT
					+ GP_DATA.SLS_MISC
					+ GP_DATA.SLS_RESTOCK),
	3)
		"Total GP%",
	SUM (GP_DATA.INVOICE_LINES) "Total # Lines",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
			THEN(GP_DATA.EXT_SALES)
			ELSE 0
		END)
			"Price Matrix Sales",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
			THEN (GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"Price Matrix Cost",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
			THEN(GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"Price Matrix GP$",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
				THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
				THEN
					CASE
						WHEN GP_DATA.EXT_SALES > 0 
						THEN (GP_DATA.EXT_SALES)
					ELSE 1
				END
			ELSE 1
		END),
	3)
		"Price Matrix GP%",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
				THEN (GP_DATA.EXT_SALES)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.SLS_SUBTOTAL > 0 
				THEN GP_DATA.SLS_SUBTOTAL
				ELSE 1
			END),
	3)
		"Price Matrix Use%$",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
				THEN (GP_DATA.INVOICE_LINES)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.INVOICE_LINES > 0 
				THEN GP_DATA.INVOICE_LINES
				ELSE 1
			END),
		3)
			"Price Matrix Use%#",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
				THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.ROLLUP = 'Total'
				THEN
					CASE
						WHEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS) <> 0
						THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
						ELSE 1
					END
				ELSE 1
			END),
		3)
			"Price Matrix Profit%$",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MATRIX', 'MATRIX_BID')
			THEN (GP_DATA.INVOICE_LINES)
			ELSE 0
		END)
			"Price Matrix # Lines",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
			THEN (GP_DATA.EXT_SALES)
			ELSE 0
		END)
			"Contract Sales",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
			THEN (GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"Contract Cost",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
			THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"Contract GP$",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
				THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
				THEN
					CASE
						WHEN GP_DATA.EXT_SALES > 0 THEN (GP_DATA.EXT_SALES)
						ELSE 1
					END
				ELSE
					1
			END),
		3)
			"Contract GP%",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
				THEN (GP_DATA.EXT_SALES)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.SLS_SUBTOTAL > 0 THEN GP_DATA.SLS_SUBTOTAL
				ELSE 1
			END),
		3)
			"Contract Use%$",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
				THEN (GP_DATA.INVOICE_LINES)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.INVOICE_LINES > 0 
				THEN GP_DATA.INVOICE_LINES
				ELSE 1
			END),
		3)
			"Contract Use%#",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
				THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.ROLLUP = 'Total'
				THEN
					CASE
						WHEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS) <> 0
						THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
						ELSE 1
					END
				ELSE 1
			END),
		3)
			"Contract Profit%$",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN 'OVERRIDE'
			THEN (GP_DATA.INVOICE_LINES)
			ELSE 0
		END)
			"Contract # Lines",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
			THEN (GP_DATA.EXT_SALES)
			ELSE 0
		END)
			"Manual Sales",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
			THEN (GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"Manual Cost",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
			THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"Manual GP$",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
				THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
				THEN
					CASE
						WHEN GP_DATA.EXT_SALES > 0 
						THEN (GP_DATA.EXT_SALES)
						ELSE 1
					END
				ELSE 1
			END),
		3)
			"Manual GP%",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
				THEN (GP_DATA.EXT_SALES)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.SLS_SUBTOTAL > 0 
				THEN GP_DATA.SLS_SUBTOTAL
				ELSE 1
			END),
		3)
			"Manual Use%$",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
				THEN (GP_DATA.INVOICE_LINES)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.INVOICE_LINES > 0 
				THEN GP_DATA.INVOICE_LINES
				ELSE 1
			END),
		3)
			"Manual Use%#",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
				THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
				ELSE 0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.ROLLUP = 'Total'
				THEN
					CASE
						WHEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS) <> 0
						THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
						ELSE 1
					END
				ELSE 1
			END),
		3)
			"Manual Profit%$",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('MANUAL', 'TOOLS', 'QUOTE')
			THEN (GP_DATA.INVOICE_LINES)
			ELSE 0
		END)
			"Manual # Lines",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY NOT IN
				('MATRIX',
				'OVERRIDE',
				'MANUAL',
				'CREDITS',
				'TOOLS',
				'QUOTE',
				'MATRIX_BID',
				'Total')
			THEN (GP_DATA.EXT_SALES)
			ELSE 0
		END)
			"Other Sales",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY NOT IN
				('MATRIX',
				'OVERRIDE',
				'MANUAL',
				'CREDITS',
				'TOOLS',
				'QUOTE',
				'MATRIX_BID',
				'Total')
			THEN (GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"OtherCost",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY NOT IN
				('MATRIX',
				'OVERRIDE',
				'MANUAL',
				'CREDITS',
				'TOOLS',
				'QUOTE',
				'MATRIX_BID',
				'Total')
			THEN (GP_DATA.EXT_SALES-GP_DATA.AVG_COGS)
			ELSE 0
		END)
			"OtherGP$",
	ROUND(
		SUM(
			CASE
				WHEN GP_DATA.PRICE_CATEGORY NOT IN
					('MATRIX',
					'OVERRIDE',
					'MANUAL',
					'CREDITS',
					'TOOLS',
					'QUOTE',
					'MATRIX_BID',
					'Total')
				THEN (GP_DATA.EXT_SALES-GP_DATA.AVG_COGS)
				ELSE 0
			END)
		/SUM(
		CASE
			WHEN GP_DATA.PRICE_CATEGORY NOT IN
				('MATRIX',
				'OVERRIDE',
				'MANUAL',
				'CREDITS',
				'TOOLS',
				'QUOTE',
				'MATRIX_BID',
				'Total')
			THEN
				CASE
					WHEN GP_DATA.EXT_SALES>0
					THEN(GP_DATA.EXT_SALES)
					ELSE 1
				END
			ELSE 1
		END),
	3)
		"OtherGP%",
	ROUND(
		SUM(
			CASE
				WHEN GP_DATA.PRICE_CATEGORY NOT IN
					('MATRIX',
					'OVERRIDE',
					'MANUAL',
					'CREDITS',
					'TOOLS',
					'QUOTE',
					'MATRIX_BID',
					'Total')
				THEN (GP_DATA.EXT_SALES)
				ELSE 0
			END)
			/SUM(
				CASE
					WHEN GP_DATA.SLS_SUBTOTAL>0
					THEN GP_DATA.SLS_SUBTOTAL
					ELSE 1
				END),
		3)
			"OtherUse%$",
	ROUND(
		SUM(
			CASE
				WHEN GP_DATA.PRICE_CATEGORY NOT IN
					('MATRIX',
					'OVERRIDE',
					'MANUAL',
					'CREDITS',
					'TOOLS',
					'QUOTE',
					'MATRIX_BID',
					'Total')
				THEN (GP_DATA.INVOICE_LINES)
				ELSE 0
			END)
			/SUM(
				CASE
					WHEN GP_DATA.INVOICE_LINES>0
					THEN GP_DATA.INVOICE_LINES
					ELSE 1
				END),
			3)
				"OtherUse%#",
   ROUND (
	  SUM (
		 CASE
			WHEN GP_DATA.PRICE_CATEGORY NOT IN
					('MATRIX',
					 'OVERRIDE',
					 'MANUAL',
					 'CREDITS',
					 'TOOLS',
					 'QUOTE',
					 'MATRIX_BID',
					 'Total')
			THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
			ELSE 0
		END)
		/ SUM (
			CASE
				WHEN GP_DATA.ROLLUP = 'Total'
				THEN
					CASE
						WHEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS) <> 0
						THEN (GP_DATA.EXT_SALES - GP_DATA.AVG_COGS)
						ELSE 1
					END
				ELSE 1
			END),
		3)
			"Other Profit%$",
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY NOT IN
				('MATRIX',
				'OVERRIDE',
				'MANUAL',
				'CREDITS',
				'TOOLS',
				'QUOTE',
				'MATRIX_BID',
				'Total')
			THEN (GP_DATA.INVOICE_LINES)
			ELSE 0
		END)
		  "Other # Lines",
	ROUND (
		SUM (
			CASE
				WHEN GP_DATA.PRICE_CATEGORY IN ('CREDITS')
				THEN(GP_DATA.EXT_SALES)
				ELSE	0
			END)
		/ SUM (
			CASE
				WHEN GP_DATA.SLS_SUBTOTAL > 0 
				THEN GP_DATA.SLS_SUBTOTAL
				ELSE 1
			END),
	3)
		"Credits Use%$",
	ROUND (
	SUM (
		CASE
			WHEN GP_DATA.PRICE_CATEGORY IN ('CREDITS')
			THEN	(GP_DATA.INVOICE_LINES)
			ELSE 0
		END)
	/ SUM (
		CASE
			WHEN GP_DATA.INVOICE_LINES > 0 
			THEN GP_DATA.INVOICE_LINES
			ELSE 1
		END),
	3)
		"Credits Use%#",
	SUM (GP_DATA.SLS_FREIGHT - GP_DATA.AVG_COST_FREIGHT)
		"Freight Profit (Loss)"
FROM  AAD9606.GP_TRACKER_WRITER GP_DATA,
	(SELECT WD.ACCOUNT_NAME, WD.ACCOUNT_NUMBER_NK
		FROM DW_FEI.WAREHOUSE_DIMENSION WD
		WHERE (WD.ACTIVE_FLAG = 1) AND (WD.DELETE_DATE IS NULL)
		GROUP BY WD.ACCOUNT_NAME, WD.ACCOUNT_NUMBER_NK) ACCT
WHERE GP_DATA.ACCOUNT_NUMBER = ACCT.ACCOUNT_NUMBER_NK(+)
 	HAVING SUM (GP_DATA.SLS_SUBTOTAL) <> 0

GROUP BY GP_DATA.YEARMONTH,
	CASE
		WHEN GP_DATA.REGION IS NULL THEN ACCT.ACCOUNT_NAME
		WHEN GP_DATA.REGION = 'EAST' THEN 'EASTERN'
		WHEN GP_DATA.REGION = 'WEST' THEN 'WESTERN'
		ELSE GP_DATA.REGION
	END,
	GP_DATA.ACCOUNT_NUMBER,
	ACCT.ACCOUNT_NAME,
	GP_DATA.WAREHOUSE_NUMBER,
	CASE	
		WHEN UPPER(GP_DATA.TYPE_OF_SALE) = 'SHOWROOM DIRECT' 
		THEN 'ShDir'
		ELSE GP_DATA.TYPE_OF_SALE
	END

ORDER BY "Region",
	"Branch Name",
	"Whse",
	"Sale Type"
;