SELECT DISTINCT
			 PROD_DIM.PRODUCT_NK || '*' || WHSE_DIM.WAREHOUSE_NUMBER_NK PRODUCT,
       WHSE_DIM.ACCOUNT_NAME ACCOUNT,
       WPF.ALT_CODE "ALT.1",
       PROD_DIM.PRODUCT_NAME,
			 VENDOR_CODE,
       NVL (WPF.NEW_LIST, NULL) NEW_LIST,
       WPF.LIST_PR,
       WPF.BASIS_2,
       WPF.BASIS_3,
       WPF.REP_COST REP,
       WPF.WHSE_AVG_COST_AMOUNT AC,
			 NULL AS PO_COST,
			 NULL AS PO_DATE,
       PROD_DIM.LIST_PRICE AS M_LIST,
       WPF.DISCOUNT_GROUP_NK DG_NK,
       WPF.LINEBUY LB_NK,
       WPF.STATUS_TYPE ST,
       WPF.UNIT_OF_MEASUREMENT UM,
       WPF.ON_HAND_QTY OHB,
       WPF.DEMAND_12_MONTHS DMD,
       PROD_DIM.MANUFACTURER,
       SWD.DIVISION_NAME
			 
  FROM    (   (   (   DW_FEI.WAREHOUSE_PRODUCT_FACT WPF
                   INNER JOIN
                      DW_FEI.WAREHOUSE_DIMENSION WHSE_DIM
                   ON (WPF.WAREHOUSE_GK = WHSE_DIM.WAREHOUSE_GK))
               INNER JOIN
                  DW_FEI.PRODUCT_DIMENSION PROD_DIM
               ON (WPF.PRODUCT_GK = PROD_DIM.PRODUCT_GK))
           INNER JOIN
              DW_FEI.BRANCH_VENDOR_DIMENSION BVD
           ON (BVD.VENDOR_NK = PROD_DIM.VENDOR_CODE))
       INNER JOIN
          SALES_MART.SALES_WAREHOUSE_DIM SWD
       ON (SWD.WAREHOUSE_NUMBER_NK = WHSE_DIM.WAREHOUSE_NUMBER_NK)
 WHERE     (WHSE_DIM.ACCOUNT_NAME = 'DETROIT')
       --AND (WPF.STATUS_TYPE IN ('T', 'S'))
       --AND (SWD.DIVISION_NAME = 'temp')
       --AND (SWD.REGION_NAME = 'temp')
			 AND WPF.DISCOUNT_GROUP_NK IN ( '1072', '1076' )
       AND (WPF.YEARMONTH = TO_NUMBER (TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')))
	;