/* CREATE TABLE AAA6863.PR_VICT2_CUST_12MO_test3 AS */
SELECT WW_DAT.ACCOUNT_NUMBER,
	  WW_DAT.ACCOUNT_NAME,
	  WW_DAT.YEARMONTH,
	  WW_DAT.DISCOUNT_GROUP_NK DG,
	  WW_DAT.CHANNEL_TYPE,
    SUM(WW_DAT.AC) AS EXT_AC,
    SUM(WW_DAT.SALES) AS EXT_SLS
	  
FROM (
	SELECT IHF.ACCOUNT_NUMBER,
		  CUST.ACCOUNT_NAME,
		  IHF.YEARMONTH,
		  IHF.CHANNEL_TYPE,
		  CASE
			 WHEN ILF.PRODUCT_GK IS NOT NULL
			 THEN PROD.DISCOUNT_GROUP_NK
			 ELSE SP_PROD.SPECIAL_DISC_GROUP
		  END
			 AS DISCOUNT_GROUP_NK,
		  IHF.ORDER_CODE,                             
		  SUM(ILF.EXT_AVG_COGS_AMOUNT) AS AC,
		  SUM(ILF.EXT_SALES_AMOUNT) AS SALES
		  
	FROM DW_FEI.INVOICE_HEADER_FACT IHF,
		  DW_FEI.INVOICE_LINE_FACT ILF,
		  DW_FEI.PRODUCT_DIMENSION PROD,
		  DW_FEI.CUSTOMER_DIMENSION CUST,
		  DW_FEI.SPECIAL_PRODUCT_DIMENSION SP_PROD,
      AAA6863.branch_contacts BC
		  
	WHERE  IHF.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK 
		  AND IHF.ACCOUNT_NUMBER = '3083'
		  AND IHF.CUSTOMER_ACCOUNT_GK = CUST.CUSTOMER_GK
		  AND cust.ar_gl_number NOT IN
				  ('1320', '1360', '1380', '1400',
				   '1401', '1500', '4000', '7100')
		  AND cust.ar_gl_number IS NOT NULL
		  AND NVL (IHF.CONSIGN_TYPE, 'N/A') NOT IN 'R'
		  AND ILF.PRODUCT_GK = PROD.PRODUCT_GK(+)
		  AND ILF.SPECIAL_PRODUCT_GK =
				 SP_PROD.SPECIAL_PRODUCT_GK(+)
		  AND IHF.IC_FLAG = 0
		  AND ILF.SHIPPED_QTY <> 0
		  AND IHF.PO_WAREHOUSE_NUMBER IS NULL
		  AND ILF.YEARMONTH BETWEEN TO_CHAR (
									   TRUNC (
										  SYSDATE
										  - NUMTOYMINTERVAL (
											   12,
											   'MONTH'),
										  'MONTH'),
									   'YYYYMM')
								AND
				 TO_CHAR (TRUNC (SYSDATE, 'MM') - 1,
						  'YYYYMM')
		  AND IHF.YEARMONTH BETWEEN TO_CHAR (
									   TRUNC (
										  SYSDATE
										  - NUMTOYMINTERVAL (
											   12,
											   'MONTH'),
										  'MONTH'),
									   'YYYYMM')
								AND
				 TO_CHAR (TRUNC (SYSDATE, 'MM') - 1,
						  'YYYYMM')
      AND BC.DISTRICT IN ('W50', 'W51', 'W52', 'W53', 'W54')
	  GROUP BY IHF.ACCOUNT_NUMBER,
		  CUST.ACCOUNT_NAME,
		  IHF.YEARMONTH,
		  IHF.CHANNEL_TYPE,
		  
		  CASE
			 WHEN ILF.PRODUCT_GK IS NOT NULL
			 THEN PROD.DISCOUNT_GROUP_NK
			 ELSE SP_PROD.SPECIAL_DISC_GROUP
		  END,
		  IHF.ORDER_CODE) WW_DAT,
		  aaa6863.ww_core_groups core
      
WHERE WW_DAT.DISCOUNT_GROUP_NK IN core.dg_nk
  
GROUP BY WW_DAT.ACCOUNT_NUMBER,
	  WW_DAT.ACCOUNT_NAME,
	  WW_DAT.YEARMONTH,
	  WW_DAT.DISCOUNT_GROUP_NK,
	  WW_DAT.CHANNEL_TYPE
		  ;