CREATE TABLE PRICE_MGMT.PR_PRICE_CAT_HISTORY
AS

SELECT X.YEARMONTH,
       X.INVOICE_NUMBER_GK,
       X.PRICE_CODE,
       X.ORIG_PRICE_CODE,
       X.INVOICE_LINE_NUMBER,
       X.PRODUCT_GK,
       X.SPECIAL_PRODUCT_GK,
       X.EXT_AVG_COGS_AMOUNT,
       X.CORE_ADJ_AVG_COST,
       X.EXT_ACTUAL_COGS_AMOUNT,
       X.EXT_SALES_AMOUNT,
       X.PRICE_CATEGORY,
       X.PRICE_CATEGORY_OVR_PR,
       X.PRICE_CATEGORY_OVR_GR,
       X.PRICE_CATEGORY_FINAL
FROM PRICE_MGMT.PR_PRICE_CAT_HISTORY_X X
GROUP BY X.YEARMONTH,
         X.INVOICE_NUMBER_GK,
         X.PRICE_CODE,
         X.ORIG_PRICE_CODE,
         X.INVOICE_LINE_NUMBER,
         X.PRODUCT_GK,
         X.SPECIAL_PRODUCT_GK,
         X.EXT_AVG_COGS_AMOUNT,
         X.CORE_ADJ_AVG_COST,
         X.EXT_ACTUAL_COGS_AMOUNT,
         X.EXT_SALES_AMOUNT,
         X.PRICE_CATEGORY,
         X.PRICE_CATEGORY_OVR_PR,
         X.PRICE_CATEGORY_OVR_GR,
         X.PRICE_CATEGORY_FINAL