/*
  use for kelly's homeowners DG report
  pivot and send
*/
SELECT PM_DET.YEARMONTH,
       PM_DET.ACCOUNT_NUMBER_NK,
       --PM_DET.SELL_WAREHOUSE_NUMBER_NK,
       PM_DET.SELL_DISTRICT,
       PM_DET.DISCOUNT_GROUP_NK,
       PM_DET.DISCOUNT_GROUP_NK_NAME,
       --PM_DET.CUSTOMER_TYPE,
       --PM_DET.WRITER,
       CASE
        WHEN PM_DET.WRITER LIKE 'h%'
          THEN 'HOMEOWNER'
          ELSE 'OTHER'
        END
          WRITER_TYPE,
       --PM_DET.PRICE_CATEGORY,
       SUM (PM_DET.EXT_SALES_AMOUNT) AS SUM_EXT_SALES_AMOUNT,
       SUM (PM_DET.EXT_AVG_COGS_AMOUNT) AS SUM_EXT_AVG_COGS_AMOUNT
FROM SALES_MART.PRICE_MGMT_DATA_DET PM_DET
  INNER JOIN (SELECT DISTINCT PM_DET.DISCOUNT_GROUP_NK
                FROM SALES_MART.PRICE_MGMT_DATA_DET PM_DET
                WHERE     (PM_DET.YEARMONTH = '201810')         --IN (201807, 201808, 201809))
                      AND PM_DET.WRITER LIKE 'h%'
                      AND (PM_DET.ACCOUNT_NUMBER_NK IN ('39', '1350', '52'))
                      --AND ( SUBSTR ( PM_DET.SELL_DISTRICT, 1, 3 ) IN (
                      --    'D02', 'D20', 'S97'))
                      --AND (PM_DET.CUSTOMER_TYPE IN ('E_ENDUSER', 'E_HMEOWNR_NSC'))
                      AND (PM_DET.IC_FLAG = 'REGULAR')) DG
      ON DG.DISCOUNT_GROUP_NK = PM_DET.DISCOUNT_GROUP_NK
WHERE     (PM_DET.YEARMONTH = '201810') --IN (201807, 201808, 201809))
			AND (PM_DET.ACCOUNT_NUMBER_NK IN ('39', '1350', '52'))
      --AND ( SUBSTR ( PM_DET.SELL_DISTRICT, 1, 3 ) IN ( 
			 	--    'D02', 'D20', 'S97'))
      AND (PM_DET.IC_FLAG = 'REGULAR')
      --AND (PM_DET.CUSTOMER_TYPE IN ('E_ENDUSER', 'E_HMEOWNR_NSC'))
GROUP BY PM_DET.YEARMONTH,
       PM_DET.ACCOUNT_NUMBER_NK,
       --PM_DET.SELL_WAREHOUSE_NUMBER_NK,
       PM_DET.SELL_DISTRICT,
       PM_DET.DISCOUNT_GROUP_NK,
       PM_DET.DISCOUNT_GROUP_NK_NAME,
       --PM_DET.CUSTOMER_TYPE,
       PM_DET.WRITER,
       CASE
        WHEN PM_DET.WRITER LIKE 'h%'
          THEN 'HOMEOWNER'
          ELSE 'OTHER'
        END,
        PM_DET.WRITER    --,
       --PM_DET.PRICE_CATEGORY
;