SELECT sums.EOM_YEARMONTH
          AS YEARMONTH,
       swd.ACCOUNT_NUMBER_NK
          AS ACCT_NK,
       swd.DIVISION_NAME
          AS REGION,
       swd.REGION_NAME
          AS DISTRICT,
       swd.ACCOUNT_NAME
          AS ACCOUNT,
       sums.DISC_GRP,
       dg.DISCOUNT_GROUP_NAME,
       CASE WHEN sums.WRITER LIKE 'h%' THEN 'HOMEOWNER' ELSE 'OTHER' END
          WRITER_TYPE,
       SUM (sums.EXT_SALES_AMT)
          AS EXT_SALES_AMT,
       SUM (sums.CORE_COGS_AMT)
          AS CORE_COGS_AMT
FROM (PRICE_MGMT.PR_PBI_PRICE_CAT_SUMS sums
      INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM swd
         ON (sums.WHSE = swd.WAREHOUSE_NUMBER_NK))
     INNER JOIN DW_FEI.DISCOUNT_GROUP_DIMENSION dg
        ON (sums.DISC_GRP = dg.DISCOUNT_GROUP_NK)
WHERE (sums.EOM_YEARMONTH BETWEEN 201810 AND 201906)
    AND (SUBSTR (SWD.REGION_NAME,1,3) IN ('D02', 'D20', 'S97'))
GROUP BY sums.EOM_YEARMONTH,
         swd.ACCOUNT_NUMBER_NK,
         swd.DIVISION_NAME,
         swd.REGION_NAME,
         swd.ACCOUNT_NAME,
         sums.DISC_GRP,
         dg.DISCOUNT_GROUP_NAME,
         CASE WHEN sums.WRITER LIKE 'h%' THEN 'HOMEOWNER' ELSE 'OTHER' END