SELECT DISTINCT                           --PR_MFG_DG_XREF.MASTER_VENDOR_NAME,
       CONTACTS.RPC,
       DC_SDTC.DIVISION_NAME,
       DC_SDTC.REGION_NAME,
       DC_SDTC.ACCOUNT_NAME,
       DC_SDTC.BRANCH_NK,
       DC_SDTC.CUSTOMER_ALPHA,
       DC_SDTC.CUSTOMER_NAME,
       DC_SDTC.PC,
       DC_SDTC.DISC_GRP,
       DC_SDTC.DISCOUNT_GROUP_NAME,
       DC_SDTC.BASIS,
       DC_SDTC.OPER,
       DC_SDTC.MULT_MODE DC_FACT,
       ROUND((1-BR_DG.RAW_DISC_TO_COST),4) BRANCH_MULT,
       DC_SDTC.BR_SDTC DC_SDTC,
       BR_DG.RAW_DISC_TO_COST BRANCH_SDTC,
       ROUND(((1-DC_SDTC.BR_SDTC)- (1-BR_DG.RAW_DISC_TO_COST))/NULLIF((1-BR_DG.RAW_DISC_TO_COST),0)*100,4) BRANCH_PERCENT_DIFF,
      
       
       /* CASE
          WHEN DC_SDTC.BASIS = 'L' AND DC_SDTC.OPER = 'X' THEN ROUND((((1-BR_DG.RAW_DISC_TO_COST)-DC_SDTC.MULT_MODE)/DC_SDTC.MULT_MODE)*100,4)
          WHEN DC_SDTC.BASIS = 'L' AND DC_SDTC.OPER = '-' THEN ROUND((((1-BR_DG.RAW_DISC_TO_COST)-(1-DC_SDTC.MULT_MODE))/(1-DC_SDTC.MULT_MODE))*100,4)
          --ELSE 0
                    
        END BRANCH_PERCENT_DIFF,  */     
       
       --(((1-DC_SDTC.BR_SDTC)-(1-BR_DG.RAW_DISC_TO_COST))/BR_DG.RAW_DISC_TO_COST)*100 NEW_BRANCH_PERCENT_DIFF,
       --ROUND((((1-BR_DG.RAW_DISC_TO_COST) - (1-DC_SDTC.BR_SDTC))/BR_DG.RAW_DISC_TO_COST)*100,4),   
       --ROUND((((1-BR_DG.RAW_DISC_TO_COST)-DC_SDTC.MULT_MODE)/DC_SDTC.MULT_MODE)*100,4) OLD_BRANCH_PERCENT_DIFF,    
       TO_CHAR (DC_SDTC.LAST_UPDATE, 'MM/DD/YY') LAST_DC_UPDATE,
       DC_DG.STOCK_SKUS,
       OVR.PROD_OVR_COUNT OVR_SKUS,
       ROUND (
          CASE
             WHEN DC_DG.STOCK_SKUS > 0
             THEN
                OVR.PROD_OVR_COUNT / DC_DG.STOCK_SKUS
             ELSE
                0
          END,
          4)
          PCT_OVR,
       PRICE2.PCLOADED,
       DC_SDTC.BUMP,
       BR_DG.DISC_TO_COST BUMPED_SDTC,
       NOTES.SDTC_NOTES
       
  FROM AAD9606.PR_DC_SRC_SDTC DC_SDTC
       INNER JOIN AAD9606.DC_STOCK_DGS_V DC_DG
          ON (LTRIM (DC_SDTC.DISC_GRP, '0') = LTRIM (DC_DG.DC_STK_DG, '0'))
       LEFT OUTER JOIN DW_FEI.BRANCH_DISC_GROUP_DIMENSION BR_DG
          ON (DC_SDTC.ACCOUNT_NAME = BR_DG.ACCOUNT_NAME
              AND DC_SDTC.DISC_GRP = BR_DG.BRANCH_DISC_GROUP_NK)
       LEFT OUTER JOIN AAD9606.PR_DIST_PROD_OVR OVR
          ON (DC_SDTC.PC = OVR.PC AND DC_SDTC.DISC_GRP = OVR.DISC_GRP)
       INNER JOIN USER_SHARED.BRANCH_CONTACTS CONTACTS
          ON (DC_SDTC.BRANCH_NK = CONTACTS.ACCOUNT_NUMBER_NK)
       LEFT JOIN
       (SELECT PRICE.BRANCH_NUMBER_NK,
          PRICE.DISC_GROUP,
          COUNT(PRICE.PRICE_COLUMN) PCLOADED

          FROM DW_FEI.PRICE_DIMENSION PRICE

        WHERE PRICE.DELETE_DATE IS NULL
          AND PRICE.PRICE_TYPE = 'G'

        GROUP BY PRICE.BRANCH_NUMBER_NK,
          PRICE.DISC_GROUP) PRICE2
          ON (DC_SDTC.BRANCH_NK = PRICE2.BRANCH_NUMBER_NK AND DC_SDTC.DISC_GRP = PRICE2.DISC_GROUP)
       LEFT JOIN AAF1046.SDTC_NOTES NOTES
       ON (DC_SDTC.DISC_GRP = NOTES.DGNUM)
       
          
          
 WHERE     --UPPER(RPC) = UPPER(:RPC_REGION) 
 --AND (PR_MFG_DG_XREF.MASTER_VENDOR_NAME LIKE '%' || :VENDOR_NAME || '%')
       BR_DG.RAW_DISC_TO_COST <> DC_SDTC.BR_SDTC
       AND DC_SDTC.MULT_MODE < 1
       AND DC_SDTC.DISCOUNT_GROUP_NAME NOT LIKE '%OTHER%'
       AND DC_SDTC.DISCOUNT_GROUP_NAME NOT LIKE '%MISC%'
       AND DC_SDTC.DISCOUNT_GROUP_NAME NOT LIKE '%DISCONTINUED%'
       AND PRICE2.PCLOADED IS NOT NULL
       AND (NOTES.SDTC_NOTES NOT IN('FABBED','LOCAL_BUY','MARKET_BUY','NONPROGRAM','ECOMMERCE') OR NOTES.SDTC_NOTES IS NULL)
       --AND DC_SDTC.DISC_GRP IN ('0504', '1281')
       
       --AND DC_SDTC.BASIS IN ('2')
ORDER BY CONTACTS.RPC ASC,
         DC_SDTC.REGION_NAME ASC,
         DC_SDTC.ACCOUNT_NAME ASC,
         DC_SDTC.DISC_GRP ASC