SELECT DISTINCT
       SWD.ACCOUNT_NUMBER_NK,
       PROD.DISCOUNT_GROUP_NK,
       SUM (WPF.ON_HAND_QTY) OHB,
       SUM (WPF.DEMAND_12_MONTHS) DEMAND
  FROM    (   SALES_MART.WAREHOUSE_PRODUCT_FACT_LSTMON WPF
           RIGHT OUTER JOIN
              EBUSINESS.SALES_DIVISIONS SWD
           ON (WPF.ACCOUNT_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK))
       INNER JOIN
          DW_FEI.PRODUCT_DIMENSION PROD
       ON (PROD.ALT1_CODE = WPF.ALT_CODE)
 WHERE (SUBSTR (SWD.REGION_NAME, 1, 3) IN
              ('D10', 'D11', 'D12', 'D13', 'D14', 'D30', 'D31', 'D32'))
       AND (SWD.ACCOUNT_NUMBER_NK = '520')
--AND (WPF.DISCOUNT_GROUP_NK = '3915')
GROUP BY SWD.ACCOUNT_NUMBER_NK, PROD.DISCOUNT_GROUP_NK

-- Statement	10/30/2015 9:57:57 AM	0:00:05.927	Query OK	1	0
-- Demand_12_months not even close, OHB spot on
;