/* Matches the Trilogie DPRO */

CREATE TABLE AAA6863.DPRO_TEST AS

SELECT
	WPF.PRODUCT_NK Prod,
	WPF.WAREHOUSE_NK Whse,	
	PROD.ALT1_CODE "Alt-1",
	PROD.PRODUCT_NAME "Prod Description",	
	NVL (PROD.VENDOR_CODE, NULL) V_CODE,
	NVL (WPF.NEW_LIST, NULL) NEW_LIST,
	NVL (WPF.LIST_PR, NULL)  BR_LIST,	
	NVL (WPF.BASIS_2, NULL)  BASIS_2,
	NVL (WPF.BASIS_3, NULL)  BASIS_3,
	NVL (WPF.BASIS_4, NULL)  BASIS_4,
	NVL (WPF.BASIS_5, NULL)  BASIS_5,
	NVL (WPF.BASIS_6, NULL)  BASIS_6,
	NVL (WPF.BASIS_7, NULL)  BASIS_7,
	NVL (WPF.BASIS_8, NULL)  BASIS_8,
	NVL (WPF.BASIS_9, NULL)  BASIS_9,	
	NVL (WPF.REP_COST, NULL) REP,	
	NVL (PROD.LIST_PRICE, NULL) M_LIST,
	NVL (PROD.PRIOR_LIST_PRICE, NULL) PRIOR_MSTR,	  	--new
	NVL (PROD.DISCOUNT_GROUP_NK, NULL) DG,
	NVL (DISC_GRP.DISCOUNT_GROUP_NAME, NULL) DESCR,   	--new
	NVL (PROD.LINEBUY_NK, NULL) LB,	
	NVL (WPF.STATUS_TYPE, NULL) ST,
	NVL (WPF.UNIT_OF_MEASUREMENT, NULL) UM,	
	NVL (WPF.UM_CODE, NULL) UM_CD,	   					--new
	NVL (VEND.MASTER_VENDOR_NAME, NULL) MFR_NAME,	
	NVL (PROD.MANUFACTURER, NULL) MFR,
	NVL (WPF.ON_HAND_QTY, NULL) OHB,	
	NVL (WPF.DEMAND_12_MONTHS, NULL) DMD,
	NVL (WPF.WHSE_AVG_COST_AMOUNT, NULL) AC,	
	WHSE.ACCOUNT_NAME Branch,	
	WHSE.ACCOUNT_NUMBER_NK BR_NO,	
	--local option   									--add
	NVL (BDG.RAW_DISC_TO_COST, NULL) DTC,   			--new
	PROD.OBSOLETE_FLAG OBS   							--new


FROM DW_FEI.WAREHOUSE_PRODUCT_FACT WPF,
	DW_FEI.WAREHOUSE_DIMENSION WHSE,
	DW_FEI.PRODUCT_DIMENSION PROD,
	DW_FEI.DISCOUNT_GROUP_DIMENSION DISC_GRP,
	DW_FEI.LINE_BUY_DIMENSION LINEBUY,
	DW_FEI.MASTER_VENDOR_DIMENSION VEND,
	DW_FEI.BRANCH_DISC_GROUP_DIMENSION BDG,
	AAA6863.BRANCH_CONTACTS BC
		
WHERE WPF.WAREHOUSE_GK = WHSE.WAREHOUSE_GK
	AND WHSE.ACCOUNT_NAME = BDG.ACCOUNT_NAME
	AND WHSE.ACCOUNT_NAME = BC.ALIAS
	--AND BC.RPC = 'Midwest'
	AND BC.DISTRICT IN ('C10','C11','C12')
	AND PROD.DISCOUNT_GROUP_GK = BDG.DISCOUNT_GROUP_GK
	AND (WPF.YEARMONTH =
		TO_NUMBER (TO_CHAR (TRUNC (SYSDATE, 'MM') - 1, 'YYYYMM')))
	/* AND NVL (WPF.STATUS_TYPE, 'STOCK') 
		IN ('STOCK', 'NN', 'NV', 'S', 'NQ') */
	AND WPF.PRODUCT_GK = PROD.PRODUCT_GK
	AND PROD.DISCOUNT_GROUP_GK = DISC_GRP.DISCOUNT_GROUP_GK
	AND PROD.LINEBUY_GK = LINEBUY.LINEBUY_GK
	AND PROD.MANUFACTURER = VEND.MASTER_VENDOR_NK
	--AND PROD.DISCOUNT_GROUP_NK = '4559'
	--AND PROD.OBSOLETE_FLAG = 0 
	--AND PROD.LIST_PRICE <> 0
	--AND PROD.LIST_PRICE = 0
	AND WHSE.ACCOUNT_NAME = 'KNOX'
	--AND WHSE.ACCOUNT_NAME NOT LIKE 'INT%'
	--AND PROD.MANUFACTURER = CORP_PRICE.VENDOR_NO(+)
	
ORDER BY 
	WHSE.ACCOUNT_NAME ASC,
	PROD.DISCOUNT_GROUP_NK ASC,
	PROD.ALT1_CODE
;