SELECT GPT.YEARMONTH,
        SUM(GPT.EXT_SALES) YM
FROM AAA6863.GP_TRACKER_13MO GPT
GROUP BY GPT.YEARMONTH;

SELECT GPT.YEARMONTH,
        count(GPT.YEARMONTH) YM
FROM AAA6863.GP_TRACKER_13MO GPT
GROUP BY GPT.YEARMONTH;

SELECT GPT.YEARMONTH,
        count(GPT.YEARMONTH) YM
FROM AAA6863.GPT_13MO_NOT_CCOR_FY16_17_KPI GPT
GROUP BY GPT.YEARMONTH;