
SELECT
    COD.BRANCH_NUMBER_NK,
    CD.CUSTOMER_NK,
    CD.CUSTOMER_NAME,
    CD.PRICE_COLUMN,
    CD.LAST_SALE,
    COD.DISC_GROUP,
    COD.MASTER_PRODUCT,
    CCD.CONTRACT_ID,
    CCD.CONTRACT_NAME,
    COD.EXPIRE_DATE,
    COD.BASIS,
    COD.OPERATOR_USED,
    COD.MULTIPLIER,
    '' as PM_BASIS,
    '' as PM_OPERATOR_USED,
    '' as PM_MULTIPLIER,
       COD.OVERRIDE_TYPE,
       COD.MAX_PUR_QTY
FROM
    DW_FEI.CUSTOMER_OVERRIDE_DIMENSION COD,
    DW_FEI.CUSTOMER_DIMENSION CD,
    DW_FEI.CUSTOMER_CONTRACT_DIMENSION CCD
WHERE
     COD.CUSTOMER_GK = CD.CUSTOMER_GK(+)
     AND (COD.CUSTOMER_GK = CCD.CUSTOMER_GK(+)
     AND COD.CONTRACT_ID = CCD.CONTRACT_ID(+))
        AND COD.BRANCH_NUMBER_NK IN ('209', '39')
        and cd.delete_date is null
ORDER BY COD.BRANCH_NUMBER_NK,
         CD.CUSTOMER_NK,
         CCD.CONTRACT_ID,
         COD.DISC_GROUP,
      COD.MASTER_PRODUCT