SELECT /*PARALLEL */
         CUSTOMER_DIMENSION.ACCOUNT_NUMBER_NK,
      CUSTOMER_DIMENSION.CUSTOMER_NK,
      CUSTOMER_DIMENSION.CUSTOMER_NAME,
      CUSTOMER_DIMENSION.CITY,
      CUSTOMER_DIMENSION.STATE,
      CUSTOMER_DIMENSION.CUSTOMER_TYPE,
      CUSTOMER_DIMENSION.MAIN_CUSTOMER_NK,
      CUSTOMER_DIMENSION.SALESMAN_CODE,
         CUSTOMER_DIMENSION.PRICE_COLUMN,
         CUSTOMER_DIMENSION.OLD_ACCOUNT_NUMBER_NK,
         CUSTOMER_DIMENSION.OLD_ACCOUNT_NAME,
         CUSTOMER_DIMENSION.OLD_CUSTOMER_NK,
         CUSTOMER_DIMENSION.OLD_PRICE_COLUMN,
         CUSTOMER_DIMENSION.LAST_CONV_DATE,
         CUSTOMER_DIMENSION.BRANCH_WAREHOUSE_NUMBER
FROM     DW_FEI.CUSTOMER_DIMENSION CUSTOMER_DIMENSION
WHERE  CUSTOMER_DIMENSION.ACCOUNT_NUMBER_NK IN ('209', '39')
and customer_dimension.delete_date is null
ORDER BY CUSTOMER_DIMENSION.ACCOUNT_NUMBER_NK,
      CUSTOMER_DIMENSION.CUSTOMER_NK