SELECT SWD.DIVISION_NAME, 
       SWD.REGION_NAME, 
       BG_XREF.BUSINESS_GROUP,
       TPD.ROLL12MONTHS TPD,
       VICT2.PRICE_CATEGORY,
       VICT2.ORIG_PRICE_CATEGORY,
       --VICT2.CUSTOMER_TYPE,
       SUM (VICT2.CORE_ADJ_AVG_COGS) CORE_ADJ_AVG_COGS,
       SUM (VICT2.REP_COGS) EXT_REP_COGS,
       SUM (VICT2.EXT_SALES) EXT_SALES,
       SUM (VICT2.EXT_AVG_COGS) EXT_AVG_COGS,
       SUM (VICT2.LINES) EXT_LINES
       
          
  FROM (AAA6863.PR_VICT2_BG_12MO VICT2
        INNER JOIN AAD9606.PR_SLS_WHSE_DIM SWD
           ON (VICT2.WAREHOUSE_NUMBER = SWD.WAREHOUSE_NUMBER_NK))
       INNER JOIN USER_SHARED.BG_CUSTTYPE_XREF BG_XREF
          ON (VICT2.CUSTOMER_TYPE = BG_XREF.CUSTOMER_TYPE)
       INNER JOIN SALES_MART.TIME_PERIOD_DIMENSION TPD
         ON ( VICT2.YEARMONTH = TPD.YEARMONTH )


 --WHERE VICT2.ACCOUNT_NUMBER = '20'


GROUP BY SWD.DIVISION_NAME, 
       SWD.REGION_NAME, 
       BG_XREF.BUSINESS_GROUP,
       TPD.ROLL12MONTHS,
       VICT2.PRICE_CATEGORY,
       VICT2.ORIG_PRICE_CATEGORY
       ;