SELECT SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       SWD.ACCOUNT_NUMBER_NK,
       SWD.ALIAS_NAME,
       PM_DET.MAIN_CUSTOMER_NK,
       PM_DET.MAIN_CUSTOMER_NAME,
       NVL ( CUST.CUSTOMER_NK, NULL ) AS OLD_MAIN_NK,
       NVL ( CUST.CUSTOMER_NAME, NULL ) AS OLD_CUST_NAME,
       PM_DET.CUSTOMER_TYPE,
       PM_DET.PRICE_COLUMN,
       SUM ( PM_DET.EXT_SALES_AMOUNT ),
       SUM ( PM_DET.EXT_AVG_COGS_AMOUNT )
  FROM   (  (  SALES_MART.PRICE_MGMT_DATA_DET PM_DET
             INNER JOIN
               DW_FEI.CUSTOMER_DIMENSION CUST
             ON ( PM_DET.OLD_MAIN_CUSTOMER_GK = CUST.CUSTOMER_GK ))
          INNER JOIN
            SALES_MART.TIME_PERIOD_DIMENSION TPD
          ON ( TPD.YEARMONTH = PM_DET.YEARMONTH ))
       INNER JOIN
         SALES_MART.SALES_WAREHOUSE_DIM SWD
       ON ( SWD.ACCOUNT_NUMBER_NK = PM_DET.ACCOUNT_NUMBER_NK )
 WHERE ( TPD.FISCAL_YEAR_TO_DATE = 'YEAR TO DATE' )
       AND ( SWD.ACCOUNT_NUMBER_NK = '1550' )
GROUP BY TPD.FISCAL_YEAR_TO_DATE,
         SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ACCOUNT_NUMBER_NK,
         SWD.ALIAS_NAME,
         PM_DET.CUSTOMER_TYPE,
         PM_DET.PRICE_COLUMN,
         PM_DET.MAIN_CUSTOMER_NK,
         PM_DET.MAIN_CUSTOMER_NAME,
         NVL ( CUST.CUSTOMER_NK, NULL ),
         NVL ( CUST.CUSTOMER_NAME, NULL )