SELECT PM_DET.YEARMONTH,
       PM_DET.ACCOUNT_NUMBER_NK,
       PM_DET.WRITER,
       PM_DET.PRICE_CATEGORY,
       PM_DET.CHANNEL_TYPE,
       SUM ( PM_DET.EXT_SALES_AMOUNT ),
       SUM ( PM_DET.EXT_AVG_COGS_AMOUNT )
  FROM SALES_MART.PRICE_MGMT_DATA_DET PM_DET
 WHERE     ( PM_DET.YEARMONTH BETWEEN 201508 AND 201607 )
       AND ( PM_DET.ACCOUNT_NUMBER_NK = '52' )
       AND ( PM_DET.IC_FLAG = 'REGULAR' )
GROUP BY PM_DET.YEARMONTH,
         PM_DET.ACCOUNT_NUMBER_NK,
         PM_DET.WRITER,
         PM_DET.IC_FLAG,
         PM_DET.PRICE_CATEGORY,
         PM_DET.CHANNEL_TYPE