SELECT IHF.ACCOUNT_NUMBER,
       IHF.YEARMONTH,
       SWD.ACCOUNT_NAME,
       CUST.ACCOUNT_NAME
          CUST_ACCT_NAME,
       CUST.MSTR_CUSTNO,
       CUST.MSTR_CUST_NAME,
       CUST.SALESMAN_CODE
          SLSM_CODE,
       IHF.WRITER,
       IHF.OML_ASSOC,
       IHF.OML_ASSOC_INI,
       IHF.OML_ASSOC_NAME,
       IHF.WAREHOUSE_NUMBER,
       IHF.INVOICE_NUMBER_NK,
       IHF.JOB_NAME,
       IHF.CONTRACT_DESCRIPTION,
       IHF.CONTRACT_NUMBER,
       IHF.OML_ASSOC_NAME,
       DECODE (ihf.SALE_TYPE,
               '1', 'Our Truck',
               '2', 'Counter',
               '3', 'Direct',
               '4', 'Counter',
               '5', 'Credit Memo',
               '6', 'Showroom',
               '7', 'Showroom Direct',
               '8', 'eBusiness')
          TYPE_OF_SALE,
       IHF.CHANNEL_TYPE,
       ILF.INVOICE_LINE_NUMBER,
       NVL (SP_PROD.SPECIAL_PRODUCT_NK, PROD.PRODUCT_NK)
          PRODUCT_NK,
       NVL (SP_PROD.ALT_CODE, PROD.ALT1_CODE)
          ALT1_CODE,
       NVL (SP_PROD.SPECIAL_DISC_GROUP, PROD.DISCOUNT_GROUP_NK)
          DISC_GRP,
       NVL (SP_PROD.SPECIAL_PRODUCT_NAME, PROD.PRODUCT_NAME)
          PRODUCT_NAME,
       NVL (SP_PROD.UNIT_OF_MEASURE, PROD.UNIT_OF_MEASURE)
          UM,
       PROD.SELL_MULT,
       ILF.SHIPPED_QTY,
       ILF.EXT_AVG_COGS_AMOUNT,
       ILF.CORE_ADJ_AVG_COST,
       ILF.EXT_SALES_AMOUNT,
       ILF.PRICE_CODE,
       ILF.PRICE_FORMULA,
       ILF.UNIT_NET_PRICE_AMOUNT,
       ILF.UNIT_INV_COST,
       ILF.REPLACEMENT_COST,
       ILF.LIST_PRICE,
       ILF.ORDER_ENTRY_DATE,
       ILF.PO_COST,
       ILF.PO_DATE,
       ILF.PO_NUMBER_NK,
       ILF.PROCESS_DATE,
       CASE
          WHEN ILF.SPECIAL_PRODUCT_GK IS NOT NULL THEN 'SP-'
          ELSE ILF.PRODUCT_STATUS
       END
          PRODUCT_STATUS,

       --ILF.PRODUCT_STATUS,
       ILF.MATRIX,
       ILF.MATRIX_PRICE,
       IHF.CONSIGN_TYPE,
       IHF.ORDER_CODE,
       IHF.CREDIT_CODE,
       IHF.CREDIT_MEMO_TYPE,
       IHF.PO_NUMBER,
       IHF.REF_BID_NUMBER,
       IHF.SOURCE_ORDER,
       IHF.COPY_SOURCE_HIST,
       IHF.SOURCE_SYSTEM,
       IHF.CUSTOMER_ACCOUNT_GK,
       ILF.BUILDER_REBATE,
       ILF.COST_REBATE,
       CUST.MAIN_CUSTOMER_NK,
       CUST.PRICE_COLUMN,
       CUST.JOB_YN,
       CUST.CUSTOMER_NK,
       CUST.CUSTOMER_NAME,
       CUST.CUSTOMER_TYPE,
       -- HVAC_CUST.SIGNUP_DATE,*/
       SWD.ALIAS_NAME
FROM DW_FEI.INVOICE_HEADER_FACT IHF,
     DW_FEI.INVOICE_LINE_FACT ILF,
     DW_FEI.PRODUCT_DIMENSION PROD,
     DW_FEI.SPECIAL_PRODUCT_DIMENSION SP_PROD,
     SALES_MART.SALES_WAREHOUSE_DIM SWD,
     DW_FEI.CUSTOMER_DIMENSION CUST
WHERE     IHF.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK
      AND IHF.CUSTOMER_ACCOUNT_GK = CUST.CUSTOMER_GK
      AND SWD.WAREHOUSE_NUMBER_NK = IHF.WAREHOUSE_NUMBER
      AND IHF.ACCOUNT_NUMBER = 2000
      AND NVL (IHF.CONSIGN_TYPE, 'N/A') NOT IN 'R'
      AND (ILF.PRODUCT_STATUS = 'SP' OR ILF.SPECIAL_PRODUCT_GK IS NOT NULL)
      AND ILF.PRODUCT_GK = PROD.PRODUCT_GK(+)
      AND ILF.SPECIAL_PRODUCT_GK = SP_PROD.SPECIAL_PRODUCT_GK(+)
      AND IHF.IC_FLAG = 0
      --AND ILF.SHIPPED_QTY <> 0
      AND IHF.PO_WAREHOUSE_NUMBER IS NULL
      AND IHF.PROCESS_DATE = ILF.PROCESS_DATE
      AND IHF.YEARMONTH BETWEEN 201808 AND 201907
      AND IHF.YEARMONTH = ILF.YEARMONTH