/* 3 min query */
SELECT IHF.YEARMONTH,
			 BC.ACCOUNT_NK,
       SWD.ACCOUNT_NAME,
       SUM (ILF.EXT_SALES_AMOUNT) AS "SP<1500_SALES",
       SUM (ILF.EXT_AVG_COGS_AMOUNT) AS "SP<1500_AVG_COGS"
  FROM DW_FEI.INVOICE_HEADER_FACT IHF
       INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
          ON (IHF.WAREHOUSE_NUMBER = SWD.WAREHOUSE_NUMBER_NK)
       INNER JOIN DW_FEI.INVOICE_LINE_FACT ILF
          ON (IHF.INVOICE_NUMBER_GK = ILF.INVOICE_NUMBER_GK)
       INNER JOIN SALES_MART.TIME_PERIOD_DIMENSION TPD
          ON (IHF.YEARMONTH = TPD.YEARMONTH)
 		 	 INNER JOIN AAF1046.BRANCH_CONTACTS BC
					ON BC.ACCOUNT_NK = IHF.ACCOUNT_NUMBER

WHERE     ILF.PRODUCT_STATUS = 'SP'
       AND ILF.EXT_SALES_AMOUNT < 1500
       AND IHF.IC_FLAG = 0
       AND IHF.ORDER_CODE <> 'IC'
			 AND BC.DISTRICT = 'C12'
       AND TPD.ROLL12MONTHS = 'LAST TWELVE MONTHS'
GROUP BY IHF.YEARMONTH,
			 BC.ACCOUNT_NK,
       SWD.ACCOUNT_NAME
;
