--single month set at March 13
SELECT  vict2."Acct",
		vict2."Branch",
		vict2."TypeOfSale",
		vict2."OML INI",
		vict2."OML Name",
		vict2."Writer Init",
		vict2."Writer",
		vict2."Assoc Name",
		vict2."Whse",
		vict2."Inv #",
		vict2."Inv Ln",
		vict2."Via",
		vict2."Cust #",
		vict2."Cust Name",
		vict2."Main Cust",
		vict2."PC",
		vict2."Cont Desc",
		vict2."Cont #",
		vict2."Cust Type",
		vict2."Job Y/N",
		vict2."Job Name",
		vict2."Alt1 Code",
		vict2."Product Name",
		vict2."ST",
		vict2."MFGR",
		vict2."Shpd",
		vict2."Unit Net",
		vict2."Price Code",
		vict2."Price Cat",
		vict2."Cat Ovr",
		vict2."Form",
		vict2."Ext Sales",
		vict2."Ext AC",
		vict2."Rep Cost",
		vict2."Inv Cost",
		vict2."Matrix",
		vict2."List",
		vict2."PO Cost",
		vict2."DG",
		vict2."DG Name",
		--vict2."Consign Type",
		vict2."Cr Code",
		vict2."Cr Memo Type",
		vict2."Process",
		vict2."PO Nk",
		vict2."PO #",
		vict2."Pr Ovr",
		vict2."Pr Ovr Bas",
		vict2."Grp Ovr",
		vict2."Trim Form",
		vict2."Ord Cd",
		vict2."Source System",
		vict2."Bid #",
		vict2."Source",
		vict2."Matrix" - "Unit Net" AS "Var",
		vict2."Ext AC" / "Shpd" AS "Unit AC"
		
FROM PR_VICT2_CUST_12MO vict2
  
WHERE 	vict2."Acct" = '56'
	
	AND vict2."Process" = 
		TO_DATE('201303','yyyy/mm')
 
GROUP BY vict2."Acct",
		vict2."Branch",
		vict2."Writer Init",
		vict2."Writer",
		vict2."Assoc Name",
		vict2."OML INI",
		vict2."OML Name",
		vict2."PC",
		vict2."Whse",
		vict2."Inv #",
		vict2."Inv Ln",
		vict2."Via",
		vict2."Cust #",
		vict2."Cust Name",
		vict2."Main Cust",
		vict2."Alt1 Code",
		vict2."Product Name",
		vict2."ST",
		vict2."Shpd",
		vict2."Unit Net",
		vict2."Matrix",
		vict2."Ext Sales",
		vict2."Ext AC",
		vict2."Rep Cost",
		vict2."Inv Cost",
		vict2."List",
		vict2."PO Cost",
		vict2."DG",
		vict2."DG Name",
		vict2."Form",
		vict2."Price Code",
		vict2."Price Cat",
		vict2."Cat Ovr",
		vict2."Bid #",
		vict2."Source",
		vict2."TypeOfSale",
		vict2."Ord Cd",
		vict2."Cont Desc",
		vict2."Cont #",
		vict2."Cust Type",
		vict2."Job Y/N",
		vict2."Job Name",
		vict2."MFGR",
		vict2."Cr Code",
		vict2."Cr Memo Type",
		vict2."Process",
		vict2."PO Nk",
		vict2."PO #",
		vict2."Pr Ovr",
		vict2."Pr Ovr Bas",
		vict2."Grp Ovr",
		vict2."Trim Form",
		vict2."Source System"

ORDER BY vict2."Branch",
		vict2."Writer Init",
		vict2."Cust Name",
		vict2."Cust #",
		vict2."DG",
		vict2."Alt1 Code"
		;