INSERT INTO PRICE_MGMT.BACKUP_CCOR
   SELECT CCOR.BRANCH_NUMBER_NK,
          CCOR.CUSTOMER_NK,
          --CUST.CUSTOMER_NAME, -- NEW
          --CUST.JOB_YN, -- NEW
          CCOR.OVERRIDE_ID_NK,
          CCOR.OVERRIDE_TYPE,
          CCOR.DISC_GROUP DISC_GRP,
          CCOR.MASTER_PRODUCT,
          --PROD.ALT1_CODE, -- NEW
          CCOR.PRODUCT_TEMPLATE,
          CCOR.BASIS,
          CCOR.OPERATOR_USED,
          CCOR.MULTIPLIER,
          CCOR.EXPIRE_DATE,
          CCOR.MAX_PUR_QTY,
          CCOR.MPD_AMOUNT,
          CCOR.EFFECTIVE_PROD,
          CCOR.COST_REBATE,
          CCOR.BUILDER_REBATE,
          CCOR.LAST_UPDATE,
          CCOR.CONTRACT_ID,
          CCOR.DELETE_DATE,
          CONTR.CONTRACT_NAME,
          CONTR.NOTES_OVR_EXPIRE,
          CONTR.OVR_REVIEW,
          CONTR.MKT_FUND_FLAG,
          CONTR.TRIP,
          CONTR.QUOTE_ID,
          CONTR.CLAIMBACK_CUST_ID,
          CONTR.CONTRACT_EXPDATE,
          CONTR.CONTRACT_RESTRICT,
          TO_CHAR (SYSDATE, 'YYYYMM') YEARMONTH,
          TRUNC (SYSDATE) BACKUP_DATE,
          CCOR.INSERT_TIMESTAMP DW_INSERT, -- NEW
          CCOR.CUSTOMER_GK
   FROM DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCOR
        --INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUST
        --ON CCOR.CUSTOMER_GK = CUST.CUSTOMER_GK
        LEFT OUTER JOIN DW_FEI.CUSTOMER_CONTRACT_DIMENSION CONTR
           ON     (CCOR.CUSTOMER_GK = CONTR.CUSTOMER_GK)
              AND (CCOR.BRANCH_NUMBER_NK = CONTR.BRANCH_NUMBER_NK)
              AND (CCOR.CONTRACT_ID = CONTR.CONTRACT_ID)
        --LEFT OUTER JOIN DW_FEI.PRODUCT_DIMENSION PROD
         --  ON CCOR.MASTER_PRODUCT = PROD.PRODUCT_NK
   WHERE     CCOR.BRANCH_NUMBER_NK NOT IN ('39', '5400')
         -- AND CCOR.CUSTOMER_NK = '770'
         -- AND CCOR.BRANCH_NUMBER_NK = '1496'
         AND CCOR.DELETE_DATE IS NULL
         AND CCOR.OVERRIDE_TYPE <> 'C'