INSERT INTO PRICE_MGMT.BACKUP_CLAIMBACK

SELECT CCOR.BRANCH_NUMBER_NK,
       CCOR.CUSTOMER_NK,
       CCOR.OVERRIDE_ID_NK,
       CCOR.OVERRIDE_TYPE,
       CCOR.DISC_GROUP DISC_GRP,
       CCOR.MASTER_PRODUCT,
       --PROD.ALT1_CODE, -- NEW
       CCOR.PRODUCT_TEMPLATE,
       CCOR.BASIS,
       CCOR.OPERATOR_USED,
       CCOR.MULTIPLIER,
       CCOR.EXPIRE_DATE,
       CCOR.MAX_PUR_QTY,
       CCOR.MPD_AMOUNT,
       CCOR.EFFECTIVE_PROD,
       CCOR.COST_REBATE,
       CCOR.BUILDER_REBATE,
       CCOR.LAST_UPDATE,
       CCOR.CONTRACT_ID,
       CONTR.CONTRACT_NAME,
       CONTR.NOTES_OVR_EXPIRE,
       CONTR.OVR_REVIEW,
       CONTR.MKT_FUND_FLAG,
       CONTR.TRIP,
       CONTR.QUOTE_ID,
       CONTR.CLAIMBACK_CUST_ID,
       CONTR.CONTRACT_EXPDATE,
       CONTR.CONTRACT_RESTRICT,
       TO_CHAR (SYSDATE, 'YYYYMM') YEARMONTH,
       TRUNC(SYSDATE) BACKUP_DATE,
       CCOR.INSERT_TIMESTAMP DW_INSERT -- NEW
FROM DW_FEI.CUSTOMER_OVERRIDE_DIMENSION CCOR
     LEFT OUTER JOIN DW_FEI.CUSTOMER_CONTRACT_DIMENSION CONTR
        ON     (CCOR.CUSTOMER_GK = CONTR.CUSTOMER_GK)
           AND (CCOR.BRANCH_NUMBER_NK = CONTR.BRANCH_NUMBER_NK)
           AND (CCOR.CONTRACT_ID = CONTR.CONTRACT_ID)
    -- LEFT OUTER JOIN DW_FEI.PRODUCT_DIMENSION PROD
     --   ON CCOR.MASTER_PRODUCT = PROD.PRODUCT_NK
WHERE     (CCOR.DELETE_DATE IS NULL)
      AND CCOR.BRANCH_NUMBER_NK NOT IN ('39', '5400')
      AND CCOR.OVERRIDE_TYPE IN ('C')