SELECT DISTINCT
       SWD.DIVISION_NAME AS Region,
       SWD.REGION_NAME AS District,
       SWD.ACCOUNT_NUMBER_NK AS ACCT_NK,
       SWD.ACCOUNT_NAME AS Account,
       SWD.WAREHOUSE_NUMBER_NK AS WHSE_NK,
       SWD.WAREHOUSE_NAME AS WAREHOUSE,
       SWD.ALIAS_NAME AS ALIAS,
       MEGA.REG_ACCT_NUM,
       MEGA.REG_ACCT_NAME,
       MEGA.PC
  FROM   SALES_MART.SALES_WAREHOUSE_DIM SWD
       LEFT OUTER JOIN
         AAE0376.MEGA_BRANCHES MEGA
       ON ( SWD.WAREHOUSE_NUMBER_NK = MEGA.WHSE )
ORDER BY SWD.DIVISION_NAME ASC,
         SWD.REGION_NAME ASC,
         SWD.ACCOUNT_NUMBER_NK ASC,
         MEGA.REG_ACCT_NAME ASC,
         SWD.WAREHOUSE_NUMBER_NK ASC;