SELECT DISTINCT SWD.DIVISION_NAME,
                SWD.REGION_NAME,
                SWD.ACCOUNT_NUMBER_NK,
                SWD.ACCOUNT_NAME MACHINE_NAME,
                SWD.ALIAS_NAME
  FROM SALES_MART.SALES_WAREHOUSE_DIM SWD
ORDER BY SWD.REGION_NAME ASC, SWD.ACCOUNT_NUMBER_NK ASC
;