SELECT
  DISTINCT SWD.DIVISION_NAME AS REGION,
           SWD.REGION_NAME AS DISTRICT,
           CCOR.BRANCH_NUMBER_NK AS BRANCH_NO,
           SWD.ACCOUNT_NAME AS BRANCH_NAME,
           CUST.CUSTOMER_NK,
           CCOR.CONTRACT_ID,
           CCOR.OVERRIDE_ID_NK,
           CCOR.OVERRIDE_TYPE,
           CCOR.DISC_GRP,
           DG_DIM.DISCOUNT_GROUP_NAME,
           PROD_DIM.ALT1_CODE,
           PROD_DIM.PRODUCT_NAME,
           CCOR.EXPIRE_DATE,
           CCOR.BASIS,
           CCOR.OPERATOR_USED,
           CCOR.MULTIPLIER,
           CCOR.LAST_UPDATE,
           CCOR.EFFECTIVE_PROD,
           CCOR.MASTER_PRODUCT,
           CCOR.PRODUCT_TEMPLATE,
           CCOR.MAX_PUR_QTY,
           CCOR.MPD_AMOUNT,
           CCOR.COST_REBATE,
           CCOR.BUILDER_REBATE,
           CCOR.DELETE_DATE,
           CCOR.CONTRACT_NAME,
           CCOR.NOTES_OVR_EXPIRE,
           CCOR.OVR_REVIEW,
           CCOR.MKT_FUND_FLAG,
           CCOR.TRIP,
           CCOR.QUOTE_ID,
           CCOR.CLAIMBACK_CUST_ID,
           CCOR.CONTRACT_EXPDATE,
           CCOR.CONTRACT_RESTRICT,
           CCOR.YEARMONTH,
           CCOR.BACKUP_DATE
FROM
  PRICE_MGMT.BACKUP_CCOR CCOR
  INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUST
    ON CUST.CUSTOMER_NK = CCOR.CUSTOMER_NK AND
       CCOR.BRANCH_NUMBER_NK = CUST.ACCOUNT_NUMBER_NK
  INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
    ON SWD.ACCOUNT_NUMBER_NK = CCOR.BRANCH_NUMBER_NK
  INNER JOIN DW_FEI.PRODUCT_DIMENSION PROD_DIM
    ON CCOR.MASTER_PRODUCT = PROD_DIM.PRODUCT_NK
  INNER JOIN DW_FEI.DISCOUNT_GROUP_DIMENSION DG_DIM
    ON CCOR.DISC_GRP = DG_DIM.DISCOUNT_GROUP_NK
WHERE
  CCOR.BRANCH_NUMBER_NK = '2000'