SELECT SWD.DIVISION_NAME AS REGION,
       SWD.REGION_NAME AS DISTRICT,
       SWD.ACCOUNT_NUMBER_NK AS ACCOUNT_NK,
       SWD.ACCOUNT_NAME,
       CUST.CUSTOMER_NK,
       CUST.CUSTOMER_NAME,
       CUST.MAIN_CUSTOMER_NK AS MAIN_CUST_NK,
       NULL AS JOB_YN,
       BU_CMBK.CONTRACT_ID,
       BU_CMBK.OVERRIDE_ID_NK,
       BU_CMBK.OVERRIDE_TYPE,
       BU_CMBK.DISC_GRP,
       DG_DIM.DISCOUNT_GROUP_NAME,
       PROD_DIM.ALT1_CODE,
       PROD_DIM.PRODUCT_NAME,
       BU_CMBK.EXPIRE_DATE,
       BU_CMBK.BASIS,
       BU_CMBK.OPERATOR_USED,
       BU_CMBK.MULTIPLIER,
       BU_CMBK.LAST_UPDATE,
       BU_CMBK.EFFECTIVE_PROD,
       BU_CMBK.YEARMONTH,
       BU_CMBK.CLAIMBACK_CUST_ID,
       BU_CMBK.CONTRACT_EXPDATE,
       BU_CMBK.CONTRACT_RESTRICT,
       BU_CMBK.QUOTE_ID,
       ROWNUM
FROM (((SALES_MART.SALES_WAREHOUSE_DIM SWD
        INNER JOIN PRICE_MGMT.BACKUP_CLAIMBACK BU_CMBK
           ON (SWD.ACCOUNT_NUMBER_NK = BU_CMBK.BRANCH_NUMBER_NK))
       INNER JOIN DW_FEI.CUSTOMER_DIMENSION CUST
          ON (BU_CMBK.CUSTOMER_NK = CUST.CUSTOMER_NK))
      INNER JOIN DW_FEI.DISCOUNT_GROUP_DIMENSION DG_DIM
         ON (BU_CMBK.DISC_GRP = DG_DIM.DISCOUNT_GROUP_NK))
     INNER JOIN DW_FEI.PRODUCT_DIMENSION PROD_DIM
        ON (BU_CMBK.MASTER_PRODUCT = PROD_DIM.PRODUCT_NK)
WHERE     BU_CMBK.YEARMONTH = TO_CHAR (TRUNC (SYSDATE, 'MM') - 1,  'YYYYMM')
      --AND (BU_CMBK.YEARMONTH = '201805'))
      --AND (SWD.ACCOUNT_NUMBER_NK  IN ('1480', '2000')) 
      AND (SWD.ACCOUNT_NUMBER_NK = '2000')    --IN ('1480', '2000'))
      --AND (BU_CMBK.DISC_GRP IN ('1072', '1076'))
      --AND (CUST.CUSTOMER_NK IN ('123', '234'))
      --AND (CUST.MAIN_CUSTOMER_NK IN ('1234', '2345'))
      AND (PROD_DIM.ALT1_CODE = 'GGPG154211541')
      AND ROWNUM <= '100'
      ORDER BY ROWNUM;