SELECT MEGA.WHSE,
       MEGA.REG_ACCT_NAME,
       MEGA.REG_ACCT_NUM,
       MEGA.NEW_ACCT_NAME,
       MEGA.ACCT_NUM,
       MEGA.PC,
       MEGA.DIST
  FROM AAE0376.MEGA_BRANCHES MEGA
ORDER BY MEGA.DIST ASC,
         MEGA.REG_ACCT_NAME ASC,
         MEGA.ACCT_NUM ASC,
         MEGA.REG_ACCT_NUM ASC,
         MEGA.WHSE ASC
		;