/* monthly pcca archive */
--DROP TABLE AAA6863.A_PCCA_CENT_201506;

CREATE TABLE AAA6863.A_PCCA_CENT_201512
AS
  SELECT SUBSTR ( SWD.REGION_NAME,
                 1,
                 3
         )
           DIST,
         CUST.ACCOUNT_NUMBER_NK BR_NO,
         CUST.ACCOUNT_NAME BRANCH,
         CUST.CUSTOMER_ALPHA "ALPHA",
         CUST.GROSS_SALES,
         CUST.CUSTOMER_NK CUST_NO,
         CUST.CUSTOMER_NAME CUST_NAME,
         CUST.MAIN_CUSTOMER_NK MAIN_CUST,
         CUST.KOB_TYPE KOB,
         CUST.CUSTOMER_TYPE C_TYPE,
         CUST.PRIOR_CUSTOMER_TYPE PRIOR_TYPE,
         CUST.BMI_BUDGET_CUST_TYPE,
         CUST.BMI_REPORT_CUST_TYPE,
         CUST.PRICE_COLUMN PC,
         CUST.OLD_PRICE_COLUMN PRIOR_PC,
         CUST.BRANCH_WAREHOUSE_NUMBER WHSE,
         CUST.SALESMAN_CODE SLSM,
         CUST.SEC_SLSM SEC_SLSM,
         CUST.ALT_SLSM ALT_SLSM,
         CUST.MSTR_CUSTNO MSTR_NO,
         CUST.MSTR_CUST_NAME MSTR_NAME,
         CUST.MSTR_TYPE MSTR_TYPE,
         CUST.GSA_LINK GSA,
         CUST.LAST_SALE LAST_SALE,
         CUST.JOB_YN JOB_YN,
         CUST.CROSS_ACCT CROSS_ACCT,
         CUST.CROSS_CUSTOMER_NK CROSS_NO
    FROM   DW_FEI.CUSTOMER_DIMENSION CUST
         INNER JOIN
           EBUSINESS.SALES_DIVISIONS SWD
         ON ( CUST.ACCOUNT_NUMBER_NK = SWD.ACCOUNT_NUMBER_NK )
   WHERE ( SUBSTR ( SWD.REGION_NAME,
                   1,
                   3
          ) ) IN
             ( 'D10',
              'D11',
              'D12',
              'D13',
              'D14',
              'D30',
              'D31',
              'D32',
              'D50',
              'D51',
              'D53' )
  ORDER BY SUBSTR ( SWD.REGION_NAME,
                   1,
                   3
           ), CUST.ACCOUNT_NAME, CUST.CUSTOMER_NK;

GRANT SELECT ON AAA6863.A_PCCA_CENT_201512 TO PUBLIC;

SELECT *
  FROM AAA6863.A_PCCA_CENT_201512 PCCA
 WHERE PCCA.DIST BETWEEN 'D10' AND 'D14';

SELECT *
  FROM AAA6863.A_PCCA_CENT_201512 PCCA
 WHERE PCCA.DIST BETWEEN 'D30' AND 'D32';

SELECT *
  FROM AAA6863.A_PCCA_CENT_201512 PCCA
 WHERE PCCA.DIST IN ('D50', 'D51', 'D53');