SELECT SWD.DIVISION_NAME,
       SWD.REGION_NAME,
       SWD.ACCOUNT_NAME,
       HIER.HILEV, HIER.DET1, HIER.DET2, HIER.DET6,
       --DTL.DISCOUNT_GROUP_NK,
       --DTL.DISCOUNT_GROUP_NAME,
       --DTL.ALT1_CODE,
       DTL.TYPE_OF_SALE,
       PC.SUB_CATEGORY,
       --BLD.MEAN_RETAIL,
       --BLD.MIN_RETAIL,
       --BLD.MAX_RETAIL,
       --BLD."Map_Price" IMAP,
       ROUND(AVG (DTL.UNIT_NET_PRICE_AMOUNT),2) MEAN_FEI,
       MIN (DTL.UNIT_NET_PRICE_AMOUNT) MIN_FEI,
       MAX (DTL.UNIT_NET_PRICE_AMOUNT) MAX_FEI,
       DTL.PRICE_CATEGORY,
       SUM (DTL.EXT_SALES_AMOUNT) FEI_SLS,
       SUM (DTL.EXT_AVG_COGS_AMOUNT) AVG_COGS,
       SUM ( (DTL.UNIT_NET_PRICE_AMOUNT - BLD.MIN_RETAIL) * DTL.SHIPPED_QTY)
          LOST_SLS,
       SUM (BLD.MIN_RETAIL * DTL.SHIPPED_QTY) BUILD_SLS
  FROM AAE0376.PR_VICT2_CUST_12MO DTL
       INNER JOIN AAD9606.PR_BUILD_COM_PRICE BLD
          ON (DTL.PRODUCT_NK = BLD.MPN)
       INNER JOIN SALES_MART.SALES_WAREHOUSE_DIM SWD
          ON DTL.WAREHOUSE_NUMBER = SWD.WAREHOUSE_NUMBER_NK
       INNER JOIN USER_SHARED.BUSGRP_PROD_HIERARCHY HIER
        ON DTL.DISCOUNT_GROUP_NK = HIER.DISCOUNT_GROUP_NK
       LEFT OUTER JOIN AAD9606.PR_COLUMN_XREF_2014 PC
       ON DTL.PRICE_COLUMN = LTRIM(PC.PC)
 WHERE     DTL.UNIT_NET_PRICE_AMOUNT > BLD.MIN_RETAIL
       AND DTL.PRICE_CATEGORY <> 'CREDITS'
GROUP BY SWD.DIVISION_NAME,
         SWD.REGION_NAME,
         SWD.ACCOUNT_NAME,
         HIER.HILEV, HIER.DET1, HIER.DET2, HIER.DET6,
         --DTL.DISCOUNT_GROUP_NK,
         --DTL.DISCOUNT_GROUP_NAME,
         --DTL.ALT1_CODE,
         DTL.TYPE_OF_SALE,
         PC.SUB_CATEGORY,
         --BLD.MEAN_RETAIL,
         --BLD.MIN_RETAIL,
         --BLD.MAX_RETAIL,
         --BLD."Map_Price",
         DTL.PRICE_CATEGORY